### ISSUE TITLE
 error: reference to __device__ function '__nvvm_bar0_popc' in __host__ function while converting YOLO

### ISSUE THREAD

**Issue by rohanmahapatra** [ROCm/HIP#1035]
Hello,

I am getting an error when I try to convert gemm.c from YOLO (https://github.com/pjreddie/darknet/blob/master/src/gemm.c)

Below is the command I used.  

$ ./hipify-clang ../../../darknet_hipify/src/gemm.c --cuda-path=/p/hal/private/libs/cuda-8.0/ -I../../../darknet_hipify/include/ -I../../../darknet_hipify/src/ -print-stats -DCUDA_VERSION=8000 -DGPU
In file included from <built-in>:1:
In file included from /nobackup/hipify-clang/clang+llvm-6.0.1-x86_64-linux-gnu-ubuntu-16.04/lib/clang/6.0.1/include/__clang_cuda_runtime_wrapper.h:185:
/afs/cs.wisc.edu/u/m/a/mahapatra/private/gpu_project/hipify/darknet_hipify/src/device_functions.hpp:258:10: error: reference to __device__ function '__nvvm_bar0_popc' in __host__ function
  return __nvvm_bar0_popc(predicate);

Do you know what could be wrong. Any leads could be helpful.

Thank you,
Rohan

**Comment by ppanchad-amd** [comment]
@rohanmahapatra Apologies for the lack of response. Do you still need assistance with this ticket? Thanks!
