### ISSUE TITLE
When is __HIPCC__ defined?

### ISSUE THREAD

**Issue by ex-rzr** [ROCm/HIP#1103]
https://github.com/ROCm-Developer-Tools/HIP/blob/master/docs/markdown/hip_porting_guide.md#identifying-the-compiler-hcc-hip-clang-or-nvcc:
> The macro `__HIPCC__` is set if either `__HCC__`, `__HIP__` or `__CUDACC__` is defined.

However, it seems that it's defined only when hipcc is used:
https://github.com/ROCm-Developer-Tools/HIP/blob/master/bin/hipcc#L231

or `__CUDACC__` is defined:
https://github.com/ROCm-Developer-Tools/HIP/blob/master/include/hip/hip_common.h#L37

But when I use hcc directly (without hipcc), `__HIPCC__` is not defined (but it should be because `__HCC__` is defined).

So either the code or the documentation is incorrect.

**Comment by ppanchad-amd** [comment]
@ex-rzr Apologies for the lack of response. Do you still need assistance with this ticket? Thanks!
