### ISSUE TITLE
__lanemask_lt is broken

### ISSUE THREAD

**Issue by harakas** [ROCm/HIP#1161]
__lanemask_lt() is used in the common CUDA pattern "warp-aggregated atomics".
See https://devblogs.nvidia.com/cuda-pro-tip-optimized-filtering-warp-aggregated-atomics/ for reference.
The current implementation in HIP is broken. The equivalent implementation should be:

`int64_t __lanemask_lt() { return ((int64_t)1 << __lane_id()) - 1; }
`

**Comment by nartmada** [comment]
Hi @harakas, apologies for the lack of response from AMD.  Do you still need assistance with this ticket?  Thanks.

**Comment by nartmada** [comment]
Closing this ticket as it is stale.  @harakas, please re-open if you still see this issue with latest ROCm 6.0.2 (HIP 6.0.32831).  Thanks.
