### ISSUE TITLE
Hidden symbol attribute in public header file

### ISSUE THREAD

**Issue by AdhocMan** [ROCm/HIP#1166]
When compiling device code with hipcc into a static library and linking it with other host code compiled with gcc into a single executable, I'm getting the following error:
```
/usr/bin/ld: main: hidden symbol `_ZN8hip_impl22hipLaunchKernelGGLImplEmRK4dim3S2_jP12ihipStream_tPPv' in src/libspfft_device.a(local_transpose_kernels.cu.o) is referenced by DSO
```

Removing the following line fixes this issue for me:
https://github.com/ROCm-Developer-Tools/HIP/blob/9ddb0291fda35081a828f9cd98595c9c3df03f65/include/hip/hcc_detail/functional_grid_launch.hpp#L120

Maybe I'm missing something here, but hiding symbols of functions, which are declared and used in public header files, might not be a good idea.

**Comment by nartmada** [comment]
Hi @AdhocMan, apologies for the lack of response from AMD.  Can you please check latest ROCm 6.0.2 (HIP 6.0.32831) to see if your query has been addressed? Thanks.

**Comment by nartmada** [comment]
Closing the ticket as it is stale.  @AdhocMan, please re-open if you still see the issue in latest ROCm 6.0.2 (HIP 6.0.32831).  Thanks.
