### ISSUE TITLE
hipMalloc() failed in docker container

### ISSUE THREAD

**Issue by huangjw08** [ROCm/HIP#1170]
I am using HIP and openMPI to develop my program in Docker. My Server has 4 Vega 20(MI60, Device Memory is 32GB).  When I using '**mpirun -np 4 ./myApp**' to lauch four processes to start my program. I found rank-0 (process 0) failed to executed 
`hipMalloc(&dvptr, numbytes).` 

I have already assigned each device to each process to make sure each process has enough device memory to allocate.
And I use GDB to attach rank-0, the value of numbytes is 13488181248. (Obviously, My GPU has enough memory to allocate).  **But the dvptr is NULL after invoke hipMalloc(). And it returns hipErrorMemoryAllocation.** 
However, other processes have allocated 13435703296 bytes device memory in respective devices successfully. 
But the program is aborted cause rank-0's dvptr is NULL.  
I also call **hipMemGetInfo(&mem_free, &mem_total)** to query memory info.  The mem_free=34038743032, mem_total=34342961152. And both variants do not change after invoke hipMalloc() in rank-0. 
**Therefore, I want to ask is there any caution to invoke hipMalloc() or something special to develop HIP program in Docker? Why dvptr is NULL after invoking hipMalloc()?**

_**The Docker Environment:
Ubuntu 16.04.2 LTS
ROCm 2.3
HIP version: 1.5.19123
OpenMPI 1.10**_

_**The Server Environment:
Ubuntu 16.04.6 LTS
Docker version 18.09.5
ROCm 2.3
HIP version: 1.5.19123**_

**Comment by nartmada** [comment]
Hi @huangjw08, apologies for the lack of response.  Can you please check latest ROCm 6.0.2 (HIP 6.0.32831) to see if your query has been addressed? Thanks.

**Comment by nartmada** [comment]
Closing the ticket as it is stale.  @huangjw08, please re-open if you still see this issue with latest ROCm 6.0.2 (HIP 6.0.32831).
