### ISSUE TITLE
The support of hipStreamPerThread

### ISSUE THREAD

**Issue by holyprince** [ROCm/HIP#1174]
When I port a program from cuda to hip, the raw program use cudaStreamPerThread and I change it to hipStreamPerThread directly and the compile process is successful. 
But when I run my ported program, it often breaks down randomly when the program running 
```hipStreamSynchronize(hipStreamPerThread) or hipMemcpyAsync ```
and often the problem is :
```
Memory access fault by GPU node-4 (Agent handle: 0x175c520) on address 0x2b97609be000
```
From this website, I can not find the support of hipStreamPerThread :
https://rocm-documentation.readthedocs.io/en/latest/ROCm_API_References/HIP-API.html#hip-api

So I want to ask whether the hipStreamPerThread is supported by hip?

**Comment by ppanchad-amd** [comment]
@holyprince Apologies for the lack of response.  Do you still need assistance with this ticket? Thanks!

**Comment by ppanchad-amd** [comment]
@holyprince Closing ticket. Please re-open if you still need assistance. Thanks!
