### ISSUE TITLE
About bank conflict problem

### ISSUE THREAD

**Issue by ghostplant** [ROCm/HIP#1178]
For AMD ROCm, is there bank conflicts problem? Specifically,

1) Is there shared memory bank conflicts? What about the data stride between banks?
2) Is there local memory bank conflicts? What about the data stride between banks?
3) Is there global memory bank conflicts?
4) Is there inter-block bank conflicts?

**Comment by ppanchad-amd** [comment]
@ghostplant Apologies for the lack of response.  Do you still require assistance with this ticket? Thanks!

**Comment by ppanchad-amd** [comment]
@ghostplant Closing issue. Please re-open if you still need assistance. Thanks!
