### ISSUE TITLE
Give better error message when trying to launch a kernel in a work-group that required too many vgprs

### ISSUE THREAD

**Issue by davidrohr** [ROCm/HIP#1185]
Perhaps this should rather go to HCC, but I'll start here:

I have ported a CUDA application to HIP, and it was failing with:
`### HCC STATUS_CHECK Error: HSA_STATUS_ERROR_INVALID_ISA (0x100f) at file:mcwamp_hsa.cpp line:1192`
After adding the ROCr Debugging Agent, I received the error message
```
Queue error state in GPU agent: AMD gfx906
Node: 1
Queue ID: 139980058624000 (Out of VGPRs;)
```
It seems this is related to a too large work-group, such that the GPU does not have sufficient VGPRs. At least it works when I reduce the work-group size. Unfortunately the original error message about HSA_STATUS_ERROR_INVALID_ISA is pretty misleading, it would be better to explicitly state that there are not enough GPU registers.

**Comment by ppanchad-amd** [comment]
@davidrohr Apologies for the lack of response. Can you please test with latest ROCm 6.1.0 (HIP 6.1)? If resolved, please close ticket. Thanks!

**Comment by davidrohr** [comment]
Sorry, don't have time to follow up and retest these old tickets, closing.
