### ISSUE TITLE
Compiling an HIP kernel source is slow

### ISSUE THREAD

**Issue by ghostplant** [ROCm/HIP#1198]
Usually it takes over 10-20 seconds to finish compiling only one kernel (written in C device code), is it possible to shorten such compilation time, and any side effects?

**Comment by ghostplant** [comment]
Any suggestions? A thousand-line source kernel spends hours to finish its compilation.

**Comment by b-sumner** [comment]
It's hard to say much without an example.  Can you provide access to a minimal self-contained example (i.e. a single file that can be simply compiled with hipcc as opposed to a pointer to a repo containing hundreds of files and a full build system)?

**Comment by ghostplant** [comment]
@b-sumner Usually, a TVM engine compiling a large model can generate a thousand-line source codes containing many sub kernels. It takes 3-4 hours to compile such files, while nvcc takes only within 1 minute.

**Comment by ghostplant** [comment]
@b-sumner clang-9 from rocm is sequantially executed, while nvcc compiles source codes using multiple process.

**Comment by ghostplant** [comment]
@b-sumner I think the problem is caused by putting too many `__global__` kernels within one source file. It is possible to split them into a standalone source file in which there is only one `__global__` kernel defined.
However, is it really safe for `hipicc` compiler to parallel build different HIP source codes without any temporary-resource conflicts or problems?

**Comment by ppanchad-amd** [comment]
@ghostplant Apologies for the lack of response. Can you please test with latest ROCm 6.1.0 (HIP 6.1)? If resolved, please close ticket. Thanks!

**Comment by ppanchad-amd** [comment]
@ghostplant Closing ticket. Please re-open if issue still occurs with latest ROCm 6.1.1 Thanks!
