### ISSUE TITLE
hipStreamAddCallback, stream not blocked by callback (HIP/HCC)

### ISSUE THREAD

**Issue by tdd11235813** [ROCm/HIP#1205]
Refering to this [issue](https://github.com/ComputationalRadiationPhysics/alpaka/issues/794) in Alpaka, it seems that [hipStreamAddCallback](https://rocm-documentation.readthedocs.io/en/latest/ROCm_API_References/HIP_API/Stream-Management.html#hipstreamaddcallback) callback execution does not block the hip/hcc stream, so when two callbacks are added to the same stream by two different threads, we get a race condition.
```c++
// stream is initialized like this (only disables automatic default-stream sync)
ALPAKA_HIP_RT_CHECK(           
    hipStreamCreateWithFlags(  
        &m_HipQueue,           
        hipStreamNonBlocking));
```
[callback includes a wait](https://github.com/ComputationalRadiationPhysics/alpaka/blob/6f43249c216a5cd9c041b8f8be59c6f220298905/include/alpaka/queue/QueueHipRtBlocking.hpp#L225), which however does not block the hip stream, thus our task execution becomes thread-unsafe (and our tests fail).

```c++
static void HIPRT_CB hipRtCallback(hipStream_t /*queue*/, hipError_t /*status*/, void *arg)                           
{                                                                                                                     
   /* ... */                                                                                                                 
    // Wait for the executing thread to finish the task if it has not already finished.                               
    std::unique_lock<std::mutex> lock(pCallbackSynchronizationData->m_mutex);                                         
    if(pCallbackSynchronizationData->state != CallbackState::finished)                                                
    {                                                                                                                 
        pCallbackSynchronizationData->m_event.wait( /* ... */ );
    }                                                                                                                 
}                                                                                                                     
```
```c++
// call is
ALPAKA_HIP_RT_CHECK(hipStreamAddCallback(
                    queue.m_spQueueImpl->m_HipQueue,
                    hipRtCallback,
                    pCallbackSynchronizationData.get(),
                    0u));
```
it is either a bug in the HIP implementation or a documentation error see
https://rocm-documentation.readthedocs.io/en/latest/ROCm_API_References/HIP_API/Stream-Management.html#hipstreamaddcallback: `The callback will block later work in the stream until it is finished.`

**Comment by tdd11235813** [comment]
attached you find a minimal working example without Alpaka dependency. Issues reproduced with hip-clang on a Radeon VII (gfx906, Vega 20) GPU.
> (hipcc)
> HIP version: 3.1.20022-fae85cf
> clang version 10.0.0 (https://github.com/RadeonOpenCompute/clang a09d37e345861d68f9768939e485d265f4fcb0ce) (https://github.com/RadeonOpenCompute/llvm.git 7b3a23a98c2e869965f64657ee11a7cb13feffa5)

[hipstreamcb.zip](https://github.com/ROCm-Developer-Tools/HIP/files/4206643/hipstreamcb.zip)

**Comment by srinivamd** [comment]
@tdd11235813 PR https://github.com/ROCm-Developer-Tools/HIP/pull/1915 seems to fix some of the failures. Still work in progress.

**Comment by psychocoderHPC** [comment]
@jeffdaily and @srinivamd I tested with HIP 4.0.0 if this issues is already solved. 
From the comment https://github.com/ROCm-Developer-Tools/HIP/pull/1934#issuecomment-597777838 all should work now.

My tests still show that there are synchronization issues. 
@jeffdaily Do you used https://github.com/ROCm-Developer-Tools/HIP/issues/1205#issuecomment-586462855 as test case without any changes? I played with the example and if I test only `queueShouldNotBeEmptyWhenLastTaskIsStillExecutingAndIsEmptyAfterProcessingFinished` and comment out the other tests it mostly passed but sometimes failed. It looked like there is a data race somewhere.

Testsystem:
- Ubuntu 20.04
- ROCm/HIP 4.0.0 installed with `apt`
- GPU: 2xRadeon VII

**Comment by psychocoderHPC** [comment]
> @jeffdaily and @srinivamd I tested with HIP 4.0.0 if this issues is already solved.
> From the comment [#1934 (comment)](https://github.com/ROCm-Developer-Tools/HIP/pull/1934#issuecomment-597777838) all should work now.
> 
> My tests still show that there are synchronization issues.
> @jeffdaily Do you used [#1205 (comment)](https://github.com/ROCm-Developer-Tools/HIP/issues/1205#issuecomment-586462855) as test case without any changes? I played with the example and if I test only `queueShouldNotBeEmptyWhenLastTaskIsStillExecutingAndIsEmptyAfterProcessingFinished` and comment out the other tests it mostly passed but sometimes failed. It looked like there is a data race somewhere.
> 
> Testsystem:
> 
> * Ubuntu 20.04
> * ROCm/HIP 4.0.0 installed with `apt`
> * GPU: 2xRadeon VII

Hold on it looked like it is an issue in your example we provided.
The implementation of `HIP_ASSERT_IGNORE` in combination with how we used this macro together with `hipStreamQuery()` to query the status of a queue is wrong. When getting `hipErrorNotReady` back we can not say if the queue is empty or not.
The result should not be used for check where we need to know if the queue is empty or not.

**Comment by psychocoderHPC** [comment]
This issue can be **closed**. The issue reported https://github.com/ROCm-Developer-Tools/HIP/issues/1205#issuecomment-787770694 was a mistake in our code base and will be fixed https://github.com/alpaka-group/alpaka/pull/1266. 

@SarbojitAMD could you please close this issue. I am not sure if @tdd11235813 is still checking GitHub because he switched the company last year :-(
