### ISSUE TITLE
Error when assigning the value of constant variables to memory on the heap

### ISSUE THREAD

**Issue by JL-Cheng** [ROCm/HIP#1219]
In my demo , I defined a constant variable like following .
```
__constant__ float gpu_A[MAX_LENGTH]; 

...

hipMemcpyToSymbol(HIP_SYMBOL(gpu_A),A,length*sizeof(float),0,hipMemcpyHostToDevice);
```
Then I want to calculate the transposition of matrix **gpu_A** on the device , there are two possible methods .
1. Dynamically allocating memory on the heap .
```
float *AT = (float*)malloc((w*h) * sizeof(float));
for(int i=0;i<w;i++)
{
    for(int j=0;j<h;j++)
    {
        AT[i*h+j] = gpu_A[j*w+i];
    }
}
free(AT);
```
2. Statically allocating memory on the stack . 
```
float AT[MAX_LENGTH];
for(int i=0;i<w;i++)
{
    for(int j=0;j<h;j++)
    {
        AT[i*h+j] = gpu_A[j*w+i];
    }
}
```
However , the 1st method doesn't work , while only the 2nd method works . I don't know why the 1st method doesn't work .

**Comment by ppanchad-amd** [comment]
@JL-Cheng Apologies for the lack of response. Can you please test with latest ROCm 6.1.0 (HIP 6.1)? If resolved, please close ticket. Thanks!

**Comment by ppanchad-amd** [comment]
@JL-Cheng Closing ticket. Please re-open if issue still occurs with latest ROCm 6.1.1 Thanks!
