### ISSUE TITLE
How to store data on SGPR within HIP kernels?

### ISSUE THREAD

**Issue by ghostplant** [ROCm/HIP#1272]
I'd like to store some common data which is constant and shared by a wavefront, and SGPR seems to be a good place but I don't know what kind of instructions to use to achieve this?

**Comment by b-sumner** [comment]
There's no direct way to achieve this.  The language doesn't include such a concept.

The compiler does try to use SGPRs when appropriate.  You can increase the likelihood that the compiler will use an SGPR by providing as much evidence as possible that the value is uniform across the current wave, block, or grid.

**Comment by ghostplant** [comment]
@b-sumner Thanks! So would it be possible if directly writing ISA assembly codes to achieve it?
For example, something like this:
```sh
v_mov_b32_e32 s1, 10       // s1 := 10
```

**Comment by b-sumner** [comment]
Yes, writing your kernels in assembly is a supported option, but, as with any assembly coding, you have to obey the ABI.  You also need to be aware that code which assembles and works correctly on one device may not assemble on a different device.

Note that inline asm is not an option - the compiler will reuse the SGPR for its own purposes.

**Comment by ghostplant** [comment]
@b-sumner OK, I know that.

**Comment by ghostplant** [comment]
@b-sumner A problem related to this is whether it is possible to disasm HSACO binary blob back to ISA asm sources? Rocm-documentation doesn't explain clearly for this case, and it is a little old as well which is for gfx803.

**Comment by b-sumner** [comment]
llvm-objdump --triple=amdgcn-amd-amdhsa -mcpu=gfxXYX -disassemble codeobj.so

**Comment by ghostplant** [comment]
@b-sumner That's great. I just found that only latest llvm-9 can disasm gfx906 so I ever failed to disasm it using an old llvm version.

I just check the differences of original ISA code and Disasm output code generated by llvm-objdump, the latter lacks some header descriptions and tail descrptions, like:
```sh
    .text
    .hsa_code_object_version 2,1
    .hsa_code_object_isa 9,0,6,"AMD","AMDGPU"
...
        debug_mode = 0
        enable_ieee_mode = 1
        enable_wgp_mode = 0
        enable_mem_ordered = 0
        enable_fwd_progress = 0
        enable_sgpr_private_segment_wave_byte_offset = 0
        user_sgpr_count = 6
        enable_trap_handler = 0
        enable_sgpr_workgroup_id_x = 1
        enable_sgpr_workgroup_id_y = 1
        enable_sgpr_workgroup_id_z = 1
        enable_sgpr_workgroup_info = 0
..
..
    s_endpgm
.Lfunc_end0:
    .size   _Z9Conv11x11PfS_S_, .Lfunc_end0-_Z9Conv11x11PfS_S_
                                        ; -- End function
    .section    .AMDGPU.csdata
; Kernel info:
; codeLenInByte = 2628
; NumSgprs: 30
; NumVgprs: 76
; ScratchSize: 0
; MemoryBound: 0
; FloatMode: 192
; IeeeMode: 1
; LDSByteSize: 5132 bytes/workgroup (compile time only)
; SGPRBlocks: 3
; VGPRBlocks: 18
; NumSGPRsForWavesPerEU: 30
; NumVGPRsForWavesPerEU: 76
; WaveLimiterHint : 1
; COMPUTE_PGM_RSRC2:USER_SGPR: 6
; COMPUTE_PGM_RSRC2:TRAP_HANDLER: 0
; COMPUTE_PGM_RSRC2:TGID_X_EN: 1
; COMPUTE_PGM_RSRC2:TGID_Y_EN: 1
; COMPUTE_PGM_RSRC2:TGID_Z_EN: 1
; COMPUTE_PGM_RSRC2:TIDIG_COMP_CNT: 2
    .protected  __ocml_ldexp_f16
    .protected  __ocml_nan_f16
..
```
So is there a automatic way to re-fill these items after I do some instruction modifition on the disasm code which might change the actual number of VGPRs and SGPRs, if not possible, what about any manually way to fill some critical header/tail items with a minimal effort?

**Comment by ghostplant** [comment]
@b-sumner From https://rocm-documentation.readthedocs.io/en/latest/ROCm_Tools/ROCm-Tools.html: `Currently, a programmer must manually set all non-default values to provide the necessary information. Hopefully, this situation will change with new updates that bring automatic register counting and possibly a new syntax to fill that structure.`

**Comment by b-sumner** [comment]
What you really want to do is to ask the compiler to dump the original assembly.  That will be complete.  Generic disassemblers do not know about all of the AMDGPU specifics and will generally not give you text which will assemble back into the same code object.

**Comment by b-sumner** [comment]
By the way, if you feel the need to tweak compiler generated ISA, please don't keep that to yourself.  Please let AMD know when you think the compiler could be doing a better job.

**Comment by ghostplant** [comment]
@b-sumner I'd like to read from a ISA code, do some optimizations and make it consume less memory or registers, so I need to analyze and edit on existing ISA codes. There might be possibilities for succeeded tries or failure tries, so it requires some time to verify something. The obstacle at the moment is that meta-information is lacking in the disasm ISA codes, so I cannot make it back to hsaco to test it.

**Comment by ghostplant** [comment]
@b-sumner If I uses KMDUMPISA=1, it only works for kernels from source, not working for rocblas/miopen kernels.

**Comment by zgu153522** [comment]
I want to add that KMDUMPISA=1 doesn't seem to be working for me.  My original workflow with HCC was to use KMDUMPISA when calling hcc, edit the isa file, and then use clang to assemble it.  With hipcc I could use genco, but it doesn't have the right fields or format or something to be able to assemble using clang.  I'm on ROCm 3.7, and by all other accounts that I've read KMDUMPISA is supposed to still work.

**Comment by yxsamliu** [comment]
you can pass -save-temps to hipcc, which will save the ISA as .s files.

**Comment by zgu153522** [comment]
Thanks sam.  I seem to be able to do this flow without errors:
1. hipcc -save-temps file.cpp -o file.o
2. Edit the ISA / kernel metadata
3. /opt/rocm/llvm/bin/clang -target amdgcn-amd-amdhsa -mcpu=gfx906 -o file.hsaco file-hip-amdgcn-amd-amdhsa-gfx906.s

Will verify separately that the result hsaco behaves as expected with HSA runtime
