### ISSUE TITLE
build HIP from source at ARM64 Ubuntu 18.04 error for Experimental_ROC 2.0.0 01_10_hip.sh 

### ISSUE THREAD

**Issue by NothingButShadow** [ROCm/HIP#1291]
ubuntu@linux:~$ uname -a
Linux linux 4.15.0-51-generic #55ubuntu3-Ubuntu SMP Sat Jul 6 03:48:13 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux

ubuntu@linux:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

ubuntu@linux:~$ hcc -v
HCC clang version 8.0.0 (git@gitee.com:binutils/hcc-clang-upgrade.git 6ec3c61e09fbb60373eaf5a40021eb862363ba2c) (git@gitee.com:binutils/llvm.git d5938b6c383ee68cf93d4508e48836d6118517e2) (based on HCC 1.3.19301-d099b6b5-6ec3c61e09-d5938b6c383 )
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/bin
Found candidate GCC installation: /usr/lib/gcc/aarch64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/aarch64-linux-gnu/7.4.0
Found candidate GCC installation: /usr/lib/gcc/aarch64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/aarch64-linux-gnu/7.4.0
Candidate multilib: .;
Selected multilib: .;
lib/Driver/ToolChains/Gnu.cpp
Found HCC installation: /opt/rocm/bin/..

ubuntu@linux: $ cd ~/rocm/Experimental_ROC/distro_install_scripts/Ubuntu/Ubuntu_18.04/src_install/component_scripts
ubuntu@linux:~/rocm/Experimental_ROC/distro_install_scripts/Ubuntu/Ubuntu_18.04/src_install/component_scripts$ ./01_10_hip.sh 
+ trap 'lastcmd=$curcmd; curcmd=$BASH_COMMAND' DEBUG
++ lastcmd=
++ curcmd='trap '\''errno=$?; print_cmd=$lastcmd; if [ $errno -ne 0 ]; then echo "\"${print_cmd}\" command failed with exit code $errno."; fi'\'' EXIT'
+ trap 'errno=$?; print_cmd=$lastcmd; if [ $errno -ne 0 ]; then echo "\"${print_cmd}\" command failed with exit code $errno."; fi' EXIT
++ lastcmd='trap '\''errno=$?; print_cmd=$lastcmd; if [ $errno -ne 0 ]; then echo "\"${print_cmd}\" command failed with exit code $errno."; fi'\'' EXIT'
++ curcmd='source "$BASE_DIR/common/common_options.sh"'
+ source /home/ubuntu/rocm/Experimental_ROC/distro_install_scripts/Ubuntu/Ubuntu_18.04/src_install/component_scripts/common/common_options.sh
++ ROCM_VERSION_BRANCH=roc-2.0.x
++ ROCM_VERSION_MAJOR=2
++ ROCM_VERSION_MINOR=0
++ ROCM_VERSION_PATCH=0
++ ROCM_VERSION_TAG=roc-2.0.0
++ ROCM_VERSION_LONG=2.0.89
++ ROCM_CMAKE_SHA=6240bb3
++ ROCMINFO_SHA=1bb0ccc
++ ROCM_CLANG_OCL_SHA=688fe5d
++ ROCM_ATMI_SHA=4dd14ad
++ ROCM_ROCRAND_SHA=7278524
++ ROCM_MIOPENGEMM_SHA=9547fb9
++ ROCM_HIPTHRUST_SHA=e0b8fe2
++ ROCM_ROCBLAS_TAG=v2.0.0
++ ROCM_HIPBLAS_TAG=v0.12.1.0
++ ROCM_ROCFFT_TAG=v0.8.8
++ ROCM_ROCSPARSE_TAG=v1.0.1
++ ROCM_HIPSPARSE_TAG=v1.0.2
++ ROCM_ROCALUTION_TAG=v1.3.7
++ ROCM_MIOPEN_TAG=1.7.0
++ ROCM_RCCL_TAG=0.7.1
++ ROCM_ROCK_CHECKOUT=tags/roc-2.0.0
++ ROCM_ROCT_CHECKOUT=tags/roc-2.0.0
++ ROCM_ROCR_CHECKOUT=tags/roc-2.0.0
++ ROCM_SMI_CHECKOUT=tags/roc-2.0.0
++ ROCM_CMAKE_CHECKOUT=6240bb3
++ ROCM_ROCMINFO_CHECKOUT=1bb0ccc
++ ROCM_ROCPROFILER_CHECKOUT=tags/roc-2.0.0
++ ROCM_OPENCL_CHECKOUT=tags/roc-2.0.0
++ ROCM_CLANG_OCL_CHECKOUT=688fe5d
++ ROCM_HCC_CHECKOUT=tags/roc-2.0.0
++ ROCM_HIP_CHECKOUT=tags/roc-2.0.0
++ ROCM_DEVICE_LIBS_CHECKOUT=tags/roc-2.0.0
++ ROCM_ATMI_CHECKOUT=4dd14ad
++ ROCM_COMGR_CHECKOUT=tags/roc-2.0.0
++ ROCR_DEBUG_AGENT_CHECKOUT=tags/roc-2.0.0
++ ROCM_BANDWIDTH_TEST_CHECKOUT=tags/roc-2.0.0
++ ROCM_ROCBLAS_CHECKOUT=tags/v2.0.0
++ ROCM_HIPBLAS_CHECKOUT=tags/v0.12.1.0
++ ROCM_ROCFFT_CHECKOUT=tags/v0.8.8
++ ROCM_ROCRAND_CHECKOUT=7278524
++ ROCM_ROCSPARSE_CHECKOUT=tags/v1.0.1
++ ROCM_HIPSPARSE_CHECKOUT=tags/v1.0.2
++ ROCM_ROCALUTION_CHECKOUT=tags/v1.3.7
++ ROCM_MIOPENGEMM_CHECKOUT=9547fb9
++ ROCM_MIOPEN_CHECKOUT=tags/1.7.0
++ ROCM_HIPTHRUST_CHECKOUT=e0b8fe2
++ ROCM_SMILIB_CHECKOUT=tags/roc-2.0.0
++ ROCM_RCCL_CHECKOUT=tags/0.7.1
++ PRINT_HELP=false
++ ROCM_FORCE_BUILD_ONLY=false
++ ROCM_FORCE_GET_CODE=false
++ ROCM_LOCAL_INSTALL=false
++ ROCM_INSTALL_PREREQS=false
++ ROCM_BUILD_DEBUG=false
++ ROCM_DEBUG_LEVEL=0
++ ROCM_CMAKE_BUILD_TYPE=Release
++ ROCM_CHANGE_INPUT=false
++ ROCM_INPUT_DIR=/opt/rocm
++ ROCM_CHANGE_OUTPUT=false
++ ROCM_OUTPUT_DIR=/opt/rocm
++ ROCM_FORCE_PACKAGE=true
++ ROCM_PACKAGE_DIR=/home/ubuntu/rocm/deb
++ ROCM_SAVE_SOURCE=true
++ ROCM_SOURCE_DIR=/home/ubuntu/rocm/ubuntu
++ HAVE_PROXYCHAINS=true
++ TARGET_ARCH=arm64
++ ROCM_FORCE_YES=false
++ ROCM_FORCE_NO=false
++ IS_MIOPEN_CALL=false
++ MIOPEN_FORCE_OPENCL=false
++ IS_MIOPEN_CALL=false
++ ROCM_SUDO_COMMAND=sudo
++ ROCM_CPACK_RPM_PERMISSIONS='-DCPACK_RPM_DEFAULT_DIR_PERMISSIONS=OWNER_READ;OWNER_WRITE;OWNER_EXECUTE;GROUP_READ;GROUP_EXECUTE;WORLD_READ;WORLD_EXECUTE'
++ lastcmd='source "$BASE_DIR/common/common_options.sh"'
++ curcmd='parse_args "$@"'
+ parse_args
++ getopt -o hbglrd:i:o:p:s:yn --long help,build_only,get_code_only,local,required,debug:,input_dir:,output_dir:,package:,source_dir:,miopen_option,force_opencl -n parse-options --
+ cd build
++ lastcmd='cd build'
++ curcmd='export VERBOSE=1'
+ export VERBOSE=1
+ VERBOSE=1
++ lastcmd='export VERBOSE=1'
++ curcmd='export CXX=hcc'
+ export CXX=hcc
+ CXX=hcc
++ lastcmd='export CXX=hcc'
++ curcmd='cmake .. -DHIP_PLATFORM=hcc -DHCC_HOME=${ROCM_INPUT_DIR}/hcc/ -DHSA_PATH=${ROCM_INPUT_DIR} -DCMAKE_BUILD_TYPE=${ROCM_CMAKE_BUILD_TYPE} -DCMAKE_INSTALL_PREFIX=${ROCM_OUTPUT_DIR}/hip/ -DCPACK_PACKAGING_INSTALL_PREFIX=${ROCM_OUTPUT_DIR}/ -DCPACK_GENERATOR=DEB -DCMAKE_CXX_FLAGS="-v" -DHSA_AMDGPU_GPU_TARGET="gfx803,gfx900"'
+ cmake .. -DHIP_PLATFORM=hcc -DHCC_HOME=/opt/rocm/hcc/ -DHSA_PATH=/opt/rocm -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/opt/rocm/hip/ -DCPACK_PACKAGING_INSTALL_PREFIX=/opt/rocm/ -DCPACK_GENERATOR=DEB -DCMAKE_CXX_FLAGS=-v -DHSA_AMDGPU_GPU_TARGET=gfx803,gfx900
Re-run cmake no build system arguments
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is Clang 8.0.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/rocm/bin/hcc
-- Check for working CXX compiler: /opt/rocm/bin/hcc -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- HIP Platform: hcc
-- HIP Compiler: hcc
-- Looking for HCC in: /opt/rocm/hcc/. Found version: 1.3.19301-d099b6b5-6ec3c61e09-d5938b6c383
-- Looking for HSA runtime in: /opt/rocm
-- HIP will be installed in: /opt/rocm/hip
-- Testing targets will not be available. To enable them please ensure that the HIP installation directory is writeable. Use -DCMAKE_INSTALL_PREFIX to specify a suitable location
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CPACK_GENERATOR
    CPACK_PACKAGING_INSTALL_PREFIX
    HSA_AMDGPU_GPU_TARGET

-- Build files have been written to: /home/ubuntu/rocm/ubuntu/HIP/build
++ lastcmd='cmake .. -DHIP_PLATFORM=hcc -DHCC_HOME=${ROCM_INPUT_DIR}/hcc/ -DHSA_PATH=${ROCM_INPUT_DIR} -DCMAKE_BUILD_TYPE=${ROCM_CMAKE_BUILD_TYPE} -DCMAKE_INSTALL_PREFIX=${ROCM_OUTPUT_DIR}/hip/ -DCPACK_PACKAGING_INSTALL_PREFIX=${ROCM_OUTPUT_DIR}/ -DCPACK_GENERATOR=DEB -DCMAKE_CXX_FLAGS="-v" -DHSA_AMDGPU_GPU_TARGET="gfx803,gfx900"'
++ curcmd=make
+ make
...
...
...
 "/opt/rocm/hcc/bin/clang-8" -cc1 -D__KALMAR_HC__=1 -D__HCC_HC__=1 -triple aarch64-unknown-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -main-file-name hip_memory.cpp -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -fuse-init-array -target-cpu generic -target-feature +neon -target-abi aapcs -fallow-half-arguments-and-returns -dwarf-column-info -debugger-tuning=gdb -v -coverage-notes-file /home/ubuntu/rocm/ubuntu/HIP/build/CMakeFiles/hip_hcc.dir/src/hip_memory.cpp.gcno -resource-dir /opt/rocm/hcc/lib/clang/8.0.0 -I/opt/rocm/hcc//bin/../include -I/opt/rocm/hcc//bin/../hcc/include -D hip_hcc_EXPORTS -I /home/ubuntu/rocm/ubuntu/HIP/include -D HIP_VERSION_MAJOR=1 -D HIP_VERSION_MINOR=5 -D HIP_VERSION_PATCH=19285 -I /opt/rocm/hcc//include -I /opt/rocm/include -D NDEBUG -internal-isystem /usr/lib/gcc/aarch64-linux-gnu/7.4.0/../../../../include/c++/7.4.0 -internal-isystem /usr/lib/gcc/aarch64-linux-gnu/7.4.0/../../../../include/aarch64-linux-gnu/c++/7.4.0 -internal-isystem /usr/lib/gcc/aarch64-linux-gnu/7.4.0/../../../../include/aarch64-linux-gnu/c++/7.4.0 -internal-isystem /usr/lib/gcc/aarch64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/backward -internal-isystem /usr/local/include -internal-isystem /opt/rocm/hcc/lib/clang/8.0.0/include -internal-externc-isystem /usr/include/aarch64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O3 -std=c++amp -fdeprecated-macro -fdebug-compilation-dir /home/ubuntu/rocm/ubuntu/HIP/build -ferror-limit 19 -fmessage-length 149 -fno-signed-char -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -famp -fhsa-ext -o CMakeFiles/hip_hcc.dir/src/hip_memory.cpp.o -x hc-host /home/ubuntu/rocm/ubuntu/HIP/src/hip_memory.cpp -fgpu-rdc -faddrsig
clang -cc1 version 8.0.0 based upon HCC 1.3.19301-d099b6b5-6ec3c61e09-d5938b6c383  default target aarch64-unknown-linux-gnu
ignoring nonexistent directory "/opt/rocm/hcc//bin/../hcc/include"
ignoring nonexistent directory "/include"
ignoring duplicate directory "/opt/rocm/hcc//bin/../include"
ignoring duplicate directory "/usr/lib/gcc/aarch64-linux-gnu/7.4.0/../../../../include/aarch64-linux-gnu/c++/7.4.0"
#include "..." search starts here:
#include <...> search starts here:
 /opt/rocm/hcc//bin/../include
 /home/ubuntu/rocm/ubuntu/HIP/include
 /opt/rocm/include
 /usr/lib/gcc/aarch64-linux-gnu/7.4.0/../../../../include/c++/7.4.0
 /usr/lib/gcc/aarch64-linux-gnu/7.4.0/../../../../include/aarch64-linux-gnu/c++/7.4.0
 /usr/lib/gcc/aarch64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/backward
 /usr/local/include
 /opt/rocm/hcc/lib/clang/8.0.0/include
 /usr/include/aarch64-linux-gnu
 /usr/include
End of search list.
fatal error: error in backend: lib/Target/AArch64/AArch64ISelLowering.cpp : Unsupported calling convention. CC=76
 "/opt/rocm/hcc/bin/clang-8" -cc1 -D__KALMAR_HC__=1 -D__HCC_HC__=1 -famp-is-device -fno-builtin -fno-common -O2 -triple amdgcn--amdhsa-hcc -aux-triple aarch64-unknown-linux-gnu -S -disable-free -disable-llvm-verifier -main-file-name hip_memory.cpp -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fmath-errno -no-integrated-as -mconstructor-aliases -fuse-init-array -v -coverage-notes-file /home/ubuntu/rocm/ubuntu/HIP/build/CMakeFiles/hip_hcc.dir/src/hip_memory.cpp.gcno -resource-dir /opt/rocm/hcc/lib/clang/8.0.0 -I/opt/rocm/hcc//bin/../include -I/opt/rocm/hcc//bin/../hcc/include -D hip_hcc_EXPORTS -I /home/ubuntu/rocm/ubuntu/HIP/include -D HIP_VERSION_MAJOR=1 -D HIP_VERSION_MINOR=5 -D HIP_VERSION_PATCH=19285 -I /opt/rocm/hcc//include -I /opt/rocm/include -D NDEBUG -internal-isystem /usr/lib/gcc/aarch64-linux-gnu/7.4.0/../../../../include/c++/7.4.0 -internal-isystem /usr/lib/gcc/aarch64-linux-gnu/7.4.0/../../../../include/aarch64-linux-gnu/c++/7.4.0 -internal-isystem /usr/lib/gcc/aarch64-linux-gnu/7.4.0/../../../../include/aarch64-linux-gnu/c++/7.4.0 -internal-isystem /usr/lib/gcc/aarch64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/backward -internal-isystem /usr/local/include -internal-isystem /opt/rocm/hcc/lib/clang/8.0.0/include -internal-externc-isystem /usr/include/aarch64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O3 -std=c++amp -fdeprecated-macro -fno-dwarf-directory-asm -fdebug-compilation-dir /home/ubuntu/rocm/ubuntu/HIP/build -ferror-limit 19 -fmessage-length 149 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -famp -fhsa-ext -o /tmp/hip_memory-4a1ee6.s -x hc-kernel /home/ubuntu/rocm/ubuntu/HIP/src/hip_memory.cpp -fgpu-rdc -emit-llvm-bc
clang -cc1 version 8.0.0 based upon HCC 1.3.19301-d099b6b5-6ec3c61e09-d5938b6c383  default target aarch64-unknown-linux-gnu
ignoring nonexistent directory "/opt/rocm/hcc//bin/../hcc/include"
ignoring nonexistent directory "/include"
ignoring duplicate directory "/opt/rocm/hcc//bin/../include"
ignoring duplicate directory "/usr/lib/gcc/aarch64-linux-gnu/7.4.0/../../../../include/aarch64-linux-gnu/c++/7.4.0"
ignoring duplicate directory "/usr/local/include"
ignoring duplicate directory "/opt/rocm/hcc/lib/clang/8.0.0/include"
ignoring duplicate directory "/usr/include"
#include "..." search starts here:
#include <...> search starts here:
 /opt/rocm/hcc//bin/../include
 /home/ubuntu/rocm/ubuntu/HIP/include
 /opt/rocm/include
 /usr/lib/gcc/aarch64-linux-gnu/7.4.0/../../../../include/c++/7.4.0
 /usr/lib/gcc/aarch64-linux-gnu/7.4.0/../../../../include/aarch64-linux-gnu/c++/7.4.0
 /usr/lib/gcc/aarch64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/backward
 /usr/local/include
 /opt/rocm/hcc/lib/clang/8.0.0/include
 /usr/include/aarch64-linux-gnu
 /usr/include
End of search list.
 "/opt/rocm/hcc//bin/hc-kernel-assemble" /tmp/hip_memory-4a1ee6.s CMakeFiles/hip_hcc.dir/src/hip_memory.cpp.o
clang-8: error: clang frontend command failed with exit code 70 (use -v to see invocation)
HCC clang version 8.0.0 (git@gitee.com:binutils/hcc-clang-upgrade.git 6ec3c61e09fbb60373eaf5a40021eb862363ba2c) (git@gitee.com:binutils/llvm.git d5938b6c383ee68cf93d4508e48836d6118517e2) (based on HCC 1.3.19301-d099b6b5-6ec3c61e09-d5938b6c383 )
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/hcc//bin
clang-8: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang-8: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-8: note: diagnostic msg: /tmp/hip_memory-765b59.cpp
clang-8: note: diagnostic msg: /tmp/hip_memory-b1300a.cpp
clang-8: note: diagnostic msg: /tmp/hip_memory-765b59.sh
clang-8: note: diagnostic msg:

********************
CMakeFiles/hip_hcc.dir/build.make:254: recipe for target 'CMakeFiles/hip_hcc.dir/src/hip_memory.cpp.o' failed
make[2]: *** [CMakeFiles/hip_hcc.dir/src/hip_memory.cpp.o] Error 70
make[2]: Leaving directory '/home/ubuntu/rocm/ubuntu/HIP/build'
CMakeFiles/Makefile2:135: recipe for target 'CMakeFiles/hip_hcc.dir/all' failed
make[1]: *** [CMakeFiles/hip_hcc.dir/all] Error 2
make[1]: Leaving directory '/home/ubuntu/rocm/ubuntu/HIP/build'
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
++ lastcmd=make

**Comment by ppanchad-amd** [comment]
@NothingButShadow Apologies for the lack of response. Can you please test with latest ROCm 6.1.0 (HIP 6.1)? If resolved, please close ticket. Thanks!
