### ISSUE TITLE
valgrind triggers an abort when launching kernels

### ISSUE THREAD

**Issue by malcolmroberts** [ROCm/HIP#1295]
When launching a hip program with valgrind, I get a process terminated with signal 6 (SIGABRT).

This is using hipcc to compile with 2.6 installed on Ubuntu 16.04 with a Vega 20 installed.

Minimal working example code:

// compile with /opt/rocm/hip/bin/hipcc -I/opt/rocm/hip/include sample.cc
#include <hip/hip_runtime.h>
__global__ void mykernel() {}
int main()
{
  hipLaunchKernelGGL(mykernel, dim3(1), dim3(1), 0, 0);
  return 0;
}

Output without valgrind is fine with return code 0.  When running with valgrind, I get the following:

valgrind ./a.out
==23847== Memcheck, a memory error detector
==23847== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==23847== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==23847== Command: ./a.out
==23847==
==23847== Warning: set address range perms: large range [0x59e8b000, 0x15a08c000) (noaccess)
terminate called after throwing an instance of 'std::exception'
  what():  std::exception
==23847==
==23847== Process terminating with default action of signal 6 (SIGABRT)
==23847==    at 0x6A41428: raise (raise.c:54)
==23847==    by 0x6A43029: abort (abort.c:89)
==23847==    by 0x650384C: __gnu_cxx::__verbose_terminate_handler() (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21)
==23847==    by 0x65016B5: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21)
==23847==    by 0x6501700: std::terminate() (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21)
==23847==    by 0x6501918: __cxa_throw (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21)
==23847==    by 0x5A8AA6E: hip_impl::hip_throw(std::exception const&) (in /opt/rocm/hip/lib/libhip_hcc.so)
==23847==    by 0x5A6C59B: hip_impl::program_state_impl::name[abi:cxx11](unsigned long) (in /opt/rocm/hip/lib/libhip_hcc.so)
==23847==    by 0x5A656B9: hip_impl::program_state_impl::kernel_descriptor(unsigned long, hsa_agent_s) (in /opt/rocm/hip/lib/libhip_hcc.so)
==23847==    by 0x5A655F8: hip_impl::program_state::kernel_descriptor(unsigned long, hsa_agent_s) (in /opt/rocm/hip/lib/libhip_hcc.so)
==23847==    by 0x4056B3: hip_impl::hipLaunchKernelGGLImpl(unsigned long, dim3 const&, dim3 const&, unsigned int, ihipStream_t*, void**) (in /home/marobert/repo/dotamd/eg/hip/vg/a.out)
==23847==    by 0x4050A9: void hipLaunchKernelGGL<, void (*)()>(void (*)(), dim3 const&, dim3 const&, unsigned int, ihipStream_t*) (in /home/marobert/repo/dotamd/eg/hip/vg/a.out)
==23847==
==23847== HEAP SUMMARY:
==23847==     in use at exit: 15,979,617 bytes in 204,677 blocks
==23847==   total heap usage: 673,485 allocs, 468,808 frees, 1,014,156,474 bytes allocated
==23847==
==23847== LEAK SUMMARY:
==23847==    definitely lost: 864 bytes in 14 blocks
==23847==    indirectly lost: 432 bytes in 9 blocks
==23847==      possibly lost: 6,404 bytes in 53 blocks
==23847==    still reachable: 15,971,917 bytes in 204,601 blocks
==23847==                       of which reachable via heuristic:
==23847==                         stdstring          : 71 bytes in 1 blocks
==23847==         suppressed: 0 bytes in 0 blocks
==23847== Rerun with --leak-check=full to see details of leaked memory
==23847==
==23847== For lists of detected and suppressed errors, rerun with: -s

**Comment by malcolmroberts** [comment]
I should mention that this is with valgrind-3.15.0, but using different versions doesn't seem to solve the problem.

**Comment by anilbommareddy** [comment]
Issue may be resolve with the commit 
https://github.com/ROCm-Developer-Tools/HIP/pull/1684/commits/72329e679134cfb8d4b162d4c4169a14f5f129d1

**Comment by ppanchad-amd** [comment]
@malcolmroberts Can you please test with latest ROCm 6.1.0 (HIP 6.1)? If resolved, please close ticket. Thanks!
