### ISSUE TITLE
Slow inital kernel launch

### ISSUE THREAD

**Issue by stipmonster** [ROCm/HIP#1304]
When launching the first kernel on a radeon vii card, there is a large penalty of around 300ms. The card is set to the compute profile. This is the case with all examples from the repo.

The output is from a modified events example.
```
Device name Vega 20
hipMemcpyHostToDevice time taken  =  4.891ms
kernel Execution time             = 340.598ms
kernel2 Execution time             =  0.326ms
kernel3 Execution time             =  0.337ms
hipMemcpyDeviceToHost time taken  =  3.208ms
```

```
HIP version  : 1.5.19255

== hipconfig
HIP_PATH     : /opt/rocm
HIP_PLATFORM : hcc
CPP_CONFIG   :  -D__HIP_PLATFORM_HCC__=   -I/opt/rocm/include -I/opt/rocm/hcc/include

== hcc
HSA_PATH     : /opt/rocm/hsa
HCC_HOME     : /opt/rocm/hcc
HCC clang version 9.0.0 (/data/jenkins_workspace/centos_pipeline_job/rocm-rel-2.6/rocm-2.6-22-20190704/centos/external/hcc-tot/clang fff0bd8ccc310cbfec5e3e1bf516b81412081a71) (/data/jenkins_workspace/centos_pipeline_job/rocm-rel-2.6/rocm-2.6-22-20190704/centos/external/hcc-tot/compiler a42c925d178d2a3cd6541769279b736c56b3f935) (based on HCC 1.3.19242-7496b9e1-fff0bd8ccc-a42c925d178 )
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/hcc/bin
LLVM (http://llvm.org/):
  LLVM version 9.0.0svn
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: skylake-avx512

  Registered Targets:
    amdgcn - AMD GCN GPUs
    r600   - AMD GPUs HD2XXX-HD6XXX
    x86    - 32-bit X86: Pentium-Pro and above
    x86-64 - 64-bit X86: EM64T and AMD64
HCC-cxxflags :  -hc -std=c++amp -I/opt/rocm/hcc/include -I/opt/rocm/includeHCC-ldflags  :  -hc -std=c++amp -L/opt/rocm/hcc/lib -Wl,--rpath=/opt/rocm/hcc/lib -ldl -lm -lpthread -lhc_am -Wl,--whole-archive -lmcwamp -Wl,--no-whole-archive
```

**Comment by scchan** [comment]
There was a recent change in the runtime to lazily initialize the GPU resources.  That includes the GPU queues, the loading of the GPU code (among other things) and that probably explains the overhead observed during the first kernel launch.  Could you try setting the env var HCC_LAZYINIT=0 and see that helps?

**Comment by stipmonster** [comment]
Running with HCC_LAZYINIT set to zero does not change the timings.

**Comment by jtjohnston** [comment]
Any progress?  I'm running into the same issue.  In the (somewhat distant) past I had this issue as well with nvidia GPUs.  The hack-fix was to run nvidia-smi in the background (so it would initialize the gpu/driver) and then to run the actual code.  I'm not sure if something similar can be done with AMD gpus (i.e. if there's an nvidia-smi equivalent).

**Comment by kiritigowda** [comment]
@jtjohnston to call rocm-smi in a loop use 
````
watch ./rocm-smi
````

**Comment by stipmonster** [comment]
> Any progress? I'm running into the same issue. In the (somewhat distant) past I had this issue as well with nvidia GPUs. The hack-fix was to run nvidia-smi in the background continuously (so it would initialize the gpu/driver) and then to run the actual code. I'm not sure if something similar can be done with AMD gpus; it looks like rocm-smi is the nvidia-smi equivalent, but I don't see how to call it on a loop. Also, in the past, with the nvidia gpus, even nvidia-smi was slow the first time it was called (hence the need for it to be running continuously).

Running smi in a loop also does not work. disabeling HCC_LAZYINIT does change some behavoir however this does not change the slow kernel launch. I have tried to see if calling some other hip functions does trigger the init, but that does not seem to be the case. 

@jtjohnston However i am suspecting that this is also linked to how event timers are implemented because compared to nvidea cards i am seeing a lot less stable and consistent results if there is load on the card.

**Comment by jtjohnston** [comment]
@kiritigowda the `watch ./rocm-smi` doesn't work because it doesn't keep the smi running.  When I had the issue with similar symptoms on Nvidia GPUs, it was basically that initializing the device/driver (apologize if terminology is mistaken, this is not an area of huge expertise of mine) took a lot of time, but after it was initialized everything was fine until the code that had initialized the GPU/driver terminated, after that, it would have to re-initialize.  But, `nvidia-smi` can run in a loop where the single command/process never exits (so it can initialize the device but not terminate).

@stipmonster My current suspicion, though I'm not sure how to determine whether or not this is the case, is that the build I did (using default make/cmake files, etc) did not target the AMD GPU I have (Radeon PRO WX 9100).  I also had poor performance (in the past) running on Nvidia Volta GPUs when the build scripts (for PyTorch) hadn't listed Volta as a target architecture (I couldn't pull pre-compiled PyTorch that time because it was on Power9 CPUs+Volta GPUs... i.e. not an X86 architecture).

**Comment by stipmonster** [comment]
> @kiritigowda the `watch ./rocm-smi` doesn't work because it doesn't keep the smi running. When I had the issue with similar symptoms on Nvidia GPUs, it was basically that initializing the device/driver (apologize if terminology is mistaken, this is not an area of huge expertise of mine) took a lot of time, but after it was initialized everything was fine until the code that had initialized the GPU/driver terminated, after that, it would have to re-initialize. But, `nvidia-smi` can run in a loop where the single command/process never exits (so it can initialize the device but not terminate).
> 
> @stipmonster My current suspicion, though I'm not sure how to determine whether or not this is the case, is that the build I did (using default make/cmake files, etc) did not target the AMD GPU I have (Radeon PRO WX 9100). I also had poor performance (in the past) running on Nvidia Volta GPUs when the build scripts (for PyTorch) hadn't listed Volta as a target architecture (I couldn't pull pre-compiled PyTorch that time because it was on Power9 CPUs+Volta GPUs... i.e. not an X86 architecture).

That was also my intial guess but i switched to a support card, and still had the issue, I now have followed the guide, https://github.com/ROCm-Developer-Tools/HIP/blob/master/INSTALL.md for the HIP-clang version instead of the AMD-HCC version and my problems where gone. I would recommend also trying the HIP-clang version to solve this issue. The best guide to how to do it is listed at https://github.com/RadeonOpenCompute/ROCm-Device-Libs

**Comment by jtjohnston** [comment]
@stipmonster Excellent, thank you.  I will give this a try.

**Comment by stipmonster** [comment]
@scchan this issue is still there with rocm/hip 3.0, any updates?
