### ISSUE TITLE
HIPCC clang-hip segfault during compilation

### ISSUE THREAD

**Issue by davidrohr** [ROCm/HIP#1335]
The attached testcase causes a segmentation fault in clang when using hip-clang built as described in #1196 (based on ROCm 2.7).
[testcase.tar.gz](https://github.com/ROCm-Developer-Tools/HIP/files/3507044/testcase.tar.gz)
The testcase compiles correctly when I use hip based on hcc instead of hip-clang.

(I extracted the part of our application that crashes and preprocessed everything into a single .hip.cpp file)

Not sure if HIP is the right place to open the issue. If you think the better place is https://github.com/RadeonOpenCompute/clang or upstream clang, please let me know and I will open a bug report there. But since I only have this error when using hipcc, I think HIP is the best case to start with the issue.

**Comment by davidrohr** [comment]
Below is a smaller test case, that reproduces the same problem. I am afraid it is difficult to reduce the test case further. Whenever I try to remove more code, the failure disappears.
[preprocessed.hip.cpp.tar.gz](https://github.com/ROCm-Developer-Tools/HIP/files/3570071/preprocessed.hip.cpp.tar.gz)
Please run with `hipcc --amdgpu-target=gfx906 -std=c++17 -o test.o preprocessed.hip.cpp`

**Comment by ppanchad-amd** [comment]
@davidrohr Is this ticket still relevant? If not, please close. Thanks!

**Comment by davidrohr** [comment]
Sorry, don't have time to follow up and retest these old tickets, closing.
