### ISSUE TITLE
Symbol ERROR in hip-clang

### ISSUE THREAD

**Issue by louishp** [ROCm/HIP#1386]
There is a really big problem when we use symbol(hipMemcpyToSymbol and hipMemcpyToSymbol) in program compiled by hip-clang. hipMemcpyToSymbol and hipMemcpyFromSymbol call read_agent_global_from_process() to get the address of symbol through hipGetSymbolAddress. In HCC the function can return the correct address of symbol.  But In hip-clang the function can't find the address and return NULL. 
The implementation of read_agent_global_from_process() is the reason for this problem. There is a std::call_once funtion call inside of read_agent_global_from_process(). 

The process of read_agent_global_from_process():
1. lamda function  call get_executables() to get all executable of agent 
2. lamda function  scan all executable of agent
3. for each executable, lamda function call read_agent_globals() get all symbol(kernel descriptor and global variable name) and store in globals_from_process
4. read_agent_global_from_process call read_global_description to find the symbol from globals_from_process.

But this process is different in hip-clang, module executable have already created by function __hipRegisterFatBinary on the .init_array stage. When we call get_executables() in read_agent_global_from_process() the problem arises.

First, program compiled by hip-clang can't call  get_executables(). There is a std::call_once function in get_executables() to initialize the executables through get_code_object_blobs().  But this funtion only work for the program has '.kernel' segment.

Secondly, __hipRegisterFatBinary will create module executable for each agent. That means all symbol in executable has already registered to agent on hsa.  If we only fix the segment problem in get_code_object_blobs(), get_executables() will create all symbol(global variable) twice. The symbol get from hipGetSymbolAddress and kernel execution will be different.

In our solution, we create several global variables in hip_clang.cpp to save the modules create by  __hipRegisterFatBinary.  g_modules is the modules return by __hipRegisterFatBinary and g_moduledevices is label to mark the order of the agent. read_agent_global_from_process() use clanginit to decide using g_modules or get_executables() to initialize the globals_from_process.

extern std::vector<hipModule_t>* g_modules;
extern std::vector<hsa_agent_t>* g_moduledevices;
extern bool clanginit;

Currently, __hipRegisterVar in hip_clang.cpp is not implemented. I think the best way is to redesign hipGetSymbolAddress function and implement __hipRegisterVar.

**Comment by zhaozhangjian** [comment]
Hi louishp,
I found the same issue as you mentioned above. The hipcc built with clang cannot handle hipGetSymbolAddress() as expected, but hipcc built with hcc makes it! But it seems that in rocm of 2.6 version, hipcc built with clang can also handle hipGetSymbolAddress() well, which version of rocm were you using when you are posting above?
