### ISSUE TITLE
HIP compiler bug leading to miscompilation and incorrect results

### ISSUE THREAD

**Issue by davidrohr** [ROCm/HIP#1401]
The attached test case triggers a HIP compiler bug.
[testcase.tar.gz](https://github.com/ROCm-Developer-Tools/HIP/files/3591275/testcase.tar.gz)

The problem appears in a kernel in the file `SliceTracker/GPUTPCNeighboursFinder.cxx`.
I have added some more information in a comment in this file.

The result produced by the application when compiled with HIP is not correct.
If I run the same algorithm on a CPU (or on an NVIDIA GPU with CUDA), I get the correct result.

To reproduce the issue, please unpack the tarball and run `runttest.sh`. It will:
- Compile the application
- Run the code twice, once on CPU, once on the AMD GPU with hit
- Compare the output files (CPU.out and GPU.out)

I am using AMD ROCm 2.7 and HIP with HCC as compiler.

**Comment by ppanchad-amd** [comment]
@davidrohr Apologies for the lack of response. Can you please test with latest ROCm 6.1.0 (HIP 6.1)? If resolved, please close ticket. Thanks!

**Comment by davidrohr** [comment]
Sorry, don't have time to follow up and retest these old tickets, closing.
