### ISSUE TITLE
The Linker problem.

### ISSUE THREAD

**Issue by ginsongsong** [ROCm/HIP#141]
Hi all,

I have a question about MI25(gfx900) linker problem.

I'm trying to build the benchmark as bellow URL, but I found the error msg from Linker.

```
URL:
https://github.com/ekondis/mixbench

Error Msg:
error: <unknown>:0:0: in function _ZZ8runbenchILi0EEvPdlEN67HIP_kernel_functor_name_begin_unnamed_HIP_kernel_functor_name_end_319__cxxamp_trampolineE_1Dv2_DhPS2_ void (<2 x half>, <2 x half>*): unsupported call to function __hip_hc_ir_hfma2_int

error: <unknown>:0:0: in function _ZZ8runbenchILi0EEvPdlEN67HIP_kernel_functor_name_begin_unnamed_HIP_kernel_functor_name_end_319__cxxamp_trampolineE_1Dv2_DhPS2_ void (<2 x half>, <2 x half>*): unsupported call to function __hip_hc_ir_hfma2_int

Generating AMD GCN kernel failed in llc for target: gfx900
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
Died at /opt/rocm/hip/bin/hipcc line 497.

```

 I changed my system environment setting from bashrc, but I found another problem after excuting  the program.

BASHRC:

#export HCC_AMDGPU_TARGET=gfx900
export HCC_AMDGPU_TARGET=gfx803,gfx900

```
ERROR Msg:

Backtrace:
0x000000000040d1e1:	Kalmar::CLAMP::DetermineAndGetProgram(Kalmar::KalmarQueue*, unsigned long*, void**) + 0x571
0x000000000040d4f0:	Kalmar::KalmarBootstrap::KalmarBootstrap() + 0x120
0x000000000040d3a9:	__hcc_shared_library_init + 0x29
0x000000000047fa2d:	__libc_csu_init + 0x4d
0x00007f1c3cda07bf:	__libc_start_main + 0x7f
0x0000000000474359:	_start + 0x29

### HCC RUNTIME ERROR: Fail to find compatible kernel at file:mcwamp.cpp line:346

```

Finally, I found the hip  data layouts doesn't support the gfx900 when trying to compile half precision 
 hip example.

`WARNING: Linking two modules of different data layouts: '/tmp/tmp.8lkMfvhzWq/mix_kernels_hip-3b933c.kernel.bc' is '' whereas 'llvm-link' is 'e-p:64:64-p1:64:64-p2:64:64-p3:32:32-p4:32:32-p5:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-A5'`

-----------------------------------------------------------------------------------------------------
My system configuration:
Operating system: Ubuntu 16.04.2 LTS with 4.9.0-kfd-compute-rocm-rel-1.6-115
Compiler: HCC clang version 6.0.0  (based on HCC 1.0.17312-23b85c3-1d969cc-9812862 )
HIP version: 1.2.17311

**Comment by adityaatluri** [comment]
@scchan @whchung (regarding fail to find compatible kernel).

**Comment by ginsongsong** [comment]
Hi @adityaatluri ,
Is there any update on fp16 problem?

**Comment by Dekken** [comment]
I'm running into this with this [example](https://github.com/ROCmSoftwarePlatform/rocBLAS/wiki/Example-C--code-calling-rocBLAS-routine-with-hipcc-and-or-gnu-compiler) with an R 390

**Comment by ekondis** [comment]
On the latest ROCm release (1.7.60) is seems to be able to be compiled for Vega. However, after inspecting the produced ISA assembly it does not seem to take advantage of packed fp16 operations regarding the half precision tests.

**Comment by nartmada** [comment]
@ginsongsong, apologies for the lack of response.  Can you please check latest ROCm 6.0.2 (HIP 6.0.32831) to see if your query has been addressed? Thanks.

**Comment by nartmada** [comment]
Closing the ticket as it is stale and no response from @ginsongsong.  Please re-open if you still encounter this issue.  Thanks.
