### ISSUE TITLE
[HIP] List of unrecognised CUDA identifiers

### ISSUE THREAD

**Issue by cpviolator** [ROCm/HIP#1443]
I'm undertaking a HIP port of the QUDA library. The strategy is to remove all CUDA specific data types and replace them with agnostic QUDA types, which will be converted as required in a back end file.

In the meantime, I ran the HIPify tool on summit on the QUDA source code, and found some unrecognised CUDA identifiers: https://github.com/cpviolator/QUDA-hip/wiki/List-of-unsupported-CUDA-identifiers-in-HIP

May I ask if there any plans to include these in the future?

**Comment by emankov** [comment]
1. `cudaMallocManaged` is supported by HIP and HIPIFY.
2. Could you point out where `cublasgetrfBatched` and `cublasgetriBatched` are declared? I haven't found them in CUDA Toolkits.
3. Please open a ticket, maybe tickets with the prefix [HIP] for the rest of CUDA identifiers to support in HIP.

Thank you.

**Comment by cpviolator** [comment]
@emankov 

We use the `cublasCgetrfBatched` and `cublasCgetriBatched` here: https://github.com/lattice/quda/blob/develop/lib/blas_cublas.cu#L92 and here https://github.com/lattice/quda/blob/develop/lib/blas_cublas.cu#L77

**Comment by ppanchad-amd** [comment]
@cpviolator Apologies for the lack of response. Can you please check with latest ROCm 6.1.0 (HIP 6.1)? Thanks!

**Comment by ppanchad-amd** [comment]
@cpviolator Closing issue. Please re-open if it's still an issue with latest ROCm 6.1.1 Thanks
