### ISSUE TITLE
hipMemPrefetchAsync is missing. 

### ISSUE THREAD

**Issue by Kaveh01** [ROCm/HIP#1453]
hipMemPrefetchAsync is missing. I can live without that but it is nice to have the feature.

**Comment by emankov** [comment]
Do you need `cuMemPrefetchAsync` or `cudaMemPrefetchAsync`?

**Comment by Kaveh01** [comment]
@emankov 
I need `cudaMemPrefetchAsync`.

**Comment by ppanchad-amd** [comment]
@emankov Do you know if cudaMemPrefetchAsync is available with ROCm 6.1.0 (HIP 6.1)? Thanks!

**Comment by Djip007** [comment]
https://rocm.docs.amd.com/projects/HIP/en/docs-6.1.0/doxygen/html/group___memory_m.html#ga08ca029eec15591f680c7b19b0fb1d1a
may be...
