### ISSUE TITLE
How to print inside a kernel?

### ISSUE THREAD

**Issue by Rombur** [ROCm/HIP#1493]
The `printf` function has been removed https://github.com/RadeonOpenCompute/hcc/pull/1199 Is there another function that we can use? This is pretty useful to debug kernels.

**Comment by dmcdougall** [comment]
@Rombur Just to let you know, the ROCm folks are aware of the problem.

**Comment by masterleinad** [comment]
This works again.

**Comment by nartmada** [comment]
Closing the ticket as the issue has been fixed.
