### ISSUE TITLE
[HIP] Ongoing list of Unrecognised refs in QUDA-HIP port

### ISSUE THREAD

**Issue by cpviolator** [ROCm/HIP#1494]
I am attempting to port the QUDA library to HIP. I shall document here and unconverted references as I find them. I'm using cuda 9.2.148 and hip/1.5-cuda9 on SUMMIT.

**Comment by cpviolator** [comment]
```

**Comment by cpviolator** [comment]
```
[HIPIFY] info: UNCONVERTED refs by names:
  cuGetErrorString: 1
```

**Comment by ppanchad-amd** [comment]
@cpviolator Apologies for the lack of response. Can you please test with latest ROCm 6.1.0 (HIP 6.1)? If resolved, please close ticket. Thanks!

**Comment by ppanchad-amd** [comment]
@cpviolator Closing issue. Please re-open if issue still occurs with ROCm 6.1.1 Thanks!
