### ISSUE TITLE
Compilation failure with ROCm >= 2.8

### ISSUE THREAD

**Issue by davidrohr** [ROCm/HIP#1532]
The attached test case compiled with HIP from ROCm <= 2.7, but fails with 2.8 and 2.9.
[testcase.tar.gz](https://github.com/ROCm-Developer-Tools/HIP/files/3722029/testcase.tar.gz)

Compile command: `hipcc --amdgpu-target=gfx906 -std=c++17 -o test test2.hip.cpp -Wno-invalid-constexpr`

The error I receive is:
```
error: <unknown>:0:0: in function _ZSt16__introsort_loopIPjlN9__gnu_cxx5__ops15_Iter_comp_iterIN2o23gpu24GPUTPCCompressionKernels32GPUTPCCompressionKernels_CompareILi3EEEEEEvT_SA_T0_T1_ void (i32*, i32*, i64, %"struct.__gnu_cxx::__ops::_Iter_comp_iter" addrspace(5)*): The function cannot be inlined.

Generating AMD GCN kernel failed in HCC-specific opt passes for target: gfx906
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by nartmada** [comment]
Hi @davidrohr, apologies for the lack of response.  Can you please try latest ROCm 6.0.2 (HIP 6.0.32831) to see if your issue still exists?  If resolved, please close the ticket. Thanks.

**Comment by davidrohr** [comment]
this is 5 years old, I don't have a setup right now to check it.
If you want, you can still check the attached test case, anyhow, I am just closing it.
