### ISSUE TITLE
hipMemcpy2D disallows spitch<width

### ISSUE THREAD

**Issue by ekuznetsov139** [ROCm/HIP#1533]
In here
https://github.com/ROCm-Developer-Tools/HIP/blob/master/src/hip_memory.cpp#L1692

hipMemcpy2D returns an error if dpitch < width or spitch < width.

It is logical to prohibit dpitch < width (since, in that case, the behavior is undefined), but there's no good reason to restrict spitch < width. In particular, this forecloses a potentially useful case spitch=0 (in which case, the function would copy the first 'width' bytes from the pointer 'src' 'height' times into the destination buffer.)

As far as I can tell, the function does not even need to be changed in any way to allow this usage - removing the condition check would suffice.

**Comment by gargrahul** [comment]
@ekuznetsov139 we are following CUDA API's behavior. For more details please check- https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY.html#group__CUDART__MEMORY_1g3a58270f6775efe56c65ac47843e7cee

It says -"width must not exceed either dpitch or spitch".

You should set spitch = width , to copy width*height bytes into destination buffer.

**Comment by ekuznetsov139** [comment]
I doubt that anyone actually relies on having hipMemcpy2D fail with spitch<weight (all this change would do is let it work in more situations). But I suppose blind compliance with CUDA API is a valid reason.

I want to repeat the source buffer N times (broadcast operation) without having to fire up a kernel or an API call N times. CUDA has this functionality in an optional package (NCCL method ncclBroadcast).

**Comment by mangupta** [comment]
We have a NCCL port. See https://github.com/ROCmSoftwarePlatform/rccl. Also the port supports ncclBroadcast. See https://github.com/ROCmSoftwarePlatform/rccl/blob/9af66195dba5cd8950ebfbcde3ce5d640e6b29b6/src/nccl.h.in#L173-L174.

**Comment by ekuznetsov139** [comment]
Actually, I was wrong. ncclBroadcast is unrelated to what I need.

**Comment by nartmada** [comment]
Hi @ekuznetsov139, I am cleaning up stale tickets.  Has your issue been addressed?  Thanks.

**Comment by nartmada** [comment]
Closing the ticket as the issue has been fixed.
