### ISSUE TITLE
Internal Compiler error with hip-clang (all ROCm versions) and hcc (ROCm 2.8 / 2.9)

### ISSUE THREAD

**Issue by davidrohr** [ROCm/HIP#1538]
This report supersedes #1532  RadeonOpenCompute/hcc#1274 and #1335 
This is a full testcase of our application, that triggeres all the internal compiler errors in the bug reports above, + some more.

[fullTestCase.tar.gz](https://github.com/ROCm-Developer-Tools/HIP/files/3726041/fullTestCase.tar.gz)

Please unpack the attached test case in a directory and compile with the following command to trigger the ICE:
```
hipcc -DGPUCA_GPULIBRARY=HIP -DGPUCA_NO_FMT -DGPUCA_NO_VC -DGPUCA_STANDALONE -DHAVE_O2HEADERS -DHIP_ENABLED -DNDEBUG -O3 -march=native -ggdb -minline-all-stringops -ftracer -funroll-loops -fprefetch-loop-arrays -ffast-math -fno-stack-protector -Wno-error -Wall -Wextra -Wshadow -Wno-unused-function -Wno-unused-parameter -Wno-unused-local-typedefs -Wno-unknown-pragmas -Wno-write-strings --amdgpu-target=gfx906 -fPIC   -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -Wno-invalid-constexpr -Wno-ignored-optimization-argument -Wno-unused-private-field -std=c++17 -I . -IBase -IBase/opencl-common -ICommon -IDataCompression -IdEdx -Idisplay -IGlobal -IHLTHeaders -IITS -IMerger -Iqa -ISliceTracker -ITPCConvert -ITPCFastTransformation -ITRDTracking -Igpucf -rdynamic -shared -Wl,-soname,libGPUTrackingHIP.so -o libGPUTrackingHIP.so Base/hip/GPUReconstructionHIP.hip.cxx
```

**Comment by jsjodin** [comment]
I triggered this error as well (function cannot be inlined). A temporary workaround that allowed my code to compile was to move the function outside any namespaces.

**Comment by nartmada** [comment]
Hi @davidrohr, sorry for the lack of response.  Just checking to see if this issue still exists with latest ROCm 6.0.2 (HIP 6.0.32831).

**Comment by davidrohr** [comment]
this is 5 years old, I don't have a setup right now to check it.
If you want, you can still check the attached test case, anyhow, I am just closing it.
