### ISSUE TITLE
HIP miscompilation

### ISSUE THREAD

**Issue by davidrohr** [ROCm/HIP#1556]
HIP miscompiles the attached test case. The issue appears with ROCm 2.7 (Right now, I cannot use ROCm 2.8/2.9 due to #1536, so I do not know, if they are also affected.)

I am compiling the code with `hipcc -O0 -g --amdgpu-target=gfx906 -o test testcase.hip.cpp`.
Please run the application with `test cpu` and `test gpu` to execute the computation on CPU / GPU respectively. For me, it fails on the GPU with:
```
qon@qon ~/standalone-cmake $ hipcc -O0 -g --amdgpu-target=gfx906 -o test testcase.hip.cpp 
clang-9: warning: -O0 is ignored in GPU compilation path [-Winvalid-command-line-argument]
qon@qon ~/standalone-cmake $ ./test gpu
Sizes 1920 2656 220 24
Memory access fault by GPU node-1 (Agent handle: 0x590620) on address 0x24dc00002000. Reason: Unknown.
Aborted
```

Some additional information:
I could already debug that the problem is apparently in the function `GPUTPCGMTrackParam::FollowCircle` (line 3137).
The code in this function makes the compiler miscompile. If I just make the function empty, or return directly at the beginning of the function, the compilation becomes correct.
I want to add that with the test case I uploaded the code of the function is not executed at all. `Merger->Param().rec.DisableRefitAttachment = 255`, so the check at the beginning of the function makes it return immediately. So even though the code is not executed, it makes the program crash.
The attached tarball contains a second source file `testcase_modified.hip.cpp` which illustrates the behavior.
I.e., if you compile testcase_modified instead of testcase:
- you can run on the CPU and see that the funtion always returns immediately.
- you can compile on the GPU, and the program will not crash, but produce more or less the same output as on the CPU. There are small differences in the floating point results, not yet sure where this comes from.

**Comment by davidrohr** [comment]
[testcase.tar.gz](https://github.com/ROCm-Developer-Tools/HIP/files/3741585/testcase.tar.gz)

**Comment by nartmada** [comment]
Hi @davidrohr, apologies for the lack of response.  Please try latest ROCm 6.0.2 (HIP 6.0.32831) to see if your issue still exists? If resolved, please close the ticket. Thanks.

**Comment by davidrohr** [comment]
this is 5 years old, I don't have a setup right now to check it.
If you want, you can still check the attached test case, anyhow, I am just closing it.

**Comment by nartmada** [comment]
Thanks @davidrohr.  I will ask the internal team to check your test case.
