### ISSUE TITLE
hcc equivalent of nvcc's "--device-link" 

### ISSUE THREAD

**Issue by atabish** [ROCm/HIP#1606]
Hi,
I want to compile and run cpu code that contains no hip/cuda code (but links against a library that does) with g++. I can do it if HIP_PLATFORM is nvcc as follows:
hipcc   -rdc=true -c -o temp.o somefile.cu
hipcc -dlink -o somefile.o temp.o -lcudart
ar cru libgpu.a  somefile.o temp.o
ranlib libgpu.a
g++ main.cpp -L. -lgpu -o main -L/usr/local/cuda/lib64 -lcudart

But I can not do the same steps if HIP_PLATFORM is hcc. I am assuming it has to do with "-dlink" flag not being implemented in hcc. Please let me know if there is a way to repeat the above procedure for HIP_PLATFORM=hcc
thanks

**Comment by gargrahul** [comment]
@atabish Could you try https://github.com/ROCm-Developer-Tools/HIP/blob/master/tests/src/g%2B%2B/hipMalloc.cpp  or tests from https://github.com/ROCm-Developer-Tools/HIP/tree/master/tests/src/gcc ?

**Comment by atabish** [comment]
@SarbojitAMD So we decided to just use shared library following the steps from #1055 and it all works well. My question now is, how to translate the first two steps to CMake:
1. hipcc -fPIC $(INC) -c gpu.cpp // will generate gpu.o object file
2. hipcc -shared -o libgpu.so gpu.o $(LIB) -i:libhip_hcc.so // will generate shared library name libgpu.so

If I just do:
```
hip_add_library(test_gpu SHARED ${gpu_src} HIPCC_OPTIONS ${MY_HIPCC_OPTIONS} HCC_OPTIONS ${MY_HCC_OPTIONS} NVCC_OPTIONS ${MY_NVCC_OPTIONS})
```
It seems like it will compile with hipcc but link with g++ and the code crush.

**Comment by atabish** [comment]
@SarbojitAMD The shared library approach that you suggested in #1055 works well. My question now is, how to translate the first two steps to CMake:
1. hipcc -fPIC $(INC) -c gpu.cpp // will generate gpu.o object file
2. hipcc -shared -o libgpu.so gpu.o $(LIB) -i:libhip_hcc.so // will generate shared library name libgpu.so

If I just do:
```
hip_add_library(test_gpu SHARED ${gpu_src} HIPCC_OPTIONS ${MY_HIPCC_OPTIONS} HCC_OPTIONS ${MY_HCC_OPTIONS} NVCC_OPTIONS ${MY_NVCC_OPTIONS})
```
It seems like it compiles with hipcc but links with g++. The executable generated then crushes. I am looking for a generic CMake solution that I can build library which is runable on both AMD and NVidia cards.

Thanks for your help so far.

**Comment by Datta2324** [comment]
Hi , I have ported CUDA code into HIP

**Comment by Datta2324** [comment]
Hi, I am new to this 
I have ported CUDA code into HIP to run vector addition on Multiple GPUs using MPI  and in makefile in CUDA the is a linker 
-lcudart . I am getting error with that in HIP . I have tried with hiprtc but it did not work,  Can anyone help me

**Comment by fwyzard** [comment]
> Now my goal is to pack hipMalloc.cpp into a library (lets say libgpu.a) and use that with my test.cpp. Something as follows:
> 
> ```
> 1. /opt/rocm/bin/hipcc -fPIC -c -o temp.o hipMalloc.cpp
> 2. ar cru libgpu.a temp.o 
> 3. ranlib libgpu.a
> 4. g++ -D__HIP_PLATFORM_HCC__ -I/opt/rocm/hip/include -I/opt/rocm/include test.cpp -Wl,--rpath=/opt/rocm/hip/lib /opt/rocm/hip/lib/libhip_hcc.so -L. -lgpu  -o test -std=c++11
> ```

I know this is pretty old, but since I stumbled upon it while looking for a similar solution, here is what seems to work for me (using ROCm 5.4):

```
1. /opt/rocm/bin/hipcc -fPIC -fgpu-rdc -c -o temp.o hipMalloc.cpp
2. /opt/rocm/bin/hipcc -fPIC -fgpu-rdc --hip-link --emit-static-lib -o libgpu.a temp.o 
3. # not needed
4. g++ -D__HIP_PLATFORM_HCC__ -I/opt/rocm/include test.cpp -Wl,--rpath=/opt/rocm/lib -L/opt/rocm/lib -lamdhip64 -L. -lgpu -o test -std=c++11
```

**Comment by ppanchad-amd** [comment]
@atabish Apologies for the lack of response. Can you please test with latest ROCm 6.1.0 (HIP 6.1)? If resolved, please close ticket. Thanks!
