### ISSUE TITLE
Compile error when using c++17

### ISSUE THREAD

**Issue by pfultz2** [ROCm/HIP#1621]
I get this compiler error when enabling c++17:

```
/home/scxiao/Workplace/projects/AMDMIGraphX/deps_rocblas2.7/include/hip/hcc_detail/helpers.hpp:101:48: error: no member named 'invoke_result' in namespace 'std'
struct is_callable_impl<F(Ts...), void_t_<std::invoke_result<F(Ts...)> > > : std::true_type {};
                                          ~~~~~^
/home/scxiao/Workplace/projects/AMDMIGraphX/deps_rocblas2.7/include/hip/hcc_detail/helpers.hpp:101:64: error: 'Ts' does not refer to a value
struct is_callable_impl<F(Ts...), void_t_<std::invoke_result<F(Ts...)> > > : std::true_type {};
```

This is because the header assumes that `std::invoke_result` is available when `__cplusplus` is greater than `201402L` which is not the case. This only means the compiler has enabled c++17 mode, it doesn't mean the c++ runtime has c++17. However, this header has other problems as well.

Doing `std::invoke_result<F(Ts...)>` is completely wrong as well(as shown [here](https://en.cppreference.com/w/cpp/types/result_of)). It is supposed to called as `std::invoke_result<F, Ts...>`. And furthermore in this context it would be better to use `std::is_invocable` instead of doing the `void_t` dance.

Also, the `is_callable` trait should not de defined as `is_callable<F(Ts...)>` as this will lead to bugs when passing arrays or abstract type or distinguishing between top-level cv-qualifiers.

**Comment by djygithub** [comment]
I was having the same issue with a hoomd-blue build and resolved it as described here: [https://gist.github.com/jlblancoc/99521194aba975286c80f93e47966dc5](https://gist.github.com/jlblancoc/99521194aba975286c80f93e47966dc5) 
~~~
sudo apt-get install -y software-properties-common
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt update
sudo apt install g++-7 -y
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 \
                         --slave /usr/bin/g++ g++ /usr/bin/g++-7 
sudo update-alternatives --config gcc
~~~

**Comment by gargrahul** [comment]
Please try with https://github.com/ROCm-Developer-Tools/HIP/pull/1631

**Comment by nartmada** [comment]
Hi @pfultz2, just checking if your issue has been fixed.  I want to close the ticket if the reported issue has been fixed.  Thanks.

**Comment by nartmada** [comment]
Closing the ticket as it is stale.  @pfultz2, please re-open if this issue still exists with latest ROCm 6.0.2 (HIP 6.0.32831).
