### ISSUE TITLE
[HIP] hipDeviceSetLimit not supported in ROCm

### ISSUE THREAD

**Issue by hpcresearch-ht** [ROCm/HIP#1632]
hipDeviceSetLimit is supported according to the Documentation but it is not defined in the /opt/rocm/bin/include 
I have hipified my application and cudaDeviceSetLimit did not get converted

**Comment by emankov** [comment]
Thanks, it has not defined yet, but hipified.
@mangupta,  @gargrahul, Let's support `hipDeviceSetLimit` as long as `hipDeviceGetLimit`

**Comment by hpcresearch-ht** [comment]
@emankov sorry to bother you is there any update regarding the API call hipDeviceSetLimit

**Comment by nartmada** [comment]
@hpcresearch-ht, sorry for the lack of response.  Please try latest ROCm 6.0.2 (HIP 6.0.32831) to see if your issue still exists? If resolved, please close the ticket. Thanks.

**Comment by nartmada** [comment]
Closing the ticket as it is stale. Please re-open if you still see the issue with latest ROCm 6.0.2 (HIP 6.0.32831).
