### ISSUE TITLE
Initialize values of array in a struct

### ISSUE THREAD

**Issue by zjin-lcf** [ROCm/HIP#1639]
```
struct Box {
  int ranges[6];
#ifdef __HIPCC__
__host__ __device__ __inline__
#endif
  int* operator[](int xyz) { return &ranges[xyz*2]; }
#ifdef __HIPCC__
__host__ __device__ __inline__
#endif
  const int* operator[](int xyz) const { return &ranges[xyz*2]; }
};


 Box global_box = { 0, params.nx, 0, params.ny, 0, params.nz };
```

The compiler generates the following error for the initialization of the struct shown above. Is this expected ?

error: no matching constructor for initialization of 'Box'
  Box global_box = { 0, params.nx, 0, params.ny, 0, params.nz };
      ^            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../utils/Box.hpp:43:8: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 6 were provided
struct Box {
       ^
../utils/Box.hpp:43:8: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 6 were provided
../utils/Box.hpp:43:8: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 6 were provided

**Comment by nartmada** [comment]
Hi @zjin-lcf, apologies for the lack of response.  Please try latest ROCm 6.0.2 (HIP 6.0.32831) to see if your issue still exists? If resolved, please close the ticket. Thanks.
