### ISSUE TITLE
atomicAdd(float *, float) not linking

### ISSUE THREAD

**Issue by jglaser** [ROCm/HIP#1689]
in current HIP master, atomicAdd for float arguments doesn't work.

I get hipcc linker errors like

```
error: <unknown>:0:0: in function _Z27gpu_assign_particles_kernel15HIP_vector_typeIjLj3EES0_jPKjPKS_IdLj4EEPKdPS_IfLj2EEdij6BoxDimS7_ void (%struct.HIP_vector_type.70, %struct.HIP_vector_type.70, i32, i32*, %struct.HIP_vector_type*, double*, %struct.HIP_vector_type.1025*, double, i32, i32, %struct.BoxDim, double*): invalid addrspacecast
```

on gfx-906

**Comment by jglaser** [comment]
likely due to changes in d597e7ca2

**Comment by SarbojitAMD** [comment]
@jglaser,
Can you please share the code which is failing for you? I tried a simple kernel using local float array and tried to using atomicAdd(float*, float) but I did not see any link error.

Kernel that I could build successfully 
__global__ void myKernel(float* f)
{
    atomicAdd(f, 1.2);
}

**Comment by nartmada** [comment]
Hi @jglaser, sorry for the lack of response.  Please try latest ROCm 6.0.2 (HIP 6.0.32831) to see if your issue has been resolved? If resolved, please close the ticket. Thanks.

**Comment by nartmada** [comment]
Closing the ticket as it is stale.  Please re-open if you still see the issue with latest ROCm 6.0.2 (HIP 6.0.32831).
