### ISSUE TITLE
hipDeviceProp_t should have concurrentManagedAccess

### ISSUE THREAD

**Issue by jglaser** [ROCm/HIP#1696]
to match the corresponding CUDA field, and set it to something sensible (==0) for AMD GPUs

**Comment by nartmada** [comment]
Hi @jglaser, sorry for the lack of response.  Please try latest ROCm 6.0.2 (HIP 6.0.32831) to see if you still need this ticket to be opened.  Thanks.

**Comment by nartmada** [comment]
Closing the ticket as it is stale.
