### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [ROCm/HIP#170]
[An extra null pointer check is not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like in [the destructor for the class “ihipCtxCriticalBase_t”](https://github.com/ROCm-Developer-Tools/HIP/blob/f34b89b33f2f532bf964eb7f34f2fe86706d3fc6/src/hip_hcc_internal.h#L718 "Update candidate: Destructor for ihipCtxCriticalBase_t").

**Comment by nartmada** [comment]
@elfring, apologies for the lack of response.  Can you please check latest ROCm 6.0.2 (HIP 6.0.32831) to see if your query has been addressed?  Thanks.

**Comment by elfring** [comment]
>… Can you please check latest ROCm …? …

:thought_balloon: I would like to know in which directory the corresponding source files (which might eventually still include a class like “ihipCtxCriticalBase_t”) are currently stored.

**Comment by iassiour** [comment]
Hi @elfring this code was part of hip_hcc_internal.h but this has now been removed from HIP codebase.
Closing the issue.
