### ISSUE TITLE
[Question]-"CMakeLists.txt" to compile and link in HIP Environment

### ISSUE THREAD

**Issue by anilbommareddy** [ROCm/HIP#1705]
Is any reference link or document to understand on "CMakeLists.txt" to compile and link in HIP Environment

Example1:
compile & link: hipcc
hipcc -c example.cpp.cpp -o main.o [compile]
hipcc main.o -o Main [link]

Example 2:

compile(hipcc) and link(g++):
hipcc -c example.cpp -o main.o [compile]
g++ -L/opt/rocm/lib -lhip_hcc main.o -o Main [link]

In above examples , compile and link done through command lines. it is need write in CMakeLists.txt

**Comment by gargrahul** [comment]
Could you check https://github.com/ROCm-Developer-Tools/HIP/tree/master/samples/2_Cookbook/12_cmake_hip_add_executable ?

**Comment by nartmada** [comment]
Hi @anilbommareddy, sorry for the lack of response.  If your question has been answered by gargrahul, please close the ticket.  Thanks.

**Comment by nartmada** [comment]
Closing the ticket as it is stale.
