### ISSUE TITLE
hcc is deprecated in favor of hip, but hip depends on hcc

### ISSUE THREAD

**Issue by yurivict** [ROCm/HIP#1758]
The deprecation notice says that it's deprecated: https://github.com/RadeonOpenCompute/hcc

Yet hip fails without it:
```
CMake Error at CMakeLists.txt:139 (message):
  Don't know where to find HCC.  Please specify abolute path using -DHCC_HOME
```

**Comment by NAThompson** [comment]
Yes, it would be nice to receive some clarity about this. I imagine this is just a plan that never got implemented, but it creates some ambiguity about what the "blessed" workflow.

**Comment by alephpt** [comment]
and still nothing ?

**Comment by ppanchad-amd** [comment]
@yurivict  Sorry for the lack of response.  Please test with ROCm 6.0.2 (HIP 6.0.32831) to see if your issue still exists? If resolved, please close ticket. Thanks!
