### ISSUE TITLE
Compilation of HIP C kernels using clang compiler from LLVM-9

### ISSUE THREAD

**Issue by ghostplant** [ROCm/HIP#1769]
Is it able to use clang compiler provided by LLVM-9 to compile standard HIP kernels written in C?

**Comment by emankov** [comment]
HIP language extension is presented in clang 9.0; and what is your problem exactly?

  `+` @yxsamliu

**Comment by yxsamliu** [comment]
There may be some minor bugs but mostly it should work. You need to use install a rocm device library matching llvm-9.

**Comment by ppanchad-amd** [comment]
@ghostplant Please try latest ROCm 6.0.2 (HIP 6.0.32831) to see if your issue still exists? If resolved, please close the ticket. Thanks.
