### ISSUE TITLE
hipMemcpy3D(async) d2d >37x speedup possible

### ISSUE THREAD

**Issue by psychocoderHPC** [ROCm/HIP#1815]
For stencil codes as [PIConGPU](https://github.com/ComputationalRadiationPhysics/picongpu) it is important that memory copy operation has a low latency and high bandwidth. 
A common pattern is to surround the compute volume with halo/guard cells and copy these cells to the host memory and exchange the data via MPI to neighbor GPUs.
Typically 3D memcopies between memory hierarchies e.g. device to host are slow. To workaround this limitation PIConGPU serialize the data on the device and uses a 1D memcopy to move the data to the host (s. image)

![hipMemcpy3Dasync](https://user-images.githubusercontent.com/4037125/73059747-ac99d280-3e96-11ea-935d-277cdab39d37.png)

If the pich of the source and destination memory is not equal to the width of the extents the user is coping, the operation `hipMemcpy3D` will be split into `height*depth` independent 1D memcopies.

https://github.com/ROCm-Developer-Tools/HIP/blob/753277422a0637ff2bf541c7b43dfaaa2b12c9f6/src/hip_memory.cpp#L1668-L1679

In a stencil code such an operation will be performed up to a few hundred times per second. The current implementation on AMD (e.g. Radeon VII) gpus is very slow. An integration test with PIConGPU for a `64x64x64` cell volume needs `1.66` sec/simulation step.
Tested with 955b88ef5a6278c8759f635cfd384ef0d4fad49d + cherry-pick of #1798

When the `hipMemcpy3Dasync` operations for device2device are substituted with a kernel the performance can be increased by a factor `37` (`0.045` sec/simulation step).

# my suggestion

substitute `hipMemcpy3D` calls for device2device which not evaluate https://github.com/ROCm-Developer-Tools/HIP/blob/753277422a0637ff2bf541c7b43dfaaa2b12c9f6/src/hip_memory.cpp#L1662 to true with a kernel.

example implementation: 
ATTENTION in the example the tuples used compared to HIP a different order of the components.
`e.g. vec3D == vec3D(depth, height, widthInByte)`

https://github.com/psychocoderHPC/picongpu/blob/87074d6731115954e56f011a035a74fb22b2923b/thirdParty/alpaka/include/alpaka/mem/buf/hip/Copy.hpp#L46-L159

While the writing of this ticket I realized that `hipMemcpy2D` is already using a kernel to speedup the copy operation: https://github.com/ROCm-Developer-Tools/HIP/blob/753277422a0637ff2bf541c7b43dfaaa2b12c9f6/src/hip_memory.cpp#L1950-L1996

**Comment by ppanchad-amd** [comment]
@psychocoderHPC Is this ticket still relevant? Thanks!

**Comment by psychocoderHPC** [comment]
I close this ticket since the issue is already solved. It was solved at least with HIP 3.9+
