### ISSUE TITLE
How to get KMDUMPLLVM=1 IR without following procedure?

### ISSUE THREAD

**Issue by ghostplant** [ROCm/HIP#1832]
Is it possible to get the file `dump.kernel_input.ll` without following compilation procedure like the generation of host_binary / hsaco_binary.

In other words, instead of `KMDUMPLLVM=1 hipcc main.cc -o useless.out`,
I expect something like `ANY_HIP_CMD main.cc -o dump.kernel_input.ll`.

Any existing commands exist or other suitable solution?

**Comment by ppanchad-amd** [comment]
@ghostplant Apologies for the lack of response. Do you still require assistance with this ticket? Thanks!
