### ISSUE TITLE
-cuda Flag for Rocm

### ISSUE THREAD

**Issue by kayog96** [ROCm/HIP#1848]
I have a cuda file and compiled it with 
**nvcc -cuda --output-file kernel.cpp kernel.cu** which gives me cpp file which generates the code which can be compiled by host compiler

I would like to know is there any similar flag in hipcc which can generate similar output as in nvidia

**Comment by kayog96** [comment]
Kernel.cu & kernel.cpp file i am attaching.
 `
[kernel_cu & kernel_cpp.zip](https://github.com/ROCm-Developer-Tools/HIP/files/4180813/kernel_cu.kernel_cpp.zip)

I am then compiling kernel.cpp with mpicxx to generate the kernel.o file. Can we generate a similar kernel.cpp file with hipcc/hcc ?

**Comment by ppanchad-amd** [comment]
@kayog96 Sorry for the lack of response.  Do you still need assistance with ticket? Thanks!

**Comment by ppanchad-amd** [comment]
@kayog96 Closing ticket. Please re-open if you still need assistance with this ticket. Thanks!
