### ISSUE TITLE
this_thread_block() alternative in HIP

### ISSUE THREAD

**Issue by hpcresearch-ht** [ROCm/HIP#1878]
Hi
 this_thread_block() is not defined in ROCm in hip_cooperative_groups
is there any alternative/workaround for this

Thanks in advance

**Comment by ppanchad-amd** [comment]
@hpcresearch-ht , Sorry for the lack of response. Please try latest ROCm 6.0.2 (HIP 6.0.32831) to see if your issue still exists? If resolved, please close the ticket. Thanks.
