### ISSUE TITLE
Bug in hipMemset

### ISSUE THREAD

**Issue by ekuznetsov139** [ROCm/HIP#1888]
The following code 
https://github.com/ROCm-Developer-Tools/HIP/blob/master/src/hip_memory.cpp#L1854-L1860

is incorrect.

Suppose it is called with a pointer dst=0x01, type char, count 64.
Then aligned_dst is 0x04, n_head is 3, n=(64-3)/4=15, n_tail=0. Then handleHeadTail (line 1827) sets locations 0x01, 0x02, 0x03, and hsa_amd_memory_fill (line 1899) sets locations 0x4 through 0x3f. Location 0x40 is left unchanged. This is wrong.

Additionally, even if you correctly calculate n_tail as 1, it still won't work. Because, at line 1827, thread 0 sets 0x01, thread 1 sets 0x02, thread 2 sets 0x03, and thread 3 sets 0x01+(3-3+15*4)=0x3D instead of 0x40. Line 1827 should read

`                p[(threadIdx.x < nh) ? threadIdx.x : (threadIdx.x + nb)] = x;`

**Comment by nartmada** [comment]
Closing the ticket as issue has been fixed.
