### ISSUE TITLE
Missing constructors / assignment operators in hip_vector_types and general problems with __attribute((address_space(...))) in this* pointers

### ISSUE THREAD

**Issue by davidrohr** [ROCm/HIP#1892]
I have come across several problems in HIP using pointer to volatile variables or pointers attributed with an address space, in particular within the HIP_vector_types like uint4.
There are also problems passing such pointers to atomic functions.
Lastly, the problem with the attributed this* ptr is not specific to the HIP_vector_type, but it basically is a problem that lies rather in clang in my opinion, and it affects also my own classes, when I do similar things as HIP_vector_type.

Attached is a testcase for several issues, a an incomplete patch for the hip vector types header that fixes some of them.

[test.hip.cxx.tar.gz](https://github.com/ROCm-Developer-Tools/HIP/files/4239582/test.hip.cxx.tar.gz)
[hip_vectors.patch.tar.gz](https://github.com/ROCm-Developer-Tools/HIP/files/4239583/hip_vectors.patch.tar.gz)

**Comment by JonChesterfield** [comment]
I don't believe address_space can be applied to the implicit this pointer in clang (though it can be in some other compilers, e.g. there's some documentation by codeplay about doing so), so hip is presumably inheriting that limitation. Perhaps that limitation is better lifted in general, as opposed to only for hip.

**Comment by davidrohr** [comment]
I agree that some of the problems might be inherited from clang, while others relate to the HIP headers. For those in clang, I agree we should file a corresponding bug report there, to get this lifted in general.

**Comment by ppanchad-amd** [comment]
@davidrohr  Sorry for the lack of response. Please try latest ROCm 6.0.2 (HIP 6.0.32831) to see if your issue still exists? If resolved, please close the ticket. Thanks.
