### ISSUE TITLE
question about __byte_perm

### ISSUE THREAD

**Issue by jinz2014** [ROCm/HIP#1944]
I have a question about the selector.   Please see the comparison. Thanks.

In CUDA:
The selector indices are as follows (the upper 16-bits of the selector are not used): selector[0] = s<**2:0**> selector[1] = s<**6:4**> selector[2] = s<**10:8**> selector[3] = s<**14:12**>

In HIP:
__device__
static inline unsigned int __byte_perm(unsigned int x, unsigned int y, unsigned int s) {
    struct uchar2Holder cHoldVal;
    struct ucharHolder cHoldKey;
    struct ucharHolder cHoldOut;
    cHoldKey.ui = s;
    cHoldVal.ui[0] = x;
    cHoldVal.ui[1] = y;
    cHoldOut.c[0] = cHoldVal.c[cHoldKey.c[0]];   // 4-bit selector
    cHoldOut.c[1] = cHoldVal.c[cHoldKey.c[1]];
    cHoldOut.c[2] = cHoldVal.c[cHoldKey.c[2]];
    cHoldOut.c[3] = cHoldVal.c[cHoldKey.c[3]];
    return cHoldOut.ui;
}

**Comment by ppanchad-amd** [comment]
@jinz2014 Apologies for the lack of response.  Do you still need assistance with this ticket? Thanks!

**Comment by yiakwy-xpu-ml-framework-team** [comment]
> selector[0] = s<**2:0**> selector[1] = s<**6:4**> selector[2] = s<**10:8**> selector[3] = s<**14:12**>

I checked source codes of __byte_perm, I think rocm work in the eact way CUDA does:

```
// pack 8 bytes data together
CUDA:
uint64_t tmp64 = ((uint64_t)y << 32) | x

AMD:
struct uchar2Holder cHoldVal;
struct ucharHolder cHoldKey;
cHoldKey.ui = s;
cHoldVal.ui[0] = x;
cHoldVal.ui[1] = y;

// apply bit mask
CUDA:
selector0 = (s >> 0) & 0x7;
res[07:00] = tmp64[selector0];

selector1 = (s >> 4) & 0x7;
res[15:08] = tmp64[selector1];
...

AMD:
result = cHoldVal.c[cHoldKey.c[0] & 0x07];

result += (cHoldVal.c[(cHoldKey.c[0] & 0x70) >> 4] << 8);
...
```

@jinz2014

**Comment by jinz2014** [comment]
Thanks.
