### ISSUE TITLE
Many un-standard initialization method in HIP

### ISSUE THREAD

**Issue by zhaozhangjian** [ROCm/HIP#1952]
Please refer to this commit https://github.com/ROCm-Developer-Tools/HIP/commit/7c8b8d24ef7cc0f0c69db3ee9c785804ee9317b0
There are still many mistakes like this remaining in HIP code. Sometimes using braces to initialize can be taken the same way as initialization using parentheses, such as line 63 in src/hip_clang.cpp: _std::string triple{&desc->triple[0], sizeof(AMDGCN_AMDHSA_TRIPLE) - 1};_, but sometimes can't, just as the commit I mentioned above, which are very dangerous. So I strongly suggest correcting these wrong usage in HIP code.

**Comment by ppanchad-amd** [comment]
@zhaozhangjian  Sorry for the lack of response. Please try latest ROCm 6.0.2 (HIP 6.0.32831) to see if your issue still exists? If resolved, please close the ticket. Thanks.
