### ISSUE TITLE
device property question 

### ISSUE THREAD

**Issue by jinz2014** [ROCm/HIP#1970]
What is the HIP device property corresponding to the maximum memory allocation size in OpenCL ?

Thanks

**Comment by ppanchad-amd** [comment]
@jinz2014 Apologies for the lack of response.  Do you still need assistance with this ticket? Thanks!

**Comment by jinz2014** [comment]
Could HIP add a property for the maximum memory allocation size if it is not available ?

**Comment by ppanchad-amd** [comment]
@jinz2014 HIP is constrained by the Cuda API.  There is no plan to add this feature at the moment. Thanks!
