### ISSUE TITLE
hiprtc always returns HIPRTC_INTERNAL_ERROR in case of failed compilation

### ISSUE THREAD

**Issue by jpola** [ROCm/HIP#1981]
Hi, 
I have an issue with the hiprtc. In case of compilation error the hiprtc always returns the HIPRTC_ERROR_INTERNAL_ERROR status. In my opinion it should return HIPRTC_ERROR_COMPILATION. 
In addtion you can't get the logs from the failed compilation. (related to #1706).

Here is the patch which works for me:
```
diff --git a/src/hiprtc.cpp b/src/hiprtc.cpp
index 4efdbad6..6a1f4d36 100644
--- a/src/hiprtc.cpp
+++ b/src/hiprtc.cpp
@@ -522,10 +522,9 @@ extern "C" hiprtcResult hiprtcCompileProgram(hiprtcProgram p, int n, const char*
     args.emplace_back("-o");
     args.emplace_back(tmp.path() + '/' + "hiprtc.out");
 
-    if (!p->compile(args)) return HIPRTC_ERROR_INTERNAL_ERROR;
-    if (!p->readLoweredNames()) return HIPRTC_ERROR_INTERNAL_ERROR;
-
     p->compiled = true;
+    if (!p->compile(args)) return HIPRTC_ERROR_COMPILATION;
+    if (!p->readLoweredNames()) return HIPRTC_ERROR_INTERNAL_ERROR;
 
     return HIPRTC_SUCCESS;
 }
```

**Comment by ppanchad-amd** [comment]
@jpola Sorry for the lack of response. Please try latest ROCm 6.0.2 (HIP 6.0.32831) to see if your issue still exists? If resolved, please close the ticket. Thanks.
