### ISSUE TITLE
runtime_error :hipFuncGetAttributes.cpp compile with clang++

### ISSUE THREAD

**Issue by newbee816** [ROCm/HIP#2019]
compile hipFuncGetAttributes with clang (from llvm_amd:https://github.com/RadeonOpenCompute/llvm-project)

path HIP/tests/ 
```
hipcc -I src src/runtimeApi/module/hipFuncGetAttributes.cpp
./a.out
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  No device code available for function: __device_stub__Z2fnPfS_, for agent: gfx803
Aborted (core dumped)
However, try to compile the code with hcc, it's OK.

**Comment by ppanchad-amd** [comment]
@newbee816 Sorry for the lack of response. Please try latest ROCm 6.0.2 (HIP 6.0.32831) to see if your issue still exists? If resolved, please close the ticket. Thanks.
