### ISSUE TITLE
[Question]-How create an object  for the hipcc compilation results

### ISSUE THREAD

**Issue by anilbommareddy16** [ROCm/HIP#2020]
For an example: To create an object lib for the nvcc compilation  used as cuda_wrap_srcs
add_subdirectory(cuda_app)
cuda_include_directories(${PROJECT_SOURCE_DIR}/include)
cuda_wrap_srcs(app OBJ app_cuda_backend_obj cuda_app/cuZFP.cu)
app_cuda_backend_obj object created for cuda_app/cuZFP.cu .

Example: https://github.com/LLNL/blt/issues/75

similarly how to create an object for hipcc complication.?hid_add_libaray(app OBJ app_cuda_backend_obj cuda_app/cuZFP.cu) used?
The manually command to create object  /opt/rocm/bin/hipcc  cuZFP.cu -o app_cuda_backend_

2.CUDA_CUDART_LIBRARY available in FindCudaMake . similarly RT library in  FindHIP make?
I think CUDA_CUDART_LIBRARY is /opt/cuda/9.0/lib64/libcudart.so  and
 HIP is /opt/rocm/hip/lib/libhiprtc.so?

**Comment by anilbommareddy16** [comment]
In Cuda, to generate an object or build object files from cuda source using Cuda Cmake Macros(FindCudaCmake) "cud_compile" or "cuda_wrap_srcs". is similar cmake macro  not available in FindHipCmake 

https://www.gitmemory.com/issue/ROCm-Developer-Tools/HIP/732/491759132

**Comment by ppanchad-amd** [comment]
@anilbommareddy16 Apologies for the lack of response.  Do you still need assistance with this ticket? Thanks!

**Comment by ppanchad-amd** [comment]
@anilbommareddy16 Closing ticket. Please re-open if you still need assistance with this ticket. Thanks!
