### ISSUE TITLE
Compiler override mechanism

### ISSUE THREAD

**Issue by PhilipDeegan** [ROCm/HIP#2027]
Hi there,

is it possible to override this line: https://github.com/ROCm-Developer-Tools/HIP/blob/master/bin/hipcc#L249

I would like to use templight[0] instead of hcc, I've built templight with HCC from source, and it appears to work.

https://github.com/mikael-s-persson/templight

modifying the file works, but I don't like it so much

**Comment by ppanchad-amd** [comment]
@PhilipDeegan Please try using latest ROCm 6.0.2 (HIP 6.0.32831).  If issue is resolved, please close ticket. Thanks!

**Comment by PhilipDeegan** [comment]
@ppanchad-amd 
I forgot about this tbh
