### ISSUE TITLE
Cannot run tests successfully on Arch Linux (rocm-3.3.0 & master)

### ISSUE THREAD

**Issue by s-bernard** [ROCm/HIP#2078]
I’m trying to compile and run HIP with HCC on Arch Linux (yes, I know it is not officially supported).
On branches rocm-3.3.0 or master, I have always the following tests failing.

I tried two things to get the ROCm dependencies (hcc / hsa-rocr / etc.):
- compiled everything from sources (build files there: https://github.com/rocm-arch/rocm-arch)
- repackage ubuntu deb (I had to repackage libtinfo5 but so far no dynamic link issues) 

=> In both case, *same* results.

If I run a clean Ubuntu Bionic container and install ROCm, I can build HIP and tests pass.
If I copy the build directory from Arch Linux (with everything built) to Ubuntu, tests pass in Ubuntu. 

So it seems that the issue is at runtime with Arch Linux system libraries although they link correctly.
Have you any suggestion on how to debug this?

---

```
The following tests FAILED:
	66 - directed_tests/hiprtc/hiprtcGetLoweredName.tst (Child terminated)
	67 - directed_tests/hiprtc/saxpy.tst (Child terminated)
	105 - directed_tests/runtimeApi/memory/hipMemcpy-size.tst (Child aborted)
	106 - directed_tests/runtimeApi/memory/hipMemcpy-dev-offsets.tst (Child aborted)
	107 - directed_tests/runtimeApi/memory/hipMemcpy-host-offsets.tst (Child aborted)
	138 - directed_tests/runtimeApi/module/hipModuleTexture2dDrv.tst (Child aborted)
	156 - directed_tests/texture/hipBindTex2DPitch.tst (Child aborted)
	157 - directed_tests/texture/hipBindTexRef1DFetch.tst (Child aborted)
	159 - directed_tests/texture/hipTex1DFetchCheckModes.tst (Child aborted)
	160 - directed_tests/texture/hipTexObjPitch.tst (Child aborted)
	161 - directed_tests/texture/hipTextureObj1DFetch.tst (Child aborted)
	162 - directed_tests/texture/hipTextureObj2D.tst (Child aborted)
	163 - directed_tests/texture/hipTextureRef2D.tst (Child aborted)
	164 - directed_tests/texture/simpleTexture2DLayered.tst (Child aborted)
	165 - directed_tests/texture/simpleTexture3D.tst (Child aborted)
```

Some details:
```
> directed_tests/hiprtc/hiprtcGetLoweredName
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

> directed_tests/hiprtc/saxpy
error: Compilation failed.
error: TEST FAILED

> env HCC_SERIALIZE_KERNEL=0x3 HCC_SERIALIZE_COPY=0x3 HIP_TRACE_API=0x2 \
directed_tests/runtimeApi/module/hipModuleTexture2dDrv
HIP_DB=0x1 [api]
  hip-api pid:904145 tid:1:HIP initialized short_tid#1 (maps to full_tid: 0x7ff723214840)
<<hip-api pid:904145 tid:1.14 904145 1.14 hipLaunchKernel 'tex2dKernel' gridDim:{16,16,1}
groupDim:{16,16,1} sharedMem:+0 stream:0.0 @27181299926678
Memory access fault by GPU node-1 (Agent handle: 0x21ee840) on address (nil).
Reason: Page not present or supervisor privilege.

> directed_tests/texture/simpleTexture3D
simpleTexture3D starting...
error: 'hipErrorRuntimeOther'(1053) from
hipBindTexture2D(&tex_ofs, &tex, devPtrA, &tex.channelDesc, SIZE_W, SIZE_H, devPitchA)
at /HIP/tests/src/texture/hipBindTex2DPitch.cpp:66
error: API returned error code.
error: TEST FAILED
```

**Comment by s-bernard** [comment]
I found one of the issue, by setting `LD_PRELOAD="/opt/rocm/hsa/lib/libhsa-ext-image64.so.1.1.30300`, all texture tests + module works while `hiprtcGetLoweredName` and `saxpy` get the same errors.

No idea why the loading of libhsa-ext-image64 is done automatically.

**Comment by ppanchad-amd** [comment]
@s-bernard , Sorry for the lack of response. Please try latest ROCm 6.0.2 (HIP 6.0.32831) to see if your issue still exists? If resolved, please close the ticket. Thanks.

**Comment by s-bernard** [comment]
I dont have time to retest so I close it. Thanks.
