### ISSUE TITLE
Trouble running on NVIDIA GPU

### ISSUE THREAD

**Issue by efwright** [ROCm/HIP#2087]
I'm a new HIP user, and I am trying to use HIP on both an AMD and NVIDIA GPU.

I first installed HIP for my AMD GPU using the instructions from https://github.com/ROCm-Developer-Tools/HIP/blob/master/INSTALL.md, and I have had no problem compiling and running HIP code on the AMD GPU. Next, I swapped AMD for an NVIDIA GPU, installed the cuda-toolkit and verified that I could compile and run with NVCC, no issue there. Then I installed hip-nvcc. I have switched the HIP_PLATFORM variable to nvcc, as instructed by https://github.com/ROCm-Developer-Tools/HIP/blob/master/docs/markdown/hip_porting_guide.md.

This is the code I am trying to compile and run.
```
#include <hip/hip_runtime.h>
#include <stdio.h>
#include <stdlib.h>

void check(hipError_t err)
{
  if(err != hipSuccess) {
    printf("%s\n", hipGetErrorName(err));
    exit(-1);
  }
}

int main()
{
  float * a;
  check(hipMalloc((void**) &a, sizeof(float)));
  check(hipFree(a));
  return 0;
}
```

This is the output of my hipconfig
```
HIP version  : 3.5.20174-0b257068

== hipconfig
HIP_PATH     : /opt/rocm-3.3.0/hip
HIP_COMPILER : clang
HIP_PLATFORM : nvcc
HIP_RUNTIME  : HCC
CPP_CONFIG   :  -D__HIP_PLATFORM_NVCC__=  -I/opt/rocm-3.3.0/hip/include -I/usr/local/cuda/include

== nvcc
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89

=== Environment Variables
PATH=/home/efwright/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/rocm/bin:/opt/rocm/profiler/bin:/opt/rocm/opencl/bin/x86_64:/opt/rocm/bin:/opt/rocm/llvm/bin:/opt/rocm/hip/bin:/usr/local/cuda/bin:/opt/pgi/linux86-64/19.10/bin:/opt/pgi/linux86-64/19.10/mpi/openmpi-3.1.3/bin
HIP_PLATFORM=nvcc

== Linux Kernel
Hostname     : baby-yoda
Linux baby-yoda 5.3.0-51-generic #44~18.04.2-Ubuntu SMP Thu Apr 23 14:27:18 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

```

And the output of nvidia-smi
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  On   | 00000000:08:00.0  On |                  N/A |
| 22%   34C    P8    17W / 250W |    219MiB / 12205MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0       979      G   /usr/lib/xorg/Xorg                            15MiB |
|    0      1070      G   /usr/bin/gnome-shell                          48MiB |
|    0     10365      G   /usr/lib/xorg/Xorg                            84MiB |
|    0     10496      G   /usr/bin/gnome-shell                          64MiB |
+-----------------------------------------------------------------------------+
```

The error that I get when running is:
*hipErrorInvalidValue*
from the hipMalloc. If I remove the error checking, I get:
*There is no device can be used to do the computation*

Any feedback would be appreciated to get this working for me!

**Comment by gargrahul** [comment]
@efwright hip_nvcc has only been tested with cuda package that comes from Nvidia's cuda repo. Please check https://github.com/ROCm-Developer-Tools/HIP/issues/820#issuecomment-494336484 for possible work around.

**Comment by YifeiLuDublin** [comment]
I'm getting a different error 
/opt/rocm-3.5.1/hip/include/hip/nvcc_detail/hip_runtime_api.h(1348): error: class "cudaPointerAttributes" has no member "memoryType"
Below is my hipconfig output
`HIP version  : 3.5.20231-93097e0

== hipconfig
HIP_PATH     : /opt/rocm-3.5.1/hip
ROCM_PATH    : /opt/rocm-3.5.1
HIP_COMPILER : clang
HIP_PLATFORM : nvcc
HIP_RUNTIME  : ROCclr
CPP_CONFIG   :  -D__HIP_PLATFORM_NVCC__=  -I/opt/rocm-3.5.1/hip/include -I/usr/local/cuda/include

== nvcc
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_May__6_19:09:25_PDT_2020
Cuda compilation tools, release 11.0, V11.0.167
Build cuda_11.0_bu.TC445_37.28358933_0

=== Environment Variables
PATH=/home/users/mschpc/2019/luy5/bin:/home/users/mschpc/2019/luy5/.local/bin:/home/support/apps/cports/debian-stretch/sid.x86_64/gnu/gcc/7.4.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/cuda-11.0/bin:/usr/local/cuda-11.0/bin:/opt/rocm/bin
LD_LIBRARY_PATH=/home/support/apps/cports/debian-stretch/sid.x86_64/gnu/gcc/7.4.0/lib64:/home/support/apps/cports/debian-stretch/sid.x86_64/gnu/gcc/7.4.0/lib:/usr/local/cuda-11.0/lib64:/usr/local/cuda-11.0/lib64
HIP_PLATFORM=nvcc

== Linux Kernel
Hostname     : cuda01.tchpc.tcd.ie
Linux cuda01.tchpc.tcd.ie 4.4.0-184-generic #214-Ubuntu SMP Thu Jun 4 10:14:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
`

**Comment by ppanchad-amd** [comment]
@efwright,  Sorry for the lack of response. Please try latest ROCm 6.0.2 (HIP 6.0.32831) to see if your issue still exists? If resolved, please close the ticket. Thanks.
