### ISSUE TITLE
hipInvalidSymbol error when using hipMempcyFromSymbol

### ISSUE THREAD

**Issue by efwright** [ROCm/HIP#2088]
I'm trying to write a code in HIP using the function hipMemcpyFromSymbol, however am getting the hipInvalidSymbol error at runtime. I am using an AMD GPU for this, and other HIP codes work with my set up. This is the code:

```
#include <hip/hip_runtime.h>
#include <stdio.h>
#include <stdlib.h>

void check(hipError_t err)
{
  if(err != hipSuccess) {
    printf("%s\n", hipGetErrorName(err));
    exit(-1);
  }
}

__device__ float d_err;

__global__ void foo()
{
  d_err = 1.0f;
}

int main()
{
  hipLaunchKernelGGL(foo, dim3(1), dim3(1), 0, 0);
  float h_err = 0.0f;
  check(hipMemcpyFromSymbol(&h_err, HIP_SYMBOL(d_err), sizeof(float), 0, hipMemcpyDeviceToHost));
  printf("%.1f\n", h_err);
  return 0;
}
```

This is a CUDA version of the code that I have working on an NVIDIA Titan X using NVCC:

```
#include <cuda_runtime.h>
#include <stdio.h>

void check(cudaError_t err)
{
  if(err != cudaSuccess) {
    printf("%s\n", cudaGetErrorName(err));
    exit(-1);
  }
}

__device__ float d_err;

__global__ void foo()
{
  d_err = 1.0f;
}

int main()
{
  foo<<<1,1>>>();
  float h_err = 0.0f;
  check(cudaMemcpyFromSymbol(&h_err, d_err, sizeof(float), 0, cudaMemcpyDeviceToHost));
  printf("%.1f\n", h_err);
  return 0;
}
```

Any help is appreciated!

**Comment by gargrahul** [comment]
I am able to run attached HIP code with ROCm-3.3. Which ROCm version are you using ? Are you able run any other HIP example/sample?

**Comment by efwright** [comment]
I am able to compile and run some of the examples I tried that came with HIP. I also have written a few test codes in HIP, and hipify'd a few cuda codes. All are able to run on my Vega 10 XTX amd gpu.

I am using rocm 3.3.0, I fresh installed it earlier this month

**Comment by zjin-lcf** [comment]
I am able to run attached HIP code with ROCm-3.9 on a Vega20 GPU.

**Comment by ppanchad-amd** [comment]
@efwright  Sorry for the lack of response. Please try latest ROCm 6.0.2 (HIP 6.0.32831) to see if your issue still exists? If resolved, please close the ticket. Thanks.
