### ISSUE TITLE
hipMemGetInfo returns hipErrorFileNotFound

### ISSUE THREAD

**Issue by trail-coffee** [ROCm/HIP#2093]
I'm using the rocm-tensorflow docker image and my host has 5.6.15 linux kernel with Manjaro (Arch). I do not have ROCK installed (tensorflow appears to work without it).

I can't find the file that hipMemGetInfo is looking for on my system:
/sys/class/kfd/kfd/topology/nodes/0/mem_banks/0/used_memory

Do I need to roll back my kernel? HIP tests 105-107 fail for me. I think this is related to [https://github.com/ROCm-Developer-Tools/HIP/pull/1646](https://github.com/ROCm-Developer-Tools/HIP/pull/1646).

**Comment by SarbojitAMD** [comment]
@trail-coffee, do you still see the issue with the latest rocm?
