### ISSUE TITLE
hip-nvcc nvidia docker compatibility. 

### ISSUE THREAD

**Issue by PhilipDeegan** [ROCm/HIP#2101]
Trying to install hip-nvcc on the official docker container nvidia/cuda:10.2-devel-ubuntu18.04

results in apt trying to re-install nvidia drivers/libs

**Comment by ppanchad-amd** [comment]
@PhilipDeegan, Sorry for the lack of response. Please try latest ROCm 6.0.2 (HIP 6.0.32831) to see if your issue still exists? If resolved, please close the ticket. Thanks.
