### ISSUE TITLE
Broken `rocm` link

### ISSUE THREAD

**Issue by cpviolator** [ROCm/HIP#2115]
On this page, https://github.com/ROCm-Developer-Tools/HIP/blob/master/INSTALL.md#hip-clang there is a broken link for rocm

**Comment by ppanchad-amd** [comment]
@cpviolator Thanks! Sorry for the late response.  Internal ticket has been created to fix the broken link.

**Comment by ppanchad-amd** [comment]
@cpviolator https://github.com/ROCm-Developer-Tools/HIP/blob/master/INSTALL.md#hip-clang is pointing to the documentation in the master branch which is a 3+ year old branch. It is not the default branch. The default branch is https://github.com/ROCm/HIP/tree/develop. Closing ticket. Thanks!
