### ISSUE TITLE
Requirement of IMAGE_PITCH_ALIGNMENT on image width

### ISSUE THREAD

**Issue by zhaozhangjian** [ROCm/HIP#2116]
Hi,
I found in the function - hipError_t **allocImage()** located in **src/hip_memory.cpp**, there is a line of 
"size_t rowPitch = getElementSize(channelOrder, channelType) * alignUp(width, IMAGE_PITCH_ALIGNMENT);"
which puts alignment requirement on the width (the number of pixels) of an image allocated.
Could anyone tell me why there should be this requirement, and why it is on the number of pixels, not bytes?
Thanks in advance for your replies!

**Comment by ppanchad-amd** [comment]
Hi @zhaozhangjian , Sorry for the lack of response. Please try latest ROCm 6.0.2 (HIP 6.0.32831) to see if your issue still exists? If resolved, please close the ticket. Thanks.
