### ISSUE TITLE
Conflict in 3.7 and Nvidia platform

### ISSUE THREAD

**Issue by AJcodes** [ROCm/HIP#2144]
After updating to the latest ROCm version (3.7), we encounter the following compilation errors when trying to compile hipCUB on an Nvidia platform (CUDA 10.2)

```
/usr/local/cuda/include/cuda_fp16.h(1430): error: inline specifier allowed on function declarations only
/usr/local/cuda/include/cuda_fp16.h(1430): error: declaration is incompatible with overloaded function "__shfl_sync"
/usr/local/cuda/include/sm_30_intrinsics.h(133): here
/usr/local/cuda/include/cuda_fp16.h(1430): error: incomplete type is not allowed
/usr/local/cuda/include/cuda_fp16.h(1430): error: expected a ")"
/usr/local/cuda/include/cuda_fp16.h(1431): error: inline specifier allowed on function declarations only
/usr/local/cuda/include/cuda_fp16.h(1431): error: declaration is incompatible with overloaded function "__shfl_up_sync"
/usr/local/cuda/include/sm_30_intrinsics.h(135): here
...
```

We've tested the same code on previous ROCm versions (3.5 and below), and the same problem isn't apparent. We'll try to provide a log file soon, but can you try to reproduce this on your end?

**Comment by ppanchad-amd** [comment]
@AJcodes Sorry for the lack of response. Please try latest ROCm 6.0.2 (HIP 6.0.32831) to see if your issue still exists? If resolved, please close the ticket. Thanks.
