### ISSUE TITLE
Problems with -finstrument-functions in hipcc/ROCm through 3.7

### ISSUE THREAD

**Issue by wrwilliams** [ROCm/HIP#2151]
Per discussion with @eshcherb:

The -finstrument-functions flag for gcc and clang (and by extension hipcc) inserts calls to specially named instrumentation functions at entry and exit of each function. At link time, a user or tool respectively may then provide implementations of these instrumentation functions, frequently in a single shared or static library. I understand it is a known limitation that hipcc requires device-side implementations of these functions to be available as well. However, because each hipcc compilation of a mixed host/device CU performs a linking pass, this means that these device-side implementations must be present in each CU and cannot be shared. From an efficiency and correctness perspective, this is not great; from a tools perspective it's worse. Normally we provide a single implementation of our instrumentation functions in a library that's linked in, but this linking pass ensures that we need to instead rewrite source code.

It should also be noted that inserting device-side instrumentation rather than using the existing tracing/profiling interfaces is probably a bad idea under most circumstances--in order to make use of any data collected, a user would need a buffer mechanism similar to that in the tracing activity API.

I can see at least three valid solutions here:

1) Only apply -finstrument-functions to host code, leaving device code uninstrumented.
2) Provide default device-side empty implementations of instrumentation functions. Users who specifically want device-side instrumentation can implement per-CU as they see fit.
3) Change the internal linking approach during the compile pass, such that undefined symbols are allowed and device-side instrumentation can be implemented in a library.

Personally I would prefer 1 or 2, as I think it's better to ensure that the tools interfaces are sufficiently capable that we don't need or want extra device-side instrumentation (and overhead). But if there's a compelling use case that -finstrument-functions should work consistently across host and device, 3 is included for completeness--in Score-P we'd likely simply add empty device-side implementations.

**Comment by ppanchad-amd** [comment]
@wrwilliams  Sorry for the lack of response. Please try latest ROCm 6.0.2 (HIP 6.0.32831) to see if your issue still exists? Thanks!

**Comment by wrwilliams** [comment]
> @wrwilliams Sorry for the lack of response. Please try latest ROCm 6.0.2 (HIP 6.0.32831) to see if your issue still exists? Thanks!

This was fixed via use of `-Xarch-host -finstrument-functions` in our tool, which provides option 1.
