### ISSUE TITLE
llvm/clang not installed with rocm-3.7 on centos

### ISSUE THREAD

**Issue by cgleggett** [ROCm/HIP#2156]
when upgrading from rocm-3.5 to rocm-3.7 on centos7, looks like llvm is not installed in /opt/rocm:

```
> yum autoremove rocm-opencl rocm-dkms rock-dkms
> yum update
> yum install rocm-dkms
Installing:
 rocm-dkms x86_64 3.7.0_20-1 ROCm 3.8 k
Installing for dependencies:
 hip-rocclr x86_64 3.7.20315_077bcfa0-1 ROCm 674 k
 hip-samples x86_64 3.7.20315_077bcfa0-1 ROCm 68 k
 rock-dkms noarch 1:3.7-20.el7 ROCm 7.4 M
 rocm-clang-ocl x86_64 0.5.0.49_rocm_rel_3.7_20_7b47f7d-1 ROCm 4.6 k
 rocm-dev x86_64 3.7.0_20-1 ROCm 4.2 k
 rocm-opencl x86_64 2.0.0.293_rocm_rel_3.7_20_3f18143-1 ROCm 462 k
 rocm-opencl-devel x86_64 2.0.0.293_rocm_rel_3.7_20_3f18143-1 ROCm 91 k
 rocm-utils x86_64 3.7.0_20-1 ROCm 3.8 k
 rocprofiler-dev x86_64 1.0.0-1 ROCm 211 k
 roctracer-dev x86_64 1.0.0-1 ROCm 265 k

> rpm -qa | grep rocm | sort
comgr-1.6.0.149_rocm_rel_3.7_20_6670e0d-1.x86_64
hsa-rocr-dev-1.2.30700.0_rocm_rel_3.7_20_99e66a7a-1.x86_64
rocm-clang-ocl-0.5.0.49_rocm_rel_3.7_20_7b47f7d-1.x86_64
rocm-cmake-0.3.0.153_rocm_rel_3.7_20_1d1caa5-1.x86_64
rocm-dbgapi-0.30.0_rocm_rel_3.7_20-1.x86_64
rocm-debug-agent-2.0.1_rocm_rel_3.7_20-1.x86_64
rocm-dev-3.7.0_20-1.x86_64
rocm-device-libs-1.0.0.588_rocm_rel_3.7_20_5ff5319-1.x86_64
rocm-dkms-3.7.0_20-1.x86_64
rocm-gdb-9.2_rocm_rel_3.7_20-1.x86_64
rocminfo-1.30700.0-1.x86_64
rocm-opencl-2.0.0.293_rocm_rel_3.7_20_3f18143-1.x86_64
rocm-opencl-devel-2.0.0.293_rocm_rel_3.7_20_3f18143-1.x86_64
rocm-smi-1.0.0_204_rocm_rel_3.7_20_g08ebddd-1.x86_64
rocm-smi-lib64-2.4.0.15.rocm_rel_3.7_20_d325613-1.x86_64
rocm-utils-3.7.0_20-1.x86_64

> /opt/rocm-3.7.0/bin/hipcc --version
Can't exec "/opt/rocm-3.7.0/llvm/bin/clang++": No such file or directory at /opt/rocm-3.7.0/hip/bin/hipconfig line 141.

> ls /opt/rocm-3.7.0
total 48
4 bin/	4 hsa/	    4 lib/    4 oam/	 4 rocm_smi/	 4 roctracer/
4 hip/	4 include/  4 lib64/  4 opencl/  4 rocprofiler/  4 share/
```

**Comment by cgleggett** [comment]
hmm, looks like one needs to reinstall a few packages, such as `llvm-amdgpu` and `hsa-amd-aqlprofile`, as I'm guessing these are installed in `/opt/rocm` which is a soft link to the current version, but when you go from say 3.5 to 3.7, this gets lost.

perhaps the documentation could be updated?

**Comment by YifeiLuDublin** [comment]
"FRESH INSTALLATION OF AMD ROCm V3.7 RECOMMENDED

A fresh and clean installation of AMD ROCm v3.7 is recommended. An upgrade from previous releases to AMD ROCm v3.7 is not supported."

https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html

**Comment by cgleggett** [comment]
> "FRESH INSTALLATION OF AMD ROCm V3.7 RECOMMENDED

so I'm not sure what part of  `yum autoremove rocm-opencl rocm-dkms rock-dkms` doesn't look like a "FRESH INSTALLATION"

The problem is that `llvm-amdgpu` is not part of the rocm metapackge, so it doesn't get removed, and reinstalled automatically. But `hipcc` requires `llvm-amdgpu` to function. Yet the installation of the metapackage breaks llvm-amdgpu (and other packages) as it moves the soft link of `/opt/rocm` to point to `/opt/rocm-3.7.0`. So either the dependencies of `llvm-amdgpu` need to be fixed, or it needs to be brought into rocm, or the instructions need some work, so that ALL packages that are installed in /opt/rocm are identified and the user is told to reinstall them.

**Comment by Bengt** [comment]
I seemed to have a similar issue, which was alleviated by installing the explicitly named `llvm-amdgpu` package like so:

    sudo apt install llvm-amdgpu4.2.0
