### ISSUE TITLE
CMake HIP Language Support and usage of `hip::device`

### ISSUE THREAD

**Issue by robertmaynard** [ROCm/HIP#2158]
@pfultz2 

A quick scan of `hip-config` module has shown a couple of problems, for us to rely on importing it to find `hip::device`, or in general once CMake has `HIP` language support.

First we are going to have a chicken and egg problem. All versions of `hip-config` that currently exist have no understanding of first class HIP support in CMake. Therefore they do things like check if the c++ language is enabled which we can't presume.

Second `hip-config` needs to continue to work with all existing version of CMake that don't have `HIP` language support. So it will need to be updated to both work with C++ only projects, and HIP only projects.

I think what we need is a special module that HIP/ROCm provides that just has `hip::device_internal` which has only the bits that CMake needs. For now I am going to have it part of CMake so I can iterate faster

Current problems I see with `hip-config`

- Lines 141 through 160 set compiler flags for all languages on all targets that link to hip::device. These need to be guarded to only the HIP language ( or C++ when shimming in hipcc/hipclang as the C++ compiler). As it currently stands linking to `hip::device` with `C` enabled and set to `gcc` will break compilation

- Line 142 sets the rule that anything that links to `hip::device` gets compiled with `-x hip`. This breaks any target that has mixed languages ( C++ && HIP ) especially when the C++ compiler isn't clang based. You should only set this for `C++` sources when shimming in as the `C++` compiler.

- Line 164. All the above about global compile flags apply. Plus the following:
-- This should be explicit opt-in by the user
-- GPU_TARGET is set by this module and not the consumer so consumers can't override what subset of GPU's they want to compile for
-- This can't be applied for the `HIP` language as CMake will have a CMAKE_HIP_ARCHITECTURE flag

**Comment by robertmaynard** [comment]
What I imagine `HIPDeviceConfig` to look like is ( untested ):

```cmake

# Need to get this information from hip somehow
set(HIP_COMPILER "@HIP_COMPILER@")
set(HIP_RUNTIME "@HIP_RUNTIME@")

find_dependency(amd_comgr)

include( "${CMAKE_CURRENT_LIST_DIR}/hipdevice-targets.cmake" )

#If HIP isnot installed under ROCm, need this to find HSA assuming HSA is under ROCm
if( DEFINED ENV{ROCM_PATH} )
     set(ROCM_PATH "$ENV{ROCM_PATH}")
endif()

#get_filename_component cannot resolve the symlinks if called from /opt/rocm/lib/hip
#and do three level up again
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_DIR}" REALPATH)
get_filename_component(_IMPORT_PREFIX "${_DIR}/../../../" REALPATH)

#if HSA is not under ROCm then provide CMAKE_PREFIX_PATH=<HSA_PATH>
find_path(HSA_HEADER hsa/hsa.h
  PATHS
    "${_IMPORT_PREFIX}/../include"
    /opt/rocm/include
)

if (HSA_HEADER-NOTFOUND)
  message (FATAL_ERROR "HSA header not found! ROCM_PATH environment not set")
endif()

# Right now this is only supported for amd platforms
set_target_properties(hip::host PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "__HIP_PLATFORM_HCC__=1"
)

set_target_properties(hip::device PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "$<$<COMPILE_LANGUAGE:HIP>:${_IMPORT_PREFIX}/../include>"
    INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "$<$<COMPILE_LANGUAGE:HIP>:${_IMPORT_PREFIX}/../include>"
  )

if(HIP_RUNTIME MATCHES "VDI")
  set_target_properties(hip::amdhip64 PROPERTIES
    INTERFACE_COMPILE_DEFINITIONS "$<$<COMPILE_LANGUAGE:HIP>:__HIP_VDI__=1>"
    INTERFACE_INCLUDE_DIRECTORIES "$<$<COMPILE_LANGUAGE:HIP>:${_IMPORT_PREFIX}/include;${HSA_HEADER}>"
    INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "$<$<COMPILE_LANGUAGE:HIP>:${_IMPORT_PREFIX}/include;${HSA_HEADER}>"
  )
  set_target_properties(hip::device PROPERTIES
    INTERFACE_COMPILE_DEFINITIONS "$<$<COMPILE_LANGUAGE:HIP>:__HIP_VDI__=1>"
  )
else()
  set_target_properties(hip::hip_hcc_static PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "$<$<COMPILE_LANGUAGE:HIP>:${_IMPORT_PREFIX}/include;${HSA_HEADER}>"
    INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "$<$<COMPILE_LANGUAGE:HIP>:${_IMPORT_PREFIX}/include;${HSA_HEADER}>")

  set_target_properties(hip::hip_hcc PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "$<$<COMPILE_LANGUAGE:HIP>:${_IMPORT_PREFIX}/include;${HSA_HEADER}>"
    INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "$<$<COMPILE_LANGUAGE:HIP>:${_IMPORT_PREFIX}/include;${HSA_HEADER}>"
  )
endif()

if(HIP_COMPILER STREQUAL "clang")

  set_property(TARGET hip::device APPEND PROPERTY
    INTERFACE_COMPILE_OPTIONS "$<$<COMPILE_LANGUAGE:HIP>:--hip-device-lib-path=${AMD_DEVICE_LIBS_PREFIX}/lib>"
  )

  set_property(TARGET hip::device APPEND PROPERTY
    INTERFACE_COMPILE_OPTIONS "$<$<COMPILE_LANG_AND_ID:HIP,Clang,HIPClang>:-mllvm;-amdgpu-early-inline-all=true;-mllvm;-amdgpu-function-calls=false>"
  )

  set_property(TARGET hip::device APPEND PROPERTY
    INTERFACE_LINK_LIBRARIES "$<$<LINK_LANGUAGE:HIP>:--hip-device-lib-path=${AMD_DEVICE_LIBS_PREFIX}/lib;--hip-link>"
  )

endif()
```

**Comment by pfultz2** [comment]
> GPU_TARGET is set by this module and not the consumer so consumers can't override what subset of GPU's they want to compile for

It is a cached variable which can be set before calling `find_package(hip)`, however, I would like to change this to use a property `GPU_TARGET` and define it by default set from `GPU_TARGETS` variable:

```cmake
foreach(scope GLOBAL DIRECTORY TARGET)
  define_property(${scope} PROPERTY "GPU_TARGET" INHERITED
    BRIEF_DOCS "Enable compiling for gpu target for hip-clang"
    FULL_DOCS "Enable compiling for gpu target for hip-clang"
  )
endforeach()
set_property(GLOBAL PROPERTY GPU_TARGET ${GPU_TARGETS)})
# Property to identify when linking directly with `hip::device`.
define_property(TARGET PROPERTY "INTERFACE_HIP_DEVICE_COMPILE"
    BRIEF_DOCS "Compiling for hip::device"
    FULL_DOCS "Compiling for hip::device"
  )

set_property(TARGET hip::device APPEND PROPERTY COMPATIBLE_INTERFACE_BOOL INTERFACE_HIP_DEVICE_COMPILE)
set_property(TARGET hip::device PROPERTY INTERFACE_HIP_DEVICE_COMPILE ON)

set(GPU_ARCH_FLAGS "$<$<STREQUAL:$<TARGET_PROPERTY:INTERFACE_HIP_DEVICE_COMPILE>,ON>:--cuda-gpu-arch=$<JOIN:$<TARGET_PROPERTY:GPU_TARGET>, --cuda-gpu-arch=>>")
add_compile_options(${GPU_ARCH_FLAGS})
link_libraries(${GPU_ARCH_FLAGS})
```

I haven't tested this. The `INTERFACE_HIP_DEVICE_COMPILE` property is used to restrict the flags to targets that link with `hip::device`. I believe something like that should work, but I am not sure.

> What I imagine HIPDeviceConfig to look like is ( untested ):

This is of course missing the compiler includes, and searching for rocm device libs. Either way, I dont think we need a different cmake config. Instead, hip-config.cmake should have a flag to setup its targets for CMAKE_HIP_COMPILER or CMAKE_CXX_COMPILER. If HIP language is enabled then it will default to use `CMAKE_HIP_COMPILER` otherwise it will use `CMAKE_CXX_COMPILER`.

> This can't be applied for the HIP language as CMake will have a CMAKE_HIP_ARCHITECTURE flag

We can disable the `GPU_TARGET` property when using `CMAKE_HIP_COMPILER`. We could also work to deprecate these `GPU_TARGETS` variable(which predates cmake's `CMAKE_CUDA_ARCHITECTURES` variable) and move to use `CMAKE_HIP_ARCHITECTURES` variable so it can be consistent when using both HIP language and CXX language with hip. hip-config.cmake can set the default, so cmake doesn't need to introspect to find an arch.

**Comment by robertmaynard** [comment]
> It is a cached variable which can be set before calling find_package(hip)

You are correct, it can be overwritten but this pattern is a source of one of CMake trickier bugs with how local and cache variables interact. For example users would thing this would work:
```cmake
cmake_minimum_required(VERSION 3.14)
project(CacheExample CXX)

set(AMDGPU_TARGETS "gfx900")
set(AMDGPU_TARGETS "gfx900;gfx906;gfx908" CACHE STRING "AMD GPU targets to compile for")

message(STATUS "AMDGPU_TARGETS: ${AMDGPU_TARGETS}")
```
But on the initial execution of CMake the local variable override will be deleted and the cache variable will be used. On an subsequent invocation of CMake for that build directory the local variable will not be overridden. This generally is the root cause of bugs that happen once, but on re-execution of CMake go away.


> If HIP language is enabled then it will default to use CMAKE_HIP_COMPILER otherwise it will use CMAKE_CXX_COMPILER.

I don't know if this will work. A package can only be included once and we need the HIP support included even when the language isn't enabled. The reason for this is that we need to support the following workflow:
```cmake
project(CacheExample CXX)

find_package(HIP)
enable_language(HIP)
```
This pattern occurs often in the wild when large projects `add_subdirectory` or `fetch_content` other projects. The root project might be using `hipcc` as the `CXX` compiler and the subproject would be using `hipcc` as the `HIP` compiler.

**Comment by robertmaynard** [comment]
Also just noticed that the -mllvm flags need to be wrapped in `SHELL` so the `-mllvm` doesn't get detected as a duplicate flag and dropped.

**Comment by pfultz2** [comment]
> it can be overwritten but this pattern is a source of one of CMake trickier bugs with how local and cache variables interact. 

Yes there is that issue, but more importantly its not possible to create a cmake target for different gpu archs. So I think using properties will be a much better approach.

> I don't know if this will work. A package can only be included once and we need the HIP support included even when the language isn't enabled.

That is a good point. I am not sure how to best tackle this. I would like to avoid duplicating the usage requirements for hip, so we could create a generic config.cmake file and then configure it for hip lang and one for c++. We need to create two different target names for `hip::device`. Some refactoring needs to be done, because `host` and `device` is defined in the CMakeLists.txt. 

I think we might have a `find_package(hip-host)`(as `hip::host` should be the same for all languages), `find_package(hip-lang)`(for cmake's hip language), and then `find_package(hip)` for C++.

**Comment by robertmaynard** [comment]
> I think we might have a find_package(hip-host)(as hip::host should be the same for all languages), find_package(hip-lang)(for cmake's hip language), and then find_package(hip) for C++.

I like the sounds of this approach.

**Comment by MathiasMagnus** [comment]
@robertmaynard This would be a life changer. +💯

**Comment by bd4** [comment]
This looks great! I am porting a mixed Fortran / C++ CUDA code to ROCm/HIP, and with current 3.9 release and earlier, it causes fortran flags to be polluted with hipcc only options and breaks the build, so I've resorted to manually defining my own INTERFACE targets.

**Comment by robertmaynard** [comment]
> This looks great! I am porting a mixed Fortran / C++ CUDA code to ROCm/HIP, and with current 3.9 release and earlier, it causes fortran flags to be polluted with hipcc only options and breaks the build, so I've resorted to manually defining my own INTERFACE targets.

@bd4 I have opened a Pull Request to correct the existing hip-config so that it doesn't break Fortran compilation ( https://github.com/ROCm-Developer-Tools/HIP/pull/2190 )

**Comment by MathiasMagnus** [comment]
Any news on upstream picking up HIP support? How much is missing to deem it feature complete and shipping it?

**Comment by robertmaynard** [comment]
Nothing can happen until #2190 and #2183 are merged into ROCm.

**Comment by ppanchad-amd** [comment]
@robertmaynard Please close ticket if no longer relevant. Thanks!

**Comment by yiakwy-xpu-ml-framework-team** [comment]
Hi @robertmaynard I have a related question, suppose I have handled a .cu file will with USE_ROCM control to add hip api codes, and enabling HIP language in original cmake with CMAKE_HIP_ARCHITECTURE detected automatically.

How could I make the minimum effort to make a previously defined target (compiled internally by CMAKE_HIP_COMPILER, clang++ or hipcc), to compile with .cu sources ?

Since I found if I rename the .cu to .hip , I can compile successfully, but if I don't , the binary doesn't contain any symbols.

**Comment by mangupta** [comment]
@yiakwy-xpu-ml-framework-team : cmake determines the language based on source file extensions. It by default recognizes .hip files as HIP language, .cpp files as C++ language, etc. If you want to override this you need to use ```set_source_files_properties``` on the source files. Something similar to ```set_source_files_properties(${SOURCES} PROPERTIES HIP_SOURCE_PROPERTY_FORMAT 1)```.

**Comment by domcharrier** [comment]
**Just for completeness:**

You can change make all `*.cu` files (and whatever else you want) by putting this in front of your project's `project(...)` statement:

```diff
 cmake_minimum_required(VERSION 3.21 FATAL_ERROR) # HIP should be supported

 # ...

+set ( CMAKE_USER_MAKE_RULES_OVERRIDE " ${CMAKE_CURRENT_LIST_DIR} /<path_to_overrides.cmake>" )

 # ...

 project(....)
```

where the `overrides.cmake` file contains the line below:

```cmake
set (CMAKE_HIP_SOURCE_FILE_EXTENSIONS hip;cu) # extend as you wish
```

> [!WARNING]
> Do not attempt to "inline" the content of `overrides.cmake` into your project's `CMakeLists.txt`
> This won't work; more details: <https://cmake.org/cmake/help/latest/variable/CMAKE_USER_MAKE_RULES_OVERRIDE.html>
