### ISSUE TITLE
Problems with linking files

### ISSUE THREAD

**Issue by thom-popovici** [ROCm/HIP#2167]
Hello

I am having some problems with linking files when using hipcc.

I have 4 files kernel0.cpp kernel1.cpp kernel2.cpp and kernel3.cpp. Within those files I have the __global__ functions and some host functions that invoke the kernel launch.

I compile those first into .o files

I have anther file where the main resides. However when I try to link the previous four files with the main file I get something like this:
./src/gpu_amd/kernel0.o:5:32: error: source file is not valid UTF-8
<U+0000><U+0000> <U+0000><U+0000><U+0000>AMDGPU<U+0000><U+0000><82><AE>amdhsa.kernels<92><8F><A5>

Not quite sure how this error may be fixed. Any help appreciated.

Best,

**Comment by msimberg** [comment]
Commenting with another reproducer that I assume is the same problem. This is with
```
$ hipcc --version
HIP version: 3.8.20371-d1886b0b
clang version 11.0.0 (/data/jenkins_workspace/centos_pipeline_job_3.8/rocm-rel-3.8/rocm-3.8-30-20200915/7.7/external/llvm-project/clang b98349b12ffa706d0e863a3f1176b20d2a6c438b)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm-3.8.0/llvm/bin
```
We get a very similar error when linking to a(ny) shared library and having a cpp file in a specific position on the command line. Specifically, the following fails:
```
hipcc main.cpp /users/simbergm/install/boost-1.74.0-hipclang-c++14-debug/lib/libboost_system.so
```
with
```
/users/simbergm/install/boost-1.74.0-hipclang-c++14-debug/lib/libboost_system.so:1:1: error: expected unqualified-id                                                              
<U+007F>ELF<U+0002><U+0001><U+0001><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0003><U+0000>><U+0000><U+0001><U+0000><U+0000><U+0000><U+0010><U+000
5><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000>@<U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000>`$<U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+00
00><U+0000>@<U+0000>8<U+0000><U+0006><U+0000>@<U+0000><U+001D><U+0000><U+001C><U+0000><U+0001><U+0000><U+0000><U+0000><U+0005><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0
000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><A4><U+0006><U
+0000><U+0000><U+0000><U+0000><U+0000><U+0000><A4><U+0006><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000> <U+0000><U+0000><U+0000><U+0000><U+0000><U+0001><U+0000
><U+0000><U+0000><U+0006><U+0000><U+0000><U+0000><D8>
^
/users/simbergm/install/boost-1.74.0-hipclang-c++14-debug/lib/libboost_system.so:1:8: warning: null character ignored [-Wnull-character]
<U+007F>ELF<U+0002><U+0001><U+0001><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0003><U+0000>><U+0000><U+0001><U+0000><U+0000><U+0000><U+0010><U+000
5><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000>@<U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000>`$<U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+00
00><U+0000>@<U+0000>8<U+0000><U+0006><U+0000>@<U+0000><U+001D><U+0000><U+001C><U+0000><U+0001><U+0000><U+0000><U+0000><U+0005><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0
000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><A4><U+0006><U
+0000><U+0000><U+0000><U+0000><U+0000><U+0000><A4><U+0006><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000> <U+0000><U+0000><U+0000><U+0000><U+0000><U+0001><U+0000
><U+0000><U+0000><U+0006><U+0000><U+0000><U+0000><D8
[more similar errors]
```
It looks like it's trying to compile a shared library as a cpp file. In this case I'm linking to `libboost_system.so`, but I could reproduce this with several other shared libraries as well, and I don't think the particular library makes a difference. The contents of `main.cpp` also don't make a difference. The following compiles fine with `hipcc`:
```
hipcc /users/simbergm/install/boost-1.74.0-hipclang-c++14-debug/lib/libboost_system.so main.cpp
```
The cpp source file is last. Replacing `hipcc` with `g++` compiles fine in both variations.

**Comment by yxsamliu** [comment]
That is due to a limitation of clang. If the file extension is .cpp but it needs to be treated as HIP program, hipcc must pass -x hip to clang. However, -x option applies to any files after that, until another -x option. Unfortunately -x option is only for languages. There is no -x option for shared library. Therefore if a .so file is in the command line of hipcc, it needs to be put before .cpp files.

Other workaround is to use -l -L or -Wl, options.

**Comment by yxsamliu** [comment]
gcc has a -x none option to "stop" the previous -x option. I will try adding that to clang, then we can get hipcc fixed.

**Comment by yxsamliu** [comment]
actually, clang already supports -x none. So for this issue, you can use

hipcc main.cpp -x none /users/simbergm/install/boost-1.74.0-hipclang-c++14-debug/lib/libboost_system.so

we will fix hipcc to automatically add -x none when necessary.

**Comment by marcinkoziej** [comment]
Hi, could you fix this?

I had to hack llama.cpp Makefile to move all cpp files to the end. This bug is kinda lame!

**Comment by ppanchad-amd** [comment]
@thom-popovici,  Sorry for the lack of response. Please try latest ROCm 6.0.2 (HIP 6.0.32831) to see if your issue still exists? If resolved, please close the ticket. Thanks.
