### ISSUE TITLE
Question on status of math functions such as `remquo`

### ISSUE THREAD

**Issue by robertmaynard** [ROCm/HIP#2169]
Looking at HIP it seems that both `remquo` (double) and `remquof` (float) have device side support in 3.7.

The https://rocmdocs.amd.com/en/latest/ROCm_API_References/HIP-MATH.html docs list `remquo` (double) as unsupported.

Looking at the hip tests:
 - https://github.com/ROCm-Developer-Tools/HIP/blob/rocm-3.7.x/tests/src/deviceLib/hipSinglePrecisionMathDevice.cpp
- https://github.com/ROCm-Developer-Tools/HIP/blob/rocm-3.7.x/tests/src/deviceLib/hipDoublePrecisionMathDevice.cpp

I see that `remquo` (double) is tested, but  `remquof` (float) is not tested. So are these math functions safe to use?

Lastly it seems that functions such as `std::round()` properly map to the correct device function ( `roundf`  / `round` ), but when trying to using `std::remquo` I get an error ( see below ) which looks to be caused by a failure to map float parameters of `std::remquo` to `remquof`
```
lld: error: undefined symbol: remquo(float, float, int*)
```

**Comment by b-sumner** [comment]
I have no idea why that document says remquo (double) is not supported.  It is.  And again no idea why remquof is not included in those tests.  It is safe to use both functions and they are well tested elsewhere..

Regarding std::remquo, that is not technically standard cuda or hip.  But I think we are supporting various other overloads so some std functions can work.  We can probably include remquo in the mix.

**Comment by robertmaynard** [comment]
> It is safe to use both functions and they are well tested elsewhere..

Good to know

>  But I think we are supporting various other overloads so some std functions can work. We can probably include remquo in the mix.

That would be great!

**Comment by robertmaynard** [comment]
I am seeing the exact same issue with `std::modf` where when passed float values it looks for a C function of signature ` modf(float, float*)` instead ` modff(float, float*)`

**Comment by yxsamliu** [comment]
we will fix it too.

**Comment by robertmaynard** [comment]
Thanks

**Comment by robertmaynard** [comment]
Extending the report to also include `std::frexp(float, int*)`

**Comment by yxsamliu** [comment]
> Extending the report to also include `std::frexp(float, int*)`

will do. thanks.

**Comment by yxsamliu** [comment]
fixed by https://github.com/llvm/llvm-project/commit/d04775e16bba456f0be0aaa7478959c5bfa22c41
