### ISSUE TITLE
Potential compiler bug: operator [] returns a const reference with non-const array

### ISSUE THREAD

**Issue by aurianer** [ROCm/HIP#2173]
Compiler bug: Accessing a non-const array gives a const reference whereas it should give a non-const ref.

The following code triggers the `static_assert` with `-std=c++14`, the problem disappears when using `-std=c++17` or when removing the `__device__` qualifier.

Note: using `rocm-3.7.0` with default `hipclang`

```
#include <hip/hip_runtime_api.h>
#include <array>

__host__ __device__ void test() {
    std::array<int, 1> arr;
    static_assert(std::is_same<int&, decltype(arr[0])>::value,
        "Accessing a non-const array should give a non-const reference");
}

int main(int argc, char* argv[])
{
    test();
    return 0;
}
```

**Comment by yxsamliu** [comment]
It seems this issue was fixed in rocm3.9
