### ISSUE TITLE
Use of uninitialized value $HIP_COMPILER in string ne at /opt/rocm/hip/bin//hipcc line 657.

### ISSUE THREAD

**Issue by cederikhoefs** [ROCm/HIP#2176]
I am getting an error like the one mentioned in issue #1186, under which I commented already. Could somebody please fix this?

**Comment by SarbojitAMD** [comment]
@cederikhoefs, could you please get some more information, such as rocm-version, command used to build the app etc.
I tried to reproduce the issue with rocm-3.7.x (https://github.com/ROCm-Developer-Tools/HIP/tree/rocm-3.7.x) but did not see the issue. 
Latest release is rocm-3.8.x (https://github.com/ROCm-Developer-Tools/HIP/tree/rocm-3.8.x) would be great if you can confirm with released version.

Thanks

**Comment by cederikhoefs** [comment]
Sorry, I am quite busy at the moment, but I am definitely using rocm-3.8.0 as being downloaded freshly using `apt`. My backend to this points was CUDA 9, but I'll try again on a different machine soon. Thanks heaps for your answer.

**Comment by ppanchad-amd** [comment]
@cederikhoefs, Sorry for the lack of response. Please try latest ROCm 6.0.2 (HIP 6.0.32831) to see if your issue still exists? If resolved, please close the ticket. Thanks.

**Comment by cederikhoefs** [comment]
Sorry, didn't remember this thread...
