### ISSUE TITLE
Spelling correction required in Cmake error message.

### ISSUE THREAD

**Issue by krishoza** [ROCm/HIP#2180]
While building HIP test below error message is printed if HCC path is not set.

> message(FATAL_ERROR "Don't know where to find HCC. Please specify abolute path using -DHCC_HOME")

We can see that here the spelling correction is required in error message from `abolute` to `absolute`.

**Comment by ppanchad-amd** [comment]
@krishoza , Sorry for the lack of response. Please try latest ROCm 6.0.2 (HIP 6.0.32831) to see if the spelling is correct? If resolved, please close the ticket. Thanks.

**Comment by ppanchad-amd** [comment]
@krishoza Closing ticket. Please re-open if you still see the issue with latest ROCm 6.1.1 Thanks!
