### ISSUE TITLE
Cannot build HIP with HIP-clang

### ISSUE THREAD

**Issue by Chunming-Zhou** [ROCm/HIP#2184]
step1:
git clone https://github.com/llvm/llvm-project.git
mkdir -p build && cd build
cmake -DCMAKE_INSTALL_PREFIX=/opt/rocm/llvm -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=1 -DLLVM_TARGETS_TO_BUILD="AMDGPU;X86" -DLLVM_EXTERNAL_LLD_SOURCE_DIR=../lld -DLLVM_EXTERNAL_CLANG_SOURCE_DIR=../clang ../llvm
make -j
sudo make install

step2:
export PATH=/opt/rocm/llvm/bin:$PATH
git clone -b amd-stg-open https://github.com/RadeonOpenCompute/ROCm-Device-Libs.git
cd ROCm-Device-Libs
mkdir -p build && cd build
CC=clang CXX=clang++ cmake -DLLVM_DIR=/opt/rocm/llvm -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_WERROR=1 -DLLVM_ENABLE_ASSERTIONS=1 ..
make -j
sudo make install

step3:
git clone -b master https://github.com/ROCm-Developer-Tools/HIP.git
cd HIP
mkdir -p build && cd build
cmake -DCMAKE_INSTALL_PREFIX=/opt/rocm/hip -DHIP_PLATFORM=clang -DCMAKE_BUILD_TYPE=Debug ..

report cmake error:
CMake Error at tests/hit/HIT.cmake:375 (elseif):
  given arguments:

    "NOT" "_exclude_compiler" "AND" "IN_LIST" "_exclude_runtime"

  Unknown arguments specified
Call Stack (most recent call first):
  tests/hit/HIT.cmake:430 (hit_add_files)
  CMakeLists.txt:637 (hit_add_directory_recursive)

Can anyone figure out what't reason?  It's hard to build HIP now...

**Comment by xuhuisheng** [comment]
Here is my building scripts for ROCm-3.9, please refer.
https://github.com/xuhuisheng/rocm-build

**Comment by Chunming-Zhou** [comment]
> Here is my building scripts for ROCm-3.9, please refer.
> https://github.com/xuhuisheng/rocm-build
> 
> There are atleast 9 steps to build hip, you have just 3 steps.

my env is new ubuntu 20.04 as well, add video and rend groups, then follow your 11~19 steps, trying rocminfo gets below:error:
sudo ./rocminfo 
ROCk module is loaded
Unable to open /dev/kfd read-write: Bad address
zecai is member of video group
hsa api call failure at: /home/zecai/riyue/rocm/rocminfo/rocminfo.cc:1142
Call returned HSA_STATUS_ERROR_OUT_OF_RESOURCES: The runtime failed to allocate the necessary resources. This error may also occur when the core runtime library needs to spawn threads or create internal OS-specific events.

**Comment by Chunming-Zhou** [comment]
The reason to fail to open /dev/kfd is "amdgpu: Failure to set tba address. error -1." from dmesg. Anyone can figure out why?

**Comment by ppanchad-amd** [comment]
@Chunming-Zhou, sorry for the lack of response. Please try latest ROCm 6.0.2 (HIP 6.0.32831) to see if your issue still exists? If resolved, please close the ticket. Thanks.
