### ISSUE TITLE
amdgpu: Failure to set tba address. error -1.

### ISSUE THREAD

**Issue by Chunming-Zhou** [ROCm/HIP#2185]
my env is ubuntu20.04+kernel5.4.0-52
after installing as Rocm packages, running rocminfo get below dmesg error:
[   83.713477] amdgpu: Failure to set tba address. error -1.

drivers/gpu/drm/amd/amdkfd/kfd_process.c: kfd_process_init_cwsr_apu
                offset = KFD_MMAP_TYPE_RESERVED_MEM | KFD_MMAP_GPU_ID(dev->id);
                qpd->tba_addr = (int64_t)vm_mmap(filep, 0,
                        KFD_CWSR_TBA_TMA_SIZE, PROT_READ | PROT_EXEC,
                        MAP_SHARED, offset);

                if (IS_ERR_VALUE(qpd->tba_addr)) {
                        int err = qpd->tba_addr;

                        pr_err("Failure to set tba address. error %d.\n", err);
                        qpd->tba_addr = 0;
                        qpd->cwsr_kaddr = NULL;
                        return err;
                }

**Comment by ppanchad-amd** [comment]
@Chunming-Zhou, Sorry for the lack of response. Please try latest ROCm 6.0.2 (HIP 6.0.32831) to see if your issue still exists? If resolved, please close the ticket. Thanks.
