### ISSUE TITLE
Linker error when using CMake on nvcc platform

### ISSUE THREAD

**Issue by JieyangChen7** [ROCm/HIP#2200]
When linking compiled GPU obj file with a shared library that has the version number its soname (e.g., `libzfp.so.0.5.5`), an error would occur on nvcc platform. This because the soname with version number is passed to `nvcc` by `hipcc_cmake_linker_helper` and `nvcc` does not know how to handle soname with a version number. For example, when linking a test code with the Hipified ZFP library, we would get this error:

```
[ 73%] Linking HIP executable ../bin/zfp
cd /home/jieyang/dev/zfp/build/utils && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/zfpcmd.dir/link.txt --verbose=1
/home/jieyang/opt/hip/bin/hipcc_cmake_linker_helper /opt/rocm/hcc CMakeFiles/zfpcmd.dir/zfp.c.o -o ../bin/zfp   -L/usr/lib/gcc/x86_64-linux-gnu/7  ../lib/libzfp.so.0.5.5 -lm -lgcc -lgcc_s -lc -lgcc -lgcc_s 
nvcc fatal   : Don't know what to do with '../lib/libzfp.so.0.5.5'
```
Tested using HIP 3.10.20413-2080cc11 and CUDA 10.1.

Disabling generating soname with the version number using `set_target_properties(zfp PROPERTIES NO_SONAME 1 )` can solve the problem, but it is not a perfect solution.

```
[ 73%] Linking HIP executable ../bin/zfp
cd /home/jieyang/dev/zfp/build/utils && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/zfpcmd.dir/link.txt --verbose=1
/home/jieyang/opt/hip/bin/hipcc_cmake_linker_helper /opt/rocm/hcc CMakeFiles/zfpcmd.dir/zfp.c.o -o ../bin/zfp   -L/usr/lib/gcc/x86_64-linux-gnu/7  ../lib/libzfp.so -lm -lgcc -lgcc_s -lc -lgcc -lgcc_s 
make[2]: Leaving directory '/home/jieyang/dev/zfp/build'
[ 73%] Built target zfpcmd
```

Is there any chance that can be fixed in the future? Thanks.

**Comment by malcolmroberts** [comment]
This is an issue with nvcc; it won't link with things that don't end in '.so'.  This can be solved by chopping off the rest of the string, for example as here: https://github.com/ROCmSoftwarePlatform/hipFFT/blob/develop/clients/rider/CMakeLists.txt#L61

Otherwise best to raise an issue with the nvcc team.
