### ISSUE TITLE
Bit shift operations behave differently on NVCC and ROCM platforms

### ISSUE THREAD

**Issue by JieyangChen7** [ROCm/HIP#2201]
Bit shift operations under some cases can behave differently on `nvcc` and `rocm` platforms. For example: 

* CUDA or HIP with NVCC:
```
(1 << 64) - 1 = 18446744073709551615
18446744073709551615 >> 64 = 0
```
* HIP with ROCM:
```
(1 << 64) - 1 = 0
18446744073709551615 >> 64 = 18446744073709551615
```
The source code of simple examples can be found in [here](https://github.com/cjy7117/cuda_hip_bit_shift ).

We encountered those problems when hipifying the ZFP library, which needs a lot of bit operations. Our current solutions are to hard code the desired values when in those cases. Are those bugs?

**Comment by b-sumner** [comment]
I wouldn't call these bugs.  Standard C++ says "The behavior is undefined if the right operand is negative, or greater than or equal to the length in bits of the promoted left operand."  I'll also note that "1" is an int which is likely to be 32 bit on your platform.

**Comment by cjy7117** [comment]
"1" in our code is actually 64bit (unsigned long long). Are there any suggestions on keeping hipified code portable across both `NVCC` and `ROCM` platforms when we encounter this issue? Thanks!

**Comment by johnbridgman** [comment]
Are you running into issues shifting less than 64 bits, or just the 64-bit case ? I'm curious how a 64-bit shift of a 64-bit value would be used.

**Comment by pfultz2** [comment]
> I wouldn't call these bugs. Standard C++ says "The behavior is undefined if the right operand is negative, or greater than or equal to the length in bits of the promoted left operand." I'll also note that "1" is an int which is likely to be 32 bit on your platform.

It is only undefined behavior for signed integers. And in C++20 bit shifting signed integers is well defined behavior. From [[expr.shift]](http://eel.is/c++draft/expr.shift#2):

> The value of E1 << E2 is the unique value congruent to E1×2E2 modulo 2N, where N is the width of the type of the result.
> [Note 1: E1 is left-shifted E2 bit positions; vacated bits are zero-filled.
— end note]

Also cppreference's sections on [Bitwise shift operators](https://en.cppreference.com/w/cpp/language/operator_arithmetic#Bitwise_shift_operators) explain this.

**Comment by pfultz2** [comment]
> Are there any suggestions on keeping hipified code portable across both NVCC and ROCM platforms when we encounter this issue?

You could try to build with `-std=c++20` to get well defined behavior.
