### ISSUE TITLE
hip_fp16_gcc.h compile failed when build mxnet

### ISSUE THREAD

**Issue by andyzhanged** [ROCm/HIP#2208]
I try to install mxnet follow the install guide in https://github.com/ROCmSoftwarePlatform/mxnet, the compiler report error when compile hip_fp16_gcc.h. The file is located in "HIP/include/hip/hcc_detail/hip_fp16_gcc.h". Error reason is the follow two function declaration as a global symbol, But the definition is in namespace anonymous.So the gcc compiler is ambiguous.

```
 __half __float2half(float);
 float __half2float(__half);
``` 

I am confused about this code, cause the gcc compiler does support this grammar. I write a case to test this usage.
namespace.hpp
```
int add(int a, int b);

namespace{

    int add(int a, int b)
    {
        return (a + b);
    }
}
```
namespace.cpp
```
#include "namespace.hpp"
int main()
{
    add(1, 2);
    return 0;
}
```
Then gcc compile report  error:
```
# zhanged @ dcu in ~/backup/test [16:48:20] C:127
$ gcc namespace.cpp 
namespace.cpp: In function ‘int main()’:
namespace.cpp:5:13: error: call of overloaded ‘add(int, int)’ is ambiguous
     add(1, 2);
             ^
namespace.hpp:1:9: note: candidate: int add(int, int)
     int add(int a, int b);
         ^~~
namespace.hpp:5:9: note: candidate: int {anonymous}::add(int, int)
     int add(int a, int b)
         ^~~
```
So i think, this usage is wrong, i try to modify, just move namespace forward as following patch shows:
```
$ cat hip_fp16_gcc_h.patch     
--- hip_fp16_gcc.h.bak  2020-12-23 16:40:37.822343698 +0800
+++ hip_fp16_gcc.h      2020-12-23 16:47:02.854487938 +0800
@@ -4,6 +4,7 @@
     #include <cstring>
 #endif
 
+namespace{
 struct __half_raw {
     unsigned short x;
 };
@@ -94,7 +95,7 @@
         }
     };
     // END STRUCT __HALF2
-    namespace{
+   
         inline
         unsigned short __internal_float2half(
             float flt, unsigned int& sgn, unsigned int& rem)
```
Mxnet can build success. I am unfamiliar with hip code, maybe my method has some defect. Is some one has more appropriate method to resolve this bug?
Thanks.

**Comment by andyzhanged** [comment]
make -jn(n=number of cores)  CXX=g++-6 USE_GPU=1 (For Ubuntu 18.04)

**Comment by MathiasMagnus** [comment]
rocRAND is suffering from the same issue when using the nvcc back-end (in tandem with GCC as a host compiler) for compilation. fp16 functions are declared as global functions but then implemented inside an anonymous namespace. GCC picks up both during name lookup and enrolls both functions into overload resolution, which then becomes ambigous. What was the reason to create an anonymous namespace for these functions?

Host headers are patchable, as demonstrated by @andyzhanged but many projects using fp16 ops are going to choke on this.

**Comment by saadrahim** [comment]
@MathiasMagnus can you confirm which ROCm release you saw this issue in?

**Comment by MathiasMagnus** [comment]
@saadrahim I could not reproduce the issue in 4.1.

**Comment by ppanchad-amd** [comment]
@andyzhanged, Please try latest ROCm 6.0.2 (HIP 6.0.32831) to see if your issue still exists? If resolved, please close the ticket. Thanks.
