### ISSUE TITLE
Inconsistent handling of NaN with `std::min` and `std::max`

### ISSUE THREAD

**Issue by robertmaynard** [ROCm/HIP#2209]
## Issue

Expectation is that `std::min` and `std::max` would be consistent with each other on what parameter they return when called with `NaN` and `Inf`. Currently hipcc isn't consistent, and the following code behavior changes when compiled with `-x hip` compared to `-x c++`. Specifically `std::min` when compiled with `-x hip` takes the second parameter instead of the first.

## Reproducer
```cxx
#include <cstdint>
#include <iostream>

static double Nan64()
{
  return std::numeric_limits<double>::quiet_NaN();
}

static double NegativeInfinity64()
{
  return  std::numeric_limits<double>::infinity() * -1.0;
}

int main(int argc, char* argv[])
{
  std::cout << "std::min of -inf and nan" << std::endl;
  std::cout << "\t " << std::min( NegativeInfinity64(), Nan64() ) << std::endl;

  std::cout << "std::min of nan and -inf" << std::endl;
  std::cout << "\t " << std::min( Nan64(), NegativeInfinity64() ) << std::endl;

  std::cout << "std::max of -inf and nan" << std::endl;
  std::cout << "\t " << std::max( NegativeInfinity64(), Nan64() ) << std::endl;

  std::cout << "std::max of nan and -inf" << std::endl;
  std::cout << "\t " << std::max( Nan64(), NegativeInfinity64() ) << std::endl;

  return 0;
}
```

### Output with `-x c++`

```
std::min of -inf and nan
         -inf
std::min of nan and -inf
         nan
std::max of -inf and nan
         -inf
std::max of nan and -inf
         nan
```

### Output with `-x hip`

```
std::min of -inf and nan
         nan
std::min of nan and -inf
         -inf
std::max of -inf and nan
         -inf
std::max of nan and -inf
         nan
```

Tested with ROCm 3.9

**Comment by ppanchad-amd** [comment]
@robertmaynard  Sorry for the lack of response. Please try latest ROCm 6.0.2 (HIP 6.0.32831) to see if your issue still exists? If resolved, please close the ticket. Thanks.

**Comment by lamikr** [comment]
I think this should be opened as "-x hip" is returning different values than other 3 compilers I tested and because of this bug there is need for a workarounds in pytorch for example at Atomic.cuh

template <typename T>
__host__ __device__ T safe_min(T a, T b) {
  #if defined(__HIPCC__)
  // TODO: remove this special case for HIP when issue is fixed:
  //       https://github.com/ROCm-Developer-Tools/HIP/issues/2209
    T min = at::_isnan(a) ? a : (at::_isnan(b) ? b : std::min<T>(a, b));
  #else
    T min = at::_isnan(b) ? b : std::min<T>(a, b);
  #endif

  return min;
}

There can be other places where the bug is affecting also and which are not fixed. For example the call to clamp function in IndexKernel.hip file of pytorch. (Thats currently triggering for me an assert error on Fedora that I am investigating)

**Comment by lamikr** [comment]
I modified the test code a bit so that results with different compilers are easier to check. Also limits needed to be included for some of the compilers.

```
#include <limits>
#include <cstdint>
#include <iostream>

static double Nan64() {
  return std::numeric_limits<double>::quiet_NaN();
}

static double NegativeInfinity64() {
  return  std::numeric_limits<double>::infinity() * -1.0;
}

int main(int argc, char* argv[]) {
  std::cout << "std::min of -inf and nan: \t";
  std::cout << std::min( NegativeInfinity64(), Nan64() ) << std::endl;

  std::cout << "std::min of nan and -inf: \t";
  std::cout << std::min( Nan64(), NegativeInfinity64() ) << std::endl;

  std::cout << "std::max of -inf and nan: \t";
  std::cout << std::max( NegativeInfinity64(), Nan64() ) << std::endl;

  std::cout << "std::max of nan and -inf: \t";
  std::cout << std::max( Nan64(), NegativeInfinity64() ) << std::endl;

  return 0;
}
```

And build script I use:

```
hipcc -v -x hip testcase.cpp -o testcase_hip_x_hip
hipcc -v -x c++ testcase.cpp -o testcase_hip_x_c++
/usr/bin/clang++ -x hip testcase.cpp -o testcase_usr_bin_clang
/usr/bin/g++ -v -x c++ testcase.cpp -o testcase_usr_bin_g++


```

**Comment by lamikr** [comment]
And here are the results:

```
[lamikr@localhost hipcc_bug]$ ./testcase_hip_x_hip 
std::min of -inf and nan: 	nan
std::min of nan and -inf: 	-inf
std::max of -inf and nan: 	-inf
std::max of nan and -inf: 	nan
[lamikr@localhost hipcc_bug]$ ./testcase_hip_x_c++ 
std::min of -inf and nan: 	-inf
std::min of nan and -inf: 	nan
std::max of -inf and nan: 	-inf
std::max of nan and -inf: 	nan
[lamikr@localhost hipcc_bug]$ ./testcase_us
[lamikr@localhost hipcc_bug]$ ./testcase_usr_bin_clang 
std::min of -inf and nan: 	-inf
std::min of nan and -inf: 	nan
std::max of -inf and nan: 	-inf
std::max of nan and -inf: 	nan
[lamikr@localhost hipcc_bug]$ ./testcase_usr_bin_g++
std::min of -inf and nan: 	-inf
std::min of nan and -inf: 	nan
std::max of -inf and nan: 	-inf
std::max of nan and -inf: 	nan
```
So all "-x hip" option differs from all others and should most likely be fixed.

**Comment by yxsamliu** [comment]
This seems to be clang issue. I will try fixing it.
