### ISSUE TITLE
Device to device copy does not work with vanilla linux kernel

### ISSUE THREAD

**Issue by seesturm** [ROCm/HIP#2214]
My system:
* 2x Vega56
* Linux kernel 5.10.5 (without rocm-dkms)
* HIP from ROCm 4.0.0

d2d copy does not work with official linux kernel. There are no error messages, neither on stdout/stderr nor dmesg. But values are wrong. Example:
```C
#include <stdio.h>
#include <hip/hip_runtime.h>

#define HIPCHECK(cmd) myHipCheck(cmd, __FILE__, __LINE__)
void myHipCheck(hipError_t e, const char *file, int line)
{
	if (e != hipSuccess) {
		printf("Failed: HIP error %s:%d '%s'\n",
			__FILE__, __LINE__, hipGetErrorString(e));
		exit(EXIT_FAILURE);
	}
}

__global__ void fillmem(int *data)
{
	int idx = hipThreadIdx_x + hipBlockDim_x * hipBlockIdx_x;
	data[idx] = idx;
}

void compare(int *buf, size_t size)
{
	 int tmp[size];
	 hipMemcpy(tmp, buf, sizeof tmp, hipMemcpyDeviceToHost);
	 for (int i=0; i<size; i++) {
		int v = tmp[i];
		const char *result = i==v ? "EQUAL" : "MISMATCH";
	 	printf("compare %d %d => %s\n", i, v, result);
	 }
}

int main(int argc, char* argv[])
{
	size_t size = 10;
	int nDev = 2;
	int *devbuff[nDev];
	hipStream_t s[nDev];

	for (int i = 0; i < nDev; ++i) {
		HIPCHECK(hipSetDevice(i));
		HIPCHECK(hipMalloc(devbuff + i, size * sizeof**devbuff));
		HIPCHECK(hipStreamCreate(s+i));
	}

	// Fill memory on GPU 0
	fillmem<<<1, size, 0, s[0]>>>(devbuff[0]);

	for (int i = 0; i < nDev; ++i)
		HIPCHECK(hipStreamSynchronize(s[i]));

	// Copy memory from GPU 0 to GPU 1
	HIPCHECK(hipMemcpyDtoD(devbuff[1], devbuff[0], size * sizeof**devbuff));

	for (int i = 0; i < nDev; ++i)
		HIPCHECK(hipStreamSynchronize(s[i]));

	compare(devbuff[1], size);
	return 0;
}
```
Gives output
```
compare 0 -1068368063 => MISMATCH
  ...
```

**Comment by seesturm** [comment]
Following commit on rocm-dkms seems to enable device-to-device transfers
https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver/commit/3b29a7d85e6b4c095b2c44c632210b529715f8ce

I modified the patch against 5.10.5.
[p2p-5.10.5-github.diff.txt](https://github.com/ROCm-Developer-Tools/HIP/files/5792508/p2p-5.10.5-github.diff.txt)
Can somebody hand it over to kernel team for inclusion into upcoming kernel version?

**Comment by sunway513** [comment]
cc @kentrussell from kernel team for awareness.

**Comment by kentrussell** [comment]
The upcoming 4.1 release will be based on the 5.9 kernel and will have the KFD patches (including this one) rebased accordingly. I'll leave it open to verify that 4.1 resolves it.

**Comment by seesturm** [comment]
Thanks for the update. But my question is for the case when rocm-dkms is NOT installed. I'm currently using 5.10.x kernel. Is there any chance that upstream kernel will get the mentioned patch integrated?

**Comment by kentrussell** [comment]
Sorry for the confusion there. For upstream, the effort is being made to move all of the P2P code upstream, but there were some issues with the initial RDMA and IPC implementations which blocked the initial attempt to upstream the code. The code is being cleaned up and attempted to be upstreamed again, but there's no definitive timeframe for when it will be fully in the upstream kernel, as far as I know. @fxkamd may have more insight into that however

**Comment by fxkamd** [comment]
I think the issue here is about PCIe P2P, not about IPC or RDMA. IPC can probably go upstream. (RDMA cannot, because it interfaces with other non-upstream drivers only.)

Our current PCIe P2P implementation in the DKMS driver is a bit of a hack, which is why we haven't been able to upstream it yet. Proper PCIe P2P support upstream is a more long-term effort.
