### ISSUE TITLE
Improve the env/cmake variable situation

### ISSUE THREAD

**Issue by haampie** [ROCm/HIP#2224]
If you install rocm with non-standard prefixes using `spack`, which is currently by far the easiest way to compile the rocm ecosystem from sources, you have to configure an overwhelming number of environment variables, and not all of them even make sense.

To make hipcc work, the following variables have to be set:

```
HIP_PATH
ROCM_PATH
HIP_LIB_PATH
HIP_CLANG_PATH
DEVICE_LIB_PATH
HSA_PATH
```
where `ROCM_PATH` is useless, since in spack installations there is no flat `$ROCM_PATH/bin`, `$ROCM_PATH/lib`, `$ROCM_PATH/llvm` folders.

Then, to make [clang](https://github.com/RadeonOpenCompute/llvm-project/) happy, you have to define:

```
HIP_DEVICE_LIB_PATH
```

And to make [comgr](https://github.com/RadeonOpenCompute/ROCm-CompilerSupport) happy, you have to define:

```
LLVM_PATH
ROCM_PATH (again... same issues)
HIP_PATH
```

and if you want to actually use the `hip::host` target in cmake when using GCC, [you also have to inform it](https://github.com/ROCm-Developer-Tools/HIP/blob/main/hip-config.cmake.in#L69) where hip/clang is installed again... Since https://github.com/ROCm-Developer-Tools/HIP/blob/main/hip-config.cmake.in#L68 is not working because `${ROCM_PATH}/llvm` does not exist, you got to define
```
-DHIP_CXX_COMPILER=[install prefix of HIP]
```

Most of these issues can simply be resolved by just making cmake locate all dependencies, then generate a file with all these paths hard-coded which serve as default search paths when running `hipcc` on the command line or find_package(hip) in a dependent package. And make sure the user can still override them with env variables if necessary.

Of course this does not entirely solve the problem for comgr / llvm, since rocm-device-libs depends on llvm, so llvm can't know about HIP_DEVICE_LIB_PATH, and similarly comgr cannot know about HIP_PATH.

**Comment by pfultz2** [comment]
> is not working because ${ROCM_PATH}/llvm does not exist, you got to define
> -DHIP_CXX_COMPILER=[install prefix of HIP]

That should be set to the clang compiler(ie /opt/rocm/llvm/bin/clang++) not hip prefix. A variable like this would still be needed if you compile hip as separate language as you need to set CMAKE_HIP_COMPILER(cmake could make some guesses but probably not if you are using spack).

But I believe this requirement should be optional for `hip::host`.

> Most of these issues can simply be resolved by just making cmake locate all dependencies, then generate a file with all these paths hard-coded which serve as default search paths when running hipcc on the command line or find_package(hip) in a dependent package.

I believe hipcc needs to be relocatable. On the build server, the dependencies are installed in different locations, so this is why hipcc doesn't hard code these values. This really should be fixed.

Ideally, hipcc shouldn't be used with cmake. Its mainly for non-cmake users as it can't understand the cmake build environment. hipcc should also use pkg-config to get its usage requirement so users only need to set `PKG_CONFIG_PATH`. 

A cmake user should only need to set `CMAKE_PREFIX_PATH` to get the dependencies(which most source-based package managers set automatically), and if that doesn't work it should be reported as a bug.

**Comment by haampie** [comment]
The gripe continues, but this time with visiblity env variables:

These env variables are all used somewhere in the ROCm ecosystem:
```
HIP_VISIBLE_DEVICES
CUDA_VISIBLE_DEVICES
GPU_DEVICE_ORDINAL
ROCR_VISIBLE_DEVICES
```

Why can't it just be 1 single variable?

**Comment by gandryey** [comment]
ROCR_VISIBLE_DEVICES is a variable for HSA runtime. It simply can't work in Windows. Also there are some applications which use HSA runtime directly and may require this level of control.
GPU_DEVICE_ORDINAL is the original OpenCL runtime variable to control the reported devices.
HIP_VISIBLE_DEVICES came from HIP-HCC implementation for compatibility. People still wanted to use it instead of unknown GPU_DEVICE_ORDINAL.
CUDA_VISIBLE_DEVICES exists for compatibility with CUDA and was ported over from HIP-HCC. I'm not sure if anyone still uses it, but it has the same logic as HIP_VISIBLE_DEVICES.

**Comment by haampie** [comment]
Ok... I think the number of variables is confusing people and the rocm packages too. For instance this is what slurm 20.11.3 chooses to set:

```
$ srun -wault08 --gres=gpu:3 --gpu-bind=map_gpu:0,1,2 --time=1 -n3 /bin/bash -c 'echo "${HIP_VISIBLE_DEVICES:-unset} ${ROCR_VISIBLE_DEVICES:-unset} ${CUDA_VISIBLE_DEVICES:-unset} ${GPU_DEVICE_ORDINAL:-unset}"'
unset 1 1 1
unset 0 0 0
unset 2 2 2
```
so `ROCR_VISIBLE_DEVICES`, `CUDA_VISIBLE_DEVICES` and `GPU_DEVICE_ORDINAL`.

And this is how clinfo handles this combination of variables:

```
$ srun -wault08 --gres=gpu:3 --gpu-bind=map_gpu:0,1,2 --time=1 -n3 /bin/bash -c '/opt/rocm-4.0.1/opencl/bin/clinfo | grep devices'
srun: job 61682 queued and waiting for resources
srun: job 61682 has been allocated resources
Number of devices:				 0
Number of devices:				 0
Number of devices:				 1
```
Seems like it fitlers the devices twice. When I unset some combination of variables:


```
$ srun -wault08 --gres=gpu:3 --gpu-bind=map_gpu:0,1,2 --time=1 -n3 /bin/bash -c 'unset ROCR_VISIBLE_DEVICES; /opt/rocm-4.0.1/opencl/bin/clinfo | grep devices'
Number of devices:				 1
Number of devices:				 1
Number of devices:				 1

$ srun -wault08 --gres=gpu:3 --gpu-bind=map_gpu:0,1,2 --time=1 -n3 /bin/bash -c 'unset CUDA_VISIBLE_DEVICES; /opt/rocm-4.0.1/opencl/bin/clinfo | grep devices'
Number of devices:				 0
Number of devices:				 0
Number of devices:				 1

$ srun -wault08 --gres=gpu:3 --gpu-bind=map_gpu:0,1,2 --time=1 -n3 /bin/bash -c 'unset GPU_DEVICE_ORDINAL; /opt/rocm-4.0.1/opencl/bin/clinfo | grep devices'
Number of devices:				 1
Number of devices:				 1
Number of devices:				 1
```

Is this to be expected?

**Comment by mattaezell** [comment]
@haampie see https://bugs.schedmd.com/show_bug.cgi?id=11097 for a discussion about the variables Slurm sets. It looks like Slurm is going to have to stop setting all 3.

**Comment by haampie** [comment]
Thanks, I forgot to file an issue there, happy that's done.

**Comment by ppanchad-amd** [comment]
@haampie Is this ticket still relevant or can we go ahead and close it? Please advise!
