### ISSUE TITLE
Dead link in installation guide

### ISSUE THREAD

**Issue by r-burns** [ROCm/HIP#2227]
It appears the link to rocm setup in the INSTALL guide is dead. In the hip-clang setup:
https://github.com/ROCm-Developer-Tools/HIP/blob/2080cc113a2d767352b512b9d24c0620b6dee790/INSTALL.md#hip-clang
The text "Install the rocm package" links to here:
https://gpuopen.com/getting-started-with-boltzmann-components-platforms-installation/
but unfortunately that page appears to have been removed.
I was able to find an archived copy here:
https://web.archive.org/web/20191215130247/https://gpuopen.com/getting-started-with-boltzmann-components-platforms-installation/

**Comment by ppanchad-amd** [comment]
Duplicate - https://github.com/ROCm/HIP/issues/2115

Internal ticket has been created to resolve this issue. Thanks

**Comment by ppanchad-amd** [comment]
@r-burns https://github.com/ROCm-Developer-Tools/HIP/blob/master/INSTALL.md#hip-clang is pointing to the documentation in the master branch which is a 3+ year old branch. It is not the default branch. The default branch is https://github.com/ROCm/HIP/tree/develop
