### ISSUE TITLE
Bug in hipCabs

### ISSUE THREAD

**Issue by sukkarde** [ROCm/HIP#2232]
The following hipCabs for double-complex numbers should use sqrt instead of sqrtf:
__device__ __host__ static inline double hipCabs(hipDoubleComplex z) { return sqrtf(hipCsqabs(z)); }

**Comment by cjatin** [comment]
Thanks for highlighting the issue to us.
We have internal ticket tracking this issue. It should be fixed in future release.

**Comment by cjatin** [comment]
Fixed via: https://github.com/ROCm/clr/commit/474493b929989de947ff610aff257139766fe6b3
