### ISSUE TITLE
HIPCC not able to pass the last parameter in function

### ISSUE THREAD

**Issue by qili93** [ROCm/HIP#2236]
Using ROCM latest version ROCM 4.0.1, and reproduce code attached here, just need to run "bash build.sh"

[pool2dgrad.tar.gz](https://github.com/ROCm-Developer-Tools/HIP/files/5993996/pool2dgrad.tar.gz)

The last parameter `adaptive` value is always `const bool` of `false` defined in `main.cc`, why it changed to `true` after calling operator function in `pooling.cu`, the value of `adaptive` should always be false in both `main.cc` and `pooling.cu`. Is this a bug of hipcc or is there some mistakes in my code or cmake file?

Output as following after run `bash build.sh`:

```bash
adaptive = 0 ==> print in main.cc
adaptive = 1 ==> print in pooling.cu
```

Defined a class which has an operator function has some parameters as following in file of `pooling.h` and implementation in `pooling.cu`

```c++
template <typename PoolProcess, typename T>
class Pool2dGradFunctor {
 public:
  void operator()(const int batch_size,
                  const int input_channels,
                  const int input_height,
                  const int input_width,
                  const int output_height,
                  const int output_width,
                  const int ksize_height,
                  const int ksize_width,
                  const int stride_height,
                  const int stride_width,
                  const int padding_height,
                  const int padding_width,
                  const T* input_cpu,
                  const T* output_cpu,
                  const T* output_grad_cpu,
                  T* input_grad_cpu,
                  PoolProcess pool_process,
                  const bool exclusive, 
                  const bool adaptive);
};
```

And call this operator function in main.cc file as following.

```c++
const bool adaptive = false;
printf("adaptive = %d\n", adaptive);
Pool2dGradFunctor<AvgPoolGrad<float>, float>  pool2d_backward;
AvgPoolGrad<float> pool_process;

pool2d_backward(batch_size, input_channels, input_height, input_width, output_height, output_width,
                ksize_height, ksize_width, stride_height, stride_width, padding_height, padding_width,
                input_cpu, output_cpu, output_grad_cpu, input_grad_cpu, pool_process, exclusive, adaptive);
```

**Comment by ppanchad-amd** [comment]
@qili93 , Sorry for the lack of response. Please try latest ROCm 6.0.2 (HIP 6.0.32831) to see if your issue still exists? If resolved, please close the ticket. Thanks.
