### ISSUE TITLE
hip_stream.cpp attempts to free something it didn't allocate.

### ISSUE THREAD

**Issue by Artem-B** [ROCm/HIP#2241]
When `Device::NullStream()` is called, it calls 
https://github.com/ROCm-Developer-Tools/HIP/blob/2080cc113a2d767352b512b9d24c0620b6dee790/rocclr/hip_device.cpp#L29

hip_stream.cpp in turn does:
`Stream::Create()` -> `Stream::Delete()` -> `delete this` which attempts to free `null_stream_` which is a *field* in an instance of Device class and can not be deallocated all by itself.

https://github.com/ROCm-Developer-Tools/HIP/blob/2080cc113a2d767352b512b9d24c0620b6dee790/rocclr/hip_stream.cpp#L118

In general,  `Stream` can not assume where its memory is coming from and should not be deallocating antyhing it does not own.

**Comment by gandryey** [comment]
Thank you for reporting the issue. It will be fixed.

**Comment by ppanchad-amd** [comment]
@gandryey Is this fixed with the latest ROCm 6.1.0 (HIP 6.1)? Thanks!

**Comment by harkgill-amd** [comment]
Hi @Artem-B, this issue has been resolved as of ROCm 6.1.1, please see below. Thanks!

https://github.com/ROCm/clr/blob/develop/hipamd/src/hip_device.cpp

https://github.com/ROCm/clr/blob/develop/hipamd/src/hip_stream.cpp
