### ISSUE TITLE
Meaning of error 0x100f when launching kernel

### ISSUE THREAD

**Issue by JieyangChen7** [ROCm/HIP#2245]
I'm trying to debug a problem in VTK-m library which uses HIP via Kokkos.  I get the following error when launching a GPU kernel:
`:0:rocdevice.cpp            :2180: 19701820608 us: Device::callbackQueue aborting with status: 0x100f`

It seems that the ROCm context crashes after this error. I'm trying to find out which part of my software stack is causing the problem. It would be helpful if I can understand the meaning of the error code. Is there a document that can tell me which error code means what?

**Comment by gandryey** [comment]
Usually it occurs if scratch memory(private memory) allocation failed or there is another problem with ISA and then ROCr can't continue:
https://github.com/RadeonOpenCompute/ROCR-Runtime/blob/77589727ecc4bc715ff3f6d76dcd59f4c455b8db/src/core/runtime/amd_aql_queue.cpp#L737

0x100f - HSA_STATUS_ERROR_INVALID_ISA
https://github.com/RadeonOpenCompute/ROCR-Runtime/blob/77589727ecc4bc715ff3f6d76dcd59f4c455b8db/src/core/runtime/amd_aql_queue.cpp#L865
