### ISSUE TITLE
cuDNN and MlOpen

### ISSUE THREAD

**Issue by botev** [ROCm/HIP#305]
Given the vast overlap (almost 1 to 1 correspondence) between the two libraries, would it be considering of adding those primitive to HIP in order to have a unified interface for those as well (even if that is some form of an extension of the base HIP)?

**Comment by Delaunay** [comment]
Something like: [hipDNN][1] ? There is also [hipBLAS][2]

[1]:  https://github.com/ROCmSoftwarePlatform/hipDNN
[2]: https://github.com/ROCmSoftwarePlatform/hipBLAS

**Comment by nartmada** [comment]
@botev, apologies for the zero response.  Can you please check latest ROCm 6.0.2 (HIP 6.0.32831) and see if your query has been addressed. Thanks.

**Comment by nartmada** [comment]
Closing the ticket as it is stale and no response from @botev.
