### ISSUE TITLE
isnan data type not-supported for HCC 

### ISSUE THREAD

**Issue by sriharikarnam** [ROCm/HIP#330]
Background: Porting Mxnet Deep Learning framework to ROCm Platform

Issue : While generating 'libmxnet.so' file for HIP/ROCm platform we have faced the below compilation issue.

Error :   
On nvcc platform isnan overloaded functions supports input parameters of data types float, double and long double, but on HCC platform isnan overloaded functions supports only input parameters of data types float and double. So while compiling for HIP/ROCm we are facing compilation error while invoking isnan() with argument of data type long double.
[isnan_ticket.txt](https://github.com/ROCm-Developer-Tools/HIP/files/1642341/isnan_ticket.txt)

**Environment info:**

- Operating System: Ubunut 16.04
- Compiled the code with hipcc
- ROCm Version: 1.7.60

**Steps to reproduce the issue:**

- $git clone --recursive https://github.com/ROCmSoftwarePlatform/mxnet.git
- $git clone --recursive https://github.com/ROCmSoftwarePlatform/Thrust.git
- $cd mxnet         
- remove the NVCC flag in mxnet/src/operator/mshadow_op.h at 809
- $export HIP_PLATFORM=hcc
- $make -j(nproc)

**Comment by nartmada** [comment]
@sriharikarnam, apologies for the zero response.  Can you please check latest ROCm 6.0.2 (HIP 6.0.32831) and see if your issue has been resolved?  Thanks.

**Comment by nartmada** [comment]
Closing the ticket as it is stale and no response from @sriharikarnam.  Please re-open if you still observe the issue in latest ROCm 6.0.2 (HIP 6.0.32831).  Thanks.
