### ISSUE TITLE
How to compile a shared CUDA library?

### ISSUE THREAD

**Issue by TimDettmers** [ROCm/HIP#335]
I tried a couple of things, but I am stuck with some kind of CUDA dependency issue which I was not able to resolve. I try to make a simple shared library based on the `sample/02_Cookbook/12_cmake_hip_add_executable` example.

1. I rename the `main` function into `test`
2. I add the file `TransposeMatrix.h` which includes `int test();` and add the header to `MatrixTranspose.cpp`
3. I add the file `interface.c` which is the following:
```
  #include <MatrixTranspose.h>                                                                                                                                                                            
  extern "C"
  {
    void ftest(){ test(); }
  
  }
```
4. I change in `CMakeLists.txt` `hip_add_executable(...` to `hip_add_library(lib SHARED ...` and also add:
```
set(MY_SOURCE_FILES MatrixTranspose.cpp interface.c)
include_directories(${CMAKE_CURRENT_SOURCE_DIR})
```

I get `undefined symbol: cudaFree` errors.

1. I tried adding the CUDA include and library paths both in `include_directories(...)` and as `nvcc` options flags
2. All global paths are set correctly.

What am I doing wrong here?

**Comment by nartmada** [comment]
@TimDettmers, apologies for the lack of response.  Can you please try latest ROCm 6.0.2 (HIP 6.0.32831) to see if your issue has been resolved? Thanks.

**Comment by nartmada** [comment]
Closing this ticket as it is stale and no response from @TimDettmers.  Please re-open if you still need assistance with this ticket.  Thanks.
