### ISSUE TITLE
Linker Command Failed with Exit Code 1 while building MIOpenDriver

### ISSUE THREAD

**Issue by xx005fs** [ROCm/HIP#375]
I am having issues trying to build and install MIOpenDriver. and here is the output of the error: 

ld: /tmp/tmp.wM7w0mfIhT/main.cpp.host.o: undefined reference to symbol '_ZN5boost6system15system_categoryEv'
//usr/lib/x86_64-linux-gnu/libboost_system.so.1.58.0: error adding symbols: DSO missing from command line
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
driver/CMakeFiles/MIOpenDriver.dir/build.make:128: recipe for target 'bin/MIOpenDriver' failed
make[3]: *** [bin/MIOpenDriver] Error 1
CMakeFiles/Makefile2:3281: recipe for target 'driver/CMakeFiles/MIOpenDriver.dir/all' failed
make[2]: *** [driver/CMakeFiles/MIOpenDriver.dir/all] Error 2
CMakeFiles/Makefile2:3288: recipe for target 'driver/CMakeFiles/MIOpenDriver.dir/rule' failed
make[1]: *** [driver/CMakeFiles/MIOpenDriver.dir/rule] Error 2
Makefile:1365: recipe for target 'MIOpenDriver' failed
make: *** [MIOpenDriver] Error 2

**Comment by ppanchad-amd** [comment]
@xx005fs Apologies for the lack of response. Can you please test with latest ROCm 6.1.0 (HIP 6.1)? If resolved, please close ticket. Thanks!
