### ISSUE TITLE
Incorrect loop fusion

### ISSUE THREAD

**Issue by yige-hu** [ROCm/HIP#381]
Operating System: Ubuntu 16.04.3 LTS, Linux kernel 4.13.0
GPU: AMD RX 580
ROCm backend.
HIP version: 1.5.18073

I wanted to run a long-running kernel which took very little memory resources. So I modified the matrixTranspose kernel from /opt/rocm/hip/samples/ to the followed:
```
__global__ void matrixTranspose(hipLaunchParm lp,
                                float *out,
                                float *in,
                                const int width)
{
    int x = hipBlockDim_x * hipBlockIdx_x + hipThreadIdx_x;
    int y = hipBlockDim_y * hipBlockIdx_y + hipThreadIdx_y;

    out[y * width + x] = in[x * width + y];

    for (int j = 0; j < 10000; j++) {
        out[y * width + x] += j;
    }
    for (int j = 0; j < 10000; j++) {
        out[y * width + x] -= j;
    }
}
```

Although the kernel is not meaningful by itself, it's still not producing the transposed matrix result correctly. With a 64x64 matrix as input, I'm getting a total of 4096 elements incorrect (i.e. all elements wrong). The kernel should be equivalent to the followed two kernels, although the latter two kernels do work but the first kernel does not.

The original kernel:
```
__global__ void matrixTranspose(hipLaunchParm lp,
                                float *out,
                                float *in,
                                const int width)
{
    int x = hipBlockDim_x * hipBlockIdx_x + hipThreadIdx_x;
    int y = hipBlockDim_y * hipBlockIdx_y + hipThreadIdx_y;

    out[y * width + x] = in[x * width + y];
}
```

A equivalent one with loop fusion:
```
__global__ void matrixTranspose(hipLaunchParm lp,
                                float *out,
                                float *in,
                                const int width)
{
    int x = hipBlockDim_x * hipBlockIdx_x + hipThreadIdx_x;
    int y = hipBlockDim_y * hipBlockIdx_y + hipThreadIdx_y;

    out[y * width + x] = in[x * width + y];

    for (int j = 0; j < 10000; j++) {
        out[y * width + x] += j;
        out[y * width + x] -= j;
    }
}
```

I feel the HIPCC compiler could be doing an incorrect loop fusion optimization.

Thanks,
Yige

**Comment by ppanchad-amd** [comment]
@yige-hu Apologies for the lack of response. Can you please test with latest ROCm 6.1.0 (HIP 6.1)? If resolved, please close ticket. Thanks!
