### ISSUE TITLE
cmake error while importing HIP

### ISSUE THREAD

**Issue by schwarzschild-radius** [ROCm/HIP#527]
The following error was generated while importing the package `HIP`
```
CMake Error at /usr/local/cmake-3.11.2/Modules/CMakeFindDependencyMacro.cmake:48
 (find_package):
   By not providing "Findhcc.cmake" in CMAKE_MODULE_PATH this project has
   asked CMake to find a package configuration file provided by "hcc", but
   CMake did not find one.

   Could not find a package configuration file provided by "hcc" with any of
   the following names:

     hccConfig.cmake
     hcc-config.cmake

   Add the installation prefix of "hcc" to CMAKE_PREFIX_PATH or set "hcc_DIR"
   to a directory containing one of the above files.  If "hcc" provides a
   separate development package or SDK, be sure it has been installed.
 Call Stack (most recent call first):
   /opt/rocm/hip/lib/cmake/hip/hip-config.cmake:75 (find_dependency)
   CMakeLists.txt:4 (find_package)
```

I think it requires me to install `hcc` but my platform is `nvidia`, so I cannot install. why does it require for hcc if nvcc is present.

**Comment by gargrahul** [comment]
What is the output of hipconfig ?

**Comment by pradeepisro** [comment]
This is the output but there is a work around by commenting the `find_dependency` line in `hip-config.cmake`

```
HIP version  : 1.5.18242

== hipconfig
HIP_PATH     : /opt/rocm/hip
HIP_PLATFORM : nvcc
CPP_CONFIG   :  -D__HIP_PLATFORM_NVCC__=  -I/opt/rocm/hip/include -I/usr/local/cuda/include

== nvcc
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Mon_Jun_26_16:13:28_CDT_2017
Cuda compilation tools, release 9.0, V9.0.102

=== Environment Variables
PATH=/home/user/Softwares/ComputeCpp-CE-0.8.0-Ubuntu-16.04-x86_64/bin:/home/user/Softwares/cmake-3.11.2/bin:/opt/rocm/hip/bin:/home/user/Softwares/ninja:/usr/local/cuda-9.0/bin:/home/user/.cargo/bin:/home/user/bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64
HIP_PLATFORM=nvcc

== Linux Kernel
Hostname     : user
Linux user 4.13.0-45-generic #50~16.04.1-Ubuntu SMP Wed May 30 11:18:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
```

**Comment by pfultz2** [comment]
The `find_package(hip)` currently only supports the hcc backend, and is also only installed when using hcc, see [here](https://github.com/ROCm-Developer-Tools/HIP/blob/master/CMakeLists.txt#L284). We could provide support for nvcc with `hip::host` or `hip::device`, as well.

**Comment by pradeepisro** [comment]
Is there any plans to conditionally set platform specific flags in FindHIP.cmake? for example HIP_NVCC_FLAGS will be set even when HIP_PLATFORM is hcc

**Comment by pradeepisro** [comment]
Why `HIP_COMPILER` is set to `hcc` even in Nvidia and also why there are no HIP variables to store include directories like `HIP_INCLUDE_DIRS`?

**Comment by nartmada** [comment]
@schwarzschild-radius, apologies for the lack of response. Can you please check latest ROCm 6.0.2 (HIP 6.0.32831) to see if your query has been addressed? Thanks.

**Comment by nartmada** [comment]
Closing the ticket as it is stale.  @schwarzschild-radius, please re-open if you still need assistance with this issue.  Thanks.
