### ISSUE TITLE
Two resource-consuming kernels in different processes crash each other

### ISSUE THREAD

**Issue by vancemiller** [ROCm/HIP#556]
Concurrently running two kernels (in separate processes) that consume large amounts of device resources causes one or both kernels to crash with a memory access fault.

Example: https://gist.github.com/vancemiller/045cce72dafb0951996e3259b6f4088d

**Comment by Jorghi12** [comment]
My guess is that this is an issue inside either the kernel logic or the kernel argument preparation logic (HIP / HCC).

Can you please collect the LLVM IR & the GCN ISA dump by building with KMDUMPLLVM=1 KMDUMPISA=1?

Now, make sure to keep the runtime logs so we can see what kernel arguments are being sent from the host to device. Use these environment variables: HIP_TRACE_API=2 HCC_DB=0x48A. 

Please upload / share the logs here.

**Comment by vancemiller** [comment]
[log_concurrent_process_1_crash.txt](https://github.com/ROCm-Developer-Tools/HIP/files/2177769/log_concurrent_process_1_crash.txt)
[log_concurrent_process_2_crash.txt](https://github.com/ROCm-Developer-Tools/HIP/files/2177770/log_concurrent_process_2_crash.txt)
[log_single_process_no_crash.txt](https://github.com/ROCm-Developer-Tools/HIP/files/2177771/log_single_process_no_crash.txt)
[dump.zip](https://github.com/ROCm-Developer-Tools/HIP/files/2177773/dump.zip)

**Comment by nartmada** [comment]
@vancemiller, apologies for the lack of response.  Please try latest ROCm 6.0.2 (HIP 6.0.32831) to see if your issue has been resolved? If resolved, please close the ticket.  Thanks.
