### ISSUE TITLE
Request: hipOccupancyMaxActiveBlocksPerMultiprocessor

### ISSUE THREAD

**Issue by Jorghi12** [ROCm/HIP#567]
Hi, requesting this function hipOccupancyMaxActiveBlocksPerMultiprocessor.

https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__HIGHLEVEL.html#group__CUDART__HIGHLEVEL_1g5a5d67a3c907371559ba692195e8a38c

Thanks.

**Comment by Jorghi12** [comment]
@mangupta

**Comment by mangupta** [comment]
@Jorghi12 I had looked into implementing this sometime back. But I didn't get round to finishing it due other tasks. It is still on my plate though. I'll try and get it as soon as possible.

**Comment by Jorghi12** [comment]
@mangupta It's not urgent at the moment. But definitely a helpful performance feature.

**Comment by nartmada** [comment]
@Jorghi12, apologies for the lack of response.  Please close the ticket if the issue has been fixed.  Thank you.

**Comment by nartmada** [comment]
Closing the ticket as the issue appeared to be fixed.  Thanks.
