### ISSUE TITLE
HIP doesn't replace std math functions.

### ISSUE THREAD

**Issue by Jorghi12** [ROCm/HIP#574]
It appears that the NVCC Compiler recognizes all uses of std::abs / std::exp / etc functions within device code and replaces them with the CUDA equivalent functions. Could we have HIP do this as well?

**Comment by nartmada** [comment]
@Jorghi12, apologies for the lack of response. Can you please check latest ROCm 6.0.2 (HIP 6.0.32831) to see if your query has been addressed? Thanks.

**Comment by nartmada** [comment]
Closing this ticket as it is stale and no response from @Jorghi12.  Please re-open if you still observed this issue with latest ROCm 6.0.2 (HIP 6.0.32831).
