### ISSUE TITLE
hipcc chokes when input file is extension *.cu

### ISSUE THREAD

**Issue by BryantLam** [ROCm/HIP#605]
HIP version: 1.5.18276 (ROCm 1.8.2)

I ran hipconvertinplace-perl.sh on one source file. When running the output file through hipcc, hipcc chokes with errors that seem superfluous.

```
$ ls
source.cu

$ hipconvertinplace-perl.sh

$ ls
source.cu
source.cu.prehip

$ hipcc -o app -x c++ source.cu # "-x c++" can be omitted and the same error occurs.
... large number of errors omitted ...
/opt/rocm/lib/libhip_device.a:3:75: error: source file is not valid UTF-8
/opt/rocm/lib/libhip_device.a:3:77: warning: null character ignored [-Wnull-character]
/opt/rocm/lib/libhip_device.a:3:78: warning: null character ignored [-Wnull-character]
fatal error: too many errors emitted, stopping now [-ferror-limit=]
40 warnings and 20 errors generated.

$ ln -sfn source.cu source.hip.cpp

$ hipcc -o app source.hip.cpp
<Success>
```

**Comment by nartmada** [comment]
@BryantLam, apologies for the lack of response. Can you please check latest ROCm 6.0.2 (HIP 6.0.32831) to see if your issue has been resolved? Thanks.

**Comment by nartmada** [comment]
Closing the ticket as it is stale and no response from @BryantLam.  Please re-open if you still observe the issue with latest ROCm 6.0.2 (HIP 6.0.32831).  Thanks.
