### ISSUE TITLE
"Call from AMP-restricted function to CPU-restricted function"

### ISSUE THREAD

**Issue by tdd11235813** [ROCm/HIP#659]
-> Minimal Example ([gist](https://gist.github.com/tdd11235813/5f378d35c2de66aa56715377f405fb0b), [main.cpp.txt](https://github.com/ROCm-Developer-Tools/HIP/files/2356374/main.cpp.txt))
-> compile with:
```bash
/opt/rocm/bin/hipcc -c ../src/main.cpp -o main.cpp.o
/opt/rocm/bin/hipcc -o main main.cpp.o --amdgpu-target=gfx900
```
Error:
```
src/main.cpp:16:3: error: call from AMP-restricted function to CPU-restricted function
  f();
  ^
src/main.cpp:49:3: note: in instantiation of function template specialization 'invoke<host_only>' requested here
  invoke(host_only());
  ^
1 error generated.
Died at /opt/rocm/bin/hipcc line 565.
```

In our code we have chains of modular functions with differing host/device signatures.
nvcc will [emit a warning](https://stackoverflow.com/a/30042449) on this example above, that a device code tried to call a host code.

Is there a simple way to resolve this error for HIP(HCC) without breaking up the host-device functions?
If it is not possible to suppress this, maybe use traits for host and device signatures in a way, that the host functor is not called within the device selection of the host-device function. 

Edit: Using rocm-dev package from repo.radeon.com for Ubuntu 16.04.5 LTS
```
$ hcc --version
HCC clang version 7.0.0 (ssh://gerritgit/compute/ec/hcc-tot/clang 86791fc4961dc8ffde77bde20d7dfa5e5cbeff5e) (ssh://gerritgit/compute/ec/hcc-tot/llvm c1f9263485c0192d7af512ac2c7dd15d5082538e) (based on HCC 1.2.18272-47899bc-86791fc-c1f9263 )
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/bin

$ hcc-config --cxxflags
 -hc -std=c++amp -I/opt/rocm/hcc/include
```

**Comment by psychocoderHPC** [comment]
Is there any progress on this issue? It is a strong requirement to build platform independent code that we can build meta functions which we can later use from host and from the device.

**Comment by tdd11235813** [comment]
using the (internal in-dev) hip-clang version I tried it again. In the MWE code from above I **changed** only the kernel call to:
```
kernel<<<dim3(1),dim3(1)>>>();
```
Then it compiled, but the printf() is not executed on device (not sure, if already supported at all, but compiler did not throw an error).

```bash
$ hipcc --version
HIP version: 1.5.19284
clang version 10.0.0 (https://github.com/RadeonOpenCompute/clang 34a07b2c8a5397b2c5607eb8425bfc1f5ab5e69a) (https://github.com/RadeonOpenCompute/llvm.git 5cb249065ec697855c714268fea8f01d34b3b660)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/llvm/bin

$ export HIP_PLATFORM="clang"
$ export HIP_CLANG_PATH=/opt/rocm/llvm/bin
$ export DEVICE_LIB_PATH=/opt/rocm/lib
$ /opt/rocm/hip-clang/bin/hipcc -c main.cpp -o main.cpp.o
$ /opt/rocm/hip-clang/bin/hipcc -o main main.cpp.o --amdgpu-target=gfx900
```
rocprof showed me a device context, but kernel had no name.
```
$ rocprof ./main
$ less results.csv
 Index,KernelName,gpu-id,queue-id,queue-index,tid,grd,wgr,lds,scr,vgpr,sgpr,fbar,sig
 0,"",0,0,0,124533,1,1,0,0,0,0,0,0x7fe07f5dc680

**Comment by dmcdougall** [comment]
@psychocoderHPC We met at the CAAR Kickoff Workshop in Knoxville.

I'll interface with the engineering team on this and get back to you.

**Comment by dmcdougall** [comment]
A colleague verifies that this is fixed with hip-clang.  Perhaps we'll keep this ticket open until hip-clang starts shipping with ROCm.  Is that reasonable?

The issue with printf is a separate problem that is also being addressed.

**Comment by tdd11235813** [comment]
that's good, thank you! Meanwhile we also compiled successfully the backend part of our infrastructure without the need of the former workaround that was required for HCC. Still testing, but hip-clang looks good so far, good job!

**Comment by dmcdougall** [comment]
Cool.  That's good feedback.  Thanks.

**Comment by psychocoderHPC** [comment]
> A colleague verifies that this is fixed with hip-clang. Perhaps we'll keep this ticket open until hip-clang starts shipping with ROCm. Is that reasonable?
> 
> The issue with printf is a separate problem that is also being addressed.

Thanks for pushing this issues. 
Looks like HIP-clang will make us the life much easier.

**Comment by ppanchad-amd** [comment]
@tdd11235813 Is this ticket still relevant? If not, please close. Thanks!

**Comment by psychocoderHPC** [comment]
@ppanchad-amd @tdd11235813 is not working on this topic anymore but from our side this ticket can be closed.
