### ISSUE TITLE
Indefinite kernel hang on ROCm 1.9.211 for MXNet HIP Port on VEGA10

### ISSUE THREAD

**Issue by sriharikarnam** [ROCm/HIP#704]
**Issue:**
Indefinite kernel hang issue is observed on executing the mxnet training application on VEGA10 gpu.

**Environment info:**
- Operating System: Ubunut 16.04

- ROCm version:
$ dpkg -s rocm-dkms
Package: rocm-dkms
Status: install ok installed
Priority: optional
Section: devel
Installed-Size: 1
Maintainer: Advanced Micro Devices Inc.
Architecture: amd64
Version: 1.9.211
Depends: rocm-dev, rock-dkms
Description: Radeon Open Compute (ROCm) Runtime software stack
Homepage: https://github.com/RadeonOpenCompute/ROCm

- HIP environment details:
  $ hipconfig --full
  HIP version  : 1.5.18353

  == hipconfig
  HIP_PATH     : /opt/rocm
  HIP_PLATFORM : hcc
  CPP_CONFIG   :  -D__HIP_PLATFORM_HCC__=   -I/opt/rocm/include -I/opt/rocm/hcc/include

  == hcc
  HSA_PATH     : /opt/rocm/hsa
  HCC_HOME     : /opt/rocm/hcc
  HCC clang version 7.0.0 (ssh://gerritgit/compute/ec/hcc-tot/clang                                                                  e2b51bfd063e4ccd426b64290bdc1587f2bf855a) (ssh://gerritgit/compute/ec/hcc-tot/llvm   009cb63e6e67f60303e7b11642113db848619871) (based on HCC 1.2.18354-ec91fed-e2b51bf-009cb63 )
  Target: x86_64-unknown-linux-gnu
  Thread model: posix
  InstalledDir: /opt/rocm/hcc/bin
  LLVM (http://llvm.org/):
    LLVM version 7.0.0svn
    Optimized build.
    Default target: x86_64-unknown-linux-gnu
    Host CPU: broadwell

  Registered Targets:
    amdgcn - AMD GCN GPUs
    r600   - AMD GPUs HD2XXX-HD6XXX
    x86    - 32-bit X86: Pentium-Pro and above
    x86-64 - 64-bit X86: EM64T and AMD64
  HCC-cxxflags :  -hc -std=c++amp -I/opt/rocm/hcc/include -I/opt/rocm/includeHCC-ldflags  :  -hc   -std=c++amp -L/opt/rocm/hcc/lib -Wl,--rpath=/opt/rocm/hcc/lib -ldl -lm -lpthread -lhc_am -Wl,--whole-archive -lmcwamp -Wl,--no-whole-archive

**Analysis**
On executing the application on GPU it hangs at the kernel,
<<hip-api tid:1.115 1.115 hipLaunchKernel '_ZN5mxnet2op8mxnet_op20mxnet_generic_kernelINS1_11op_with_reqINS1_10set_to_intILi0EEELi1EEEJPfEEEviDpT0_' gridDim:{1024,1,1} groupDim:{256,1,1} sharedMem:+0 stream:0.1 @791653796943586

We have tried to execute the application by exporting HSA_ENABLE_SDMA=0 but the issue still persists.
 
**Steps to Reproduce**

- $ git clone --recursive -b downstream_27Mar2018 --single-branch https://github.com/ROCmSoftwarePlatform/mxnet.git
- $ cd mxnet
- $ export HIP_PLATFORM=hcc
- $ make -jn (n = no of cores)
- $ cd python
- $ sudo python setup.py install
- $ cd ../example/adversary
- $ python adversary_generation.py
    NOTE: to run on cpu modify code as mx.cpu() and to run on gpu modify code as mx.gpu().

Please suggest to identify the cause which might lead to indefinite hang of the kernel.

**Comment by nartmada** [comment]
@sriharikarnam, apologies for the lack of response.  Do you still see the issue in a more recent ROCm version?  Thanks.

**Comment by nartmada** [comment]
Closing the ticket as it is stale.  @sriharikarnam, please re-open if you still need assistance with this issue.  Thanks.
