### ISSUE TITLE
Support hipIpcOpenEventHandle and hipIpcGetEventHandle?

### ISSUE THREAD

**Issue by byujiang** [ROCm/HIP#728]
We are porting a cuda library `quda` to ROCm platform, in which  `hipIpcOpenEventHandle` and `hipIpcGetEventHandle` are used. However I did not find any useful message about them. Does HIP support the two runtime functions for hcc or be planning to support?

**Comment by gargrahul** [comment]
@darkshell Yes, support for these APIs is being worked on and should be available soon. Though I won't be able to confirm currently by when.

**Comment by leofang** [comment]
Is this issue fixed? I found both `hipIpcOpenEventHandle ` and `hipIpcGetEventHandle ` are now listed in the mapping:
https://rocmdocs.amd.com/en/latest/Programming_Guides/CUDAAPIHIPTEXTURE.html#device-management

**Comment by leofang** [comment]
Turns out that https://github.com/ROCm-Developer-Tools/HIP/pull/1996 added support for this, but it is not yet released (as of ROCm 3.5.0).

**Comment by nartmada** [comment]
@byujiang, apologies for the lack of response. Can you please check latest ROCm 6.0.2 (HIP 6.0.32831) to see if your query has been addressed? Thanks.
