### ISSUE TITLE
__HIP_ARCH_GFXnnn__ macros aren’t evaluated individually for each target pass

### ISSUE THREAD

**Issue by 949f45ac** [ROCm/HIP#754]
So, a given kernel is compiled seperately for every arch. When you set `KMDUMPISA=1` you can see the different outputs.

Suppose I want to have a piece of code one way on one arch, another way on another arch. A simple example: Maybe I want to issue a `global_load` instruction on gfx900, but on gfx803 I can only use `flat_load`.

So I figure that I could use the arch macros for that.
```c++
#if __HIP_ARCH_GFX900__
asm ("global_load .....");
#else
asm ("flat_load .....");
#endif
```

The problem is that when I compile with _both_ targets present, `__HIP_ARCH_GFX900__` always evaluates to true, even when the kernel code for gfx803 is being generated. Obviously this makes compilation fail. Or I can do it the other way around, test for `__HIP_ARCH_GFX803__` first: Then compilation succeeds, but gfx900 uses flat_load instructions too.

Is there a way around this? Maybe another set of macros exists?
Or is what I want not possible, because the compilation pipeline is ordered in such a way that HIP_ARCH macros are swallowed before the final ISA is generated?

**Comment by ex-rzr** [comment]
Here is a connected issue: https://github.com/RadeonOpenCompute/hcc/issues/714
As far as I know that this feature is not yet implemented and the only way is to have separate binaries for every arch.

**Comment by nartmada** [comment]
@949f45ac, apologies for the lack of response. Can you please check latest ROCm 6.0.2 (HIP 6.0.32831) to see if your query has been addressed? Thanks.

**Comment by nartmada** [comment]
Closing the ticket as it is stale.  @949f45ac, please re-open if you still need assistance with the issue.  Thanks.
