### ISSUE TITLE
Invalid cast (Producer: 'LLVM7.0.0svn' Reader: 'LLVM 7.0.0svn')

### ISSUE THREAD

**Issue by leimingyu** [ROCm/HIP#771]
Hello,
  When I tried to convert a cuda file to a hipified code using the following command, it reported an error without any additional information. 
```bash
hipcc -g -c -DHIP_FAST_MATH -Wall -fopenmp -m64 -DUSE_ATOMIC -DSAVE_DETECTORS -DUSE_CACHEBOX  -DUSE_XORSHIFT128P_RAND  -I/opt/rocm/hip/include   -o mcx_core.o  mcx_core.cu
```

The error is shown below.
```bash
error: Invalid cast (Producer: 'LLVM7.0.0svn' Reader: 'LLVM 7.0.0svn')
1 error generated.
```
   Any suggestions to debug this issue? Thanks in advance.

**Comment by mangupta** [comment]
hipcc is used for compiling hipified code. You need to use hipify-perl or hipify-clang to covert cuda source to hipified code.

**Comment by 3upperm2n** [comment]
@mangupta Is there a way to use "verbose" option to hipcc for debugging?

**Comment by mangupta** [comment]
See https://github.com/ROCm-Developer-Tools/HIP/blob/master/docs/markdown/hip_porting_guide.md#debugging-hipcc. You can more verbose information by increasing the value from 1 to 3 or 7.

**Comment by nartmada** [comment]
@leimingyu, apologies for the lack of response.  Can you please check latest ROCm 6.0.2 (HIP 6.0.32831) to see if your issue has been resolved? Thanks.

**Comment by nartmada** [comment]
Closing the ticket as it is stale.  @leimingyu, please re-open if your issue still exists in latest ROCm 6.0.2 (HIP 6.0.32831).  Thanks.
