### ISSUE TITLE
Sample square aborts without any useful message

### ISSUE THREAD

**Issue by baryluk** [ROCm/HIP#795]
```
user@debian:~/HIP/samples/0_Intro/square$ ./square.out 
terminate called after throwing an instance of 'ihipException'
  what():  std::exception
Aborted
```

That is not useful at all. Please improve error handling and messages, the point of these sample is to verify that the HIP is working, and rest of stuff is working too. Without some kind of message what went wrong, it is not helpful.

sample from git master repo.

**Comment by mangupta** [comment]
In addition to the above, running ```hipconfig --full``` might throw light on if HIP finds a valid ROCm/CUDA platform. Also when running on ROCm platform you could also turn on [HIP tracing](https://github.com/ROCm-Developer-Tools/HIP/blob/master/docs/markdown/hip_porting_guide.md#hiptrace-mode) to see what is happening inside any HIP application.

**Comment by baryluk** [comment]
Hi. Yes rocminfo works and looks to be showing everything fine.

I can debug it of course, but I was hoping, that `square.out` does know what is wrong, and maybe show more than just ihipException. Is there some error message attached to the exception?

**Comment by baryluk** [comment]
BTW. My bug report is not about fixing my installation of HIP, it is about handling and reporting of errors in square sample itself. I am sure I can figure it out and make it work, but programs that you are likely going to use to test your setup, ending abruptly without any help, are really bad for a start.

PS. For no reasons at all, I reinstalled system, installed libtinfo5 , rocminfo,  hip_samples , hip_hcc and I think hsa-rocm-dev , and it started working.

**Comment by baryluk** [comment]
I will try to reproduce the problem again, but not it is elusive.

**Comment by nartmada** [comment]
@baryluk, apologies for the lack of response from AMD.  Do you still need assistance with this issue?

**Comment by baryluk** [comment]
I cannot even test, because rocm is completely broken currently.

**Comment by nartmada** [comment]
Please share your GPU, OS, and ROCm version so that we can try to repro your issue.  Thanks.

**Comment by harkgill-amd** [comment]
Hi @baryluk, I am unable to reproduce this issue with ROCm 6.1.2. In regard to the error handling and messages, please see @jlgreathouse's response above.

If you are still encountering any issues with the square sample test, please report them in the hip-tests repository [here](https://github.com/ROCm/hip-tests/issues). Thanks!
