### ISSUE TITLE
hip_samples debian packages should also depend on cxlactivitylogger and rocm-profiler package

### ISSUE THREAD

**Issue by baryluk** [ROCm/HIP#805]
"Profiler" example in Cookbook depends on it:

```
root@debian:/opt/rocm/hip/samples/2_Cookbook/2_Profiler# make
/opt/rocm/hip/bin/hipcc -g     -c -o MatrixTranspose.o MatrixTranspose.cpp
In file included from MatrixTranspose.cpp:27:
/opt/rocm/hip/include/hip/hip_profile.h:31:10: fatal error: 'CXLActivityLogger.h' file not found
#include <CXLActivityLogger.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
In file included from MatrixTranspose.cpp:27:
/opt/rocm/hip/include/hip/hip_profile.h:31:10: fatal error: 'CXLActivityLogger.h' file not found
#include <CXLActivityLogger.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
/opt/rocm/hip/bin/hipcc MatrixTranspose.o -o MatrixTranspose
clang-7: error: no such file or directory: 'MatrixTranspose.o'
/opt/rocm/bin/rocm-profiler -A -o MT.atp -e HIP_PROFILE_API=1 ./MatrixTranspose
make: /opt/rocm/bin/rocm-profiler: Command not found
make: *** [Makefile:34: profile] Error 127
```

Installing `cxlactivitylogger` and `rocm-profiler` packages resolves the problem.

(and probably also `cmake`, for cmake example, or at least add a `Suggests: cmake` to a package metadata).

**Comment by nartmada** [comment]
@baryluk, apologies for the lack of response.  Do you still need assistance with this ticket?  Thanks.

**Comment by baryluk** [comment]
I think you do not understand why I am reporting issues.

I am not asking for you to assist me with anything. I am fully capable of assisting myself. And bug reports are not to seek assistance. (there are forums, mailing lists, and other channels for this).

I am filling bugs, because rocm and hip are broken, and I am trying to assist you with make this code better.

And yes, it is still broken.

**Comment by harkgill-amd** [comment]
Hi @baryluk, the Profiler example in the Cookbook has since been removed. I will close this ticket as it is no longer relevant.

You can find the updated list of sample tests at [ROCm/hip-tests](https://github.com/ROCm/hip-tests). Thanks!
