### ISSUE TITLE
Excessive warnings in 11_texture_driver example. hipcc --genco broken?

### ISSUE THREAD

**Issue by baryluk** [ROCm/HIP#806]
```
root@debian:/opt/rocm/hip/samples/2_Cookbook/11_texture_driver# make
/opt/rocm/hip/bin/hipcc  --genco   tex2dKernel.cpp -o tex2dKernel.code
clang-7: warning: -amdgpu-target argument 'gfx801' is not recognized; using gfx803 instead [-Winvalid-command-line-argument]
clang-7: warning: -amdgpu-target argument 'gfx802' is not recognized; using gfx803 instead [-Winvalid-command-line-argument]
clang-7: warning: argument unused during compilation: '-shared' [-Wunused-command-line-argument]
objdump: /usr/lib/x86_64-linux-gnu/libm.a: file format not recognized
/opt/rocm/hip/bin/hipcc  texture2dDrv.cpp -o texture2dDrv.out
objdump: /usr/lib/x86_64-linux-gnu/libm.a: file format not recognized
#
```

Also this appears to be the only sample, that is not following template of other samples, by making make by default do `all`, which is to build an executable, and then do a `test` target, that executes executable. Deviation from pattern is weird.

No idea which clang it is using, but I think the correct one, because when I run `strace` on it, it only accesses clang stuff in /opt

```
root@debian:/opt/rocm/hip/samples/2_Cookbook/11_texture_driver# /opt/rocm/hip/bin/hipcc  --genco   tex2dKernel.cpp -o tex2dKernel.code
clang-7: warning: -amdgpu-target argument 'gfx801' is not recognized; using gfx803 instead [-Winvalid-command-line-argument]
clang-7: warning: -amdgpu-target argument 'gfx802' is not recognized; using gfx803 instead [-Winvalid-command-line-argument]
clang-7: warning: argument unused during compilation: '-shared' [-Wunused-command-line-argument]
objdump: /usr/lib/x86_64-linux-gnu/libm.a: file format not recognized
#
```

This warning doesn't show when I compile other samples, so I am assuming this have something to do with `--genco` flag, which obviously is not documented:

```
# /opt/rocm/hip/bin/hipcc --help | grep -i genco
<empty>
#
```

**Comment by nartmada** [comment]
@baryluk, apologies for the lack of response from AMD.  Do you still need assistance with this ticket?  Thanks.

**Comment by baryluk** [comment]
I do not know. I am not able to install rocm on my system due to dependency issues.

**Comment by nartmada** [comment]
Please share your GPU, OS, and ROCm version so that we can try to repro your issue.  Thanks.

**Comment by baryluk** [comment]
Everything is in the initial bug report. The GPU, OS version does not matter, as it is bug about build, not execution.

Version I do not remember now. The one that was available on Dec 13, 2018.

You can retry on the latest version, as there is no point of chassing repro in rocm from 2018.

Also, responding after 6 years, yeah. I do not know how I feel about this.

**Comment by nartmada** [comment]
I know... Sorry :(
Just cleaning up neglected tickets.  For due diligence, I will ask one of my guys to confirm with latest version.

**Comment by baryluk** [comment]
Please close. I see all the examples moved to a different repo.

I also sent a pull request in that repo, that fixes all build issues (for all examples). I really hope somebody takes a look at it and merges it.

**Comment by nartmada** [comment]
> Please close. I see all the examples moved to a different repo.
> 
> I also sent a pull request in that repo, that fixes all build issues (for all examples). I really hope somebody takes a look at it and merges it.

Hi @baryluk, please share the PR.  Thanks.
