### ISSUE TITLE
hipBusBandwidth and hipInfo make default target `all` should not do `install`

### ISSUE THREAD

**Issue by baryluk** [ROCm/HIP#807]
In `/opt/rocm/hip/samples/1_Utils/hipBusBandwidth/Makefile` and in `/opt/rocm/hip/samples/1_Utils/hipInfo/Makefile`:

```makefile
all: install
```

it should be

```makefile
all: $(EXE)
```

instead in both makefiles.

Also in `install` target, `cp` shouldn't not be used, but `install` binary (`/usr/bin/install`).

Thanks.

**Comment by harkgill-amd** [comment]
Hi @baryluk, the sample tests have been moved from the ROCm/HIP repo to ROCm/hip-tests. They all now use CMake rather than hardcoded Makefiles. Please report any issues with the sample tests [here](https://github.com/ROCm/hip-tests/issues). Thanks!
