### ISSUE TITLE
hipCommander examples are broken.

### ISSUE THREAD

**Issue by baryluk** [ROCm/HIP#808]
```
root@debian:/opt/rocm/hip/samples/1_Utils/hipCommander# ./hipCommander -v -f c.cmd 
Device:Fiji [Radeon R9 FURY / NANO Series] Mem=4.0GB #CUs=64 Freq=1050Mhz
error: Bad command 'loop,1000
error: assertion 0 at hipCommander.cpp:885: bad command in command-stream

Aborted
root@debian:/opt/rocm/hip/samples/1_Utils/hipCommander# ./hipCommander -v -f classic.cmd 
Device:Fiji [Radeon R9 FURY / NANO Series] Mem=4.0GB #CUs=64 Freq=1050Mhz
error: Bad command 'nullkernel,d2h,streamsync
error: assertion 0 at hipCommander.cpp:885: bad command in co mmand-stream

Aborted
#
```

and in many other files.

Some of the command files in `perf/` subdirectory work.

`latency2.hcm` for example works.

I am guessing this is because the format of commands is different.

`loop,1000;` (not working) vs `loop(1000)` (working).

And similar for streams.

Also there appears to be missing semicolons in various .cmd / .hcm files.

**Comment by nartmada** [comment]
@baryluk, apologies for the lack of response from AMD.  Do you still need assistance with this issue?  Thanks.

**Comment by harkgill-amd** [comment]
Hi @baryluk, the hipCommander sample test is no longer in use. The latest sample tests can be found at [ROCm/hip-tests](https://github.com/ROCm/hip-tests). Thanks!
