### ISSUE TITLE
No device code available for function (with tests and workarounds)

### ISSUE THREAD

**Issue by ex-rzr** [ROCm/HIP#874]
Here is a test case: https://gist.github.com/ex-rzr/d433b3c24db28761d11bc5c3ab09d247

```sh
hipcc -o no_device_code no_device_code.cpp && ./no_device_code
```

There are universal functions that must work on host an device. On device they write to memory directly, on host they launch a kernel. But the program fails to run on host:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  No device code available for function: _Z6kernelIiEvPT_
Aborted (core dumped)
```
And indeed, the binary does not contain the kernel.

I don't know internals of the compiler but suspect that for some reason the compiler looks at `__device__` functions and decides that the kernel is not used, even if it is used in `__host__` versions of the functions (i.e. it looks like the compiler overwrites dependencies of `__host__` functions with dependencies of `__device__` functions).

The workaround is to create dependencies in `__device__` functions artificially.

There are two test cases:
CASE 1 is simple and requires WORKAROUND 1 only.
CASE 2 is requires both WORKAROUND 1 and WORKAROUND 2, because we need to create a "chain" of dependencies every time when device function does not call the function called by host (this function or its callees launches kernel).

This approach with universal functions is widely used in Thrust. And sometimes it requires to add multiple workarounds because there may be a few levels from the public function to inner functions which launch kernels.

**Comment by AlexVlx** [comment]
This is all fine and good but ill-formed. At the moment you cannot call `hipLaunchKernelGGL` (this is purely `__host__` restricted) in a `__device__` context, or from a `__global__` function. `__host__ __device__` functions are not disjunctive, i.e. the body of a doubly restricted function must meet the union of restrictions. You can overload on restriction, i.e. have a `__host__` and a `__device__` version. It's highly unlikely that Thrust actually uses this idiom (which does not meet the CUDA spec either, observe https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#host).

**Comment by ex-rzr** [comment]
I'm not sure that I'm following.

> At the moment you cannot call `hipLaunchKernelGGL` (this is purely `__host__` restricted) in a `__device__` context, or from a `__global__` function.

Yes, I know, but I'm not calling the kernel from device functions.

> `__host__ __device__` functions are not disjunctive, i.e. the body of a doubly restricted function must meet the union of restrictions

Then there is a contradiction.

The CUDA spec says:
>  The `__device__` and `__host__` execution space specifiers can be used together however, in which case the function is compiled for both the host and the device. The `__CUDA_ARCH__` macro introduced in Application Compatibility can be used to differentiate code paths between host and device: 

```cpp
__host__ __device__ func()
{
#if __CUDA_ARCH__ >= 600
   // Device code path for compute capability 6.x
#elif __CUDA_ARCH__ >= 500
   // Device code path for compute capability 5.x
#elif __CUDA_ARCH__ >= 300
   // Device code path for compute capability 3.x
#elif __CUDA_ARCH__ >= 200
   // Device code path for compute capability 2.x
#elif !defined(__CUDA_ARCH__) 
   // Host code path
#endif 
}
```

I assume that this code is well-formed in both CUDA and HIP:
```cpp
__host__ __device__
void foo(x)
{
#if device code
 ... __fsqrt_rd(x) ...
#else
 ... std::sqrt(x) ...
#endif
}
```
Isn't it?

If it's well-formed then how does it differ from this?

```cpp
__host__ __device__
void foo(y)
{
#if device code
 ... *y = 123; ...
#else
 ... hipLaunchKernelGGL(..., y, ...)
#endif
}
```

This is exactly what is happening in Thrust's case (and in my example).

**Comment by AlexVlx** [comment]
There is no contradiction, a `__host__ __device__` function must use only the intersection of supported features. The macro guards with `__CUDA_ARCH__` are there precisely for that. Having said that, I did misread what your example was showing, apologies. Thank you for reporting this.

**Comment by saadrahim** [comment]
@ex-rzr Can you point out what line in Thrust has __host__ __device__ with a kernel launch?

**Comment by yxsamliu** [comment]
The template device is only instantiated in host compilation. In device compilation it is conditioned out, that's why the kernel cannot be found in device binary.

if you separate the line of

... hipLaunchKernelGGL(..., y, ...)

to a host function. Then both device and host compilation see the template instantiation, the kernel will be found in device binary.

**Comment by ppanchad-amd** [comment]
@ex-rzr Do you still require assistance with this issue? If not, please close ticket. Thanks!
