### ISSUE TITLE
Request: implement hipOccupancyMaxPotentialBlockSize for AMD GPUs

### ISSUE THREAD

**Issue by kingcrimsontianyu** [ROCm/HIP#924]
Occupancy calculator API is an invaluable asset in CUDA. Unfortunately `hipOccupancyMaxPotentialBlockSize` is only exposed to Nvidia GPUs for the time being. It would be immensely helpful if it is implemented for AMD GPUs.

**Comment by whchung** [comment]
Second to this request.

**Comment by whchung** [comment]
relevant code in TensorFlow:

https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/tensorflow/core/util/gpu_launch_config.h#L165

Without this function implemented in HIP the grid / block size selection on AMD hardware would always be sub-optimal.

**Comment by jeffdaily** [comment]
I think this can be closed as of ROCm 2.7?  
https://github.com/ROCm-Developer-Tools/HIP/blob/854768787ee9bbd6ed22b3e8fd0f139955a57e6a/src/hip_module.cpp#L1015

**Comment by jedbrown** [comment]
The HIP implementation is not comparable to the corresponding CUDA function, which takes [a function](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__TYPES.html#group__CUDA__TYPES_1g6cb31f1273726f5567051e3e21607a45) so that the dynamic shared memory can be a function of the block size.

![image](https://user-images.githubusercontent.com/3303/153775697-38f88ffb-336a-45e8-8d26-69853eff0fb0.png)

Cc: @nbeams

**Comment by nbeams** [comment]
I would further clarify that we would like a HIP version for the driver API function `cuOccupancyMaxPotentialBlockSize`, which I believe corresponds to `cudaOccupancyMaxPotentialBlockSizeVariableSMem` in the runtime API.

**Comment by jedbrown** [comment]
I see this was left as a TODO in https://github.com/ROCm-Developer-Tools/HIP/pull/1943/files#diff-9ec4991aeca8528b60eaf6d00b089eecda171d49742e348561c957c5fa2000feR1328-R1342

@gargrahul Can you suggest a workaround?

**Comment by 0x0015** [comment]
Hello, I was wondering if this is still being worked on?  It's been 2 years since last update here, and unless I have pretty bad user error, it's still not working (somehow breaking calls that occur before I even call it)

**Comment by ppanchad-amd** [comment]
@kingcrimsontianyu @0x0015 Please test with latest ROCm 6.1.0 (HIP 6.1)? Thanks!

**Comment by ppanchad-amd** [comment]
@0x0015 Have you tried with the latest ROCm 6.1.2? Thanks!

**Comment by zichguan-amd** [comment]
Hi @0x0015, [hipOccupancyMaxPotentialBlockSizeVariableSMem](https://github.com/ROCm/HIP/blob/rocm-6.2.2/include/hip/hip_runtime_api.h#L8804) and [hipOccupancyMaxPotentialBlockSizeVariableSMemWithFlags](https://github.com/ROCm/HIP/blob/rocm-6.2.2/include/hip/hip_runtime_api.h#L8692) are available in latest version of ROCm. Please let me know if that's what you are looking for.
