### ISSUE TITLE
Use of __any in branching code gives wrong result

### ISSUE THREAD

**Issue by kingcrimsontianyu** [ROCm/HIP#952]
The following toy code returns wrong result, where all data in array `c` are 1, instead of 0-1 alternatively. The code works correctly on Nvidia GPU with `int dimBlock = 32;`

Does it mean `__any()` cannot be used in branching code in hip/hcc at the moment, or did I missing anything? Thanks for any pointer.

Update: Is it possible to implement `__any_sync(__activemask(), pred)` in hip/hcc?

```
#include "hip/hip_runtime.h"
#include <cstdlib>
#include <cstdio>
#include <iostream>
#include <vector>



//------------------------------------------------------------
//------------------------------------------------------------
__global__ void TestKernel(int* c)
{
    if(hipThreadIdx_x % 2 == 0)
    {
        int x = 1;
        c[hipThreadIdx_x] = __any(x);
    }
    else
    {
        int y = 0;
        c[hipThreadIdx_x] = __any(y);
    }
}

//------------------------------------------------------------
//------------------------------------------------------------
int main(int, char**)
{
    hipSetDevice(0);

    int dimGrid = 1;
    int dimBlock = 64;
    int numThread = dimGrid * dimBlock;

    std::vector<int> c_h(numThread);
    int* c;

    hipMalloc(&c, sizeof(int) * numThread);

    hipLaunchKernelGGL(TestKernel, dim3(dimGrid), dim3(dimBlock), 0, 0, c);
    hipDeviceSynchronize();

    hipMemcpy(c_h.data(), c, sizeof(int) * numThread, hipMemcpyDeviceToHost);

    for(auto&& item : c_h)
    {
        std::cout << item << std::endl;
    }

    hipFree(c);
    return 0;
}
```

**Comment by b-sumner** [comment]
Thanks for the report.  We'll take a look.

**Comment by kingcrimsontianyu** [comment]
More info:

Both hip and hc have `__any(pred)` function that calls `__ockl_wfany_i32(pred)`. hc's header file has detailed comment: Evaluate predicate for all _**active work-items**_ in the wavefront and return non-zero if and only if predicate evaluates to non-zero for any of them.

In other words, `__any(pred)` in hc/hip is supposed to work like `__any_sync(__activemask(), pred)` in CUDA, only accounting for active threads. So the problem observed is likely caused by a compiler bug.

**Comment by kingcrimsontianyu** [comment]
Update: This issue still exists in rocm version 2.2.31

**Comment by ipe-zhangyz** [comment]
This issue still exits in rocm 2.9.6, but the kernel below  gives the right results:
__global__ void TestKernel(int* c)
{
    int x, y;
    if(hipThreadIdx_x % 2 == 0)
    {
        x = 1;
    }
    else
    {
        y = 0;
    }
    c[hipThreadIdx_x] = __any(x);
    if(hipThreadIdx_x % 2 == 1)
       c[hipThreadIdx_x] = __any(y);
}

**Comment by nartmada** [comment]
Hi @kingcrimsontianyu, apologies for the lack of response.  Can you please check latest ROCm 6.0.2 (HIP 6.0.32831) to see if your issue has been fixed? Thanks.

**Comment by nwolfey21** [comment]
Tested and confirmed working (alternating 0,1 output) with ROCm 6.0.2 on MI210

**Comment by nartmada** [comment]
Thank you @nwolfey21.  I will close the ticket now.
