### ISSUE TITLE
[HIP] missing hipDevAttrTextureAlignment in hipDeviceAttribute_t

### ISSUE THREAD

**Issue by zjunweihit** [ROCm/HIP#960]
When I try to hipify a HPC application, there is no hipDevAttrTextureAlignment comparing to CUDA.
refer to:
  * https://rocm-documentation.readthedocs.io/en/latest/Programming_Guides/CUDAAPIHIPTEXTURE.html#data-types

Is there any alternative way to support it? or any plan about it?
Thanks.

**Comment by nartmada** [comment]
@zjunweihit, apologies for the lack of response from AMD.  Do you still need assistance with this issue?  Thanks.

**Comment by nartmada** [comment]
Closing this ticket as it is stale.  @zjunweihit, please re-open if you still see this issue with latest ROCm 6.0.2 (HIP 6.0.32831).  Thanks.
