### ISSUE TITLE
Can I use g++ or mpic++ to link the hipcc object?

### ISSUE THREAD

**Issue by holyprince** [ROCm/HIP#988]
Before I want to use hipcc to link object together but I meet the LLVM problem #979 . So I change the ld to mpic++ and including the hip library (my program is MPI program). Through this, the LLVM problem solved and can link successfully, but when I running the executable file, the following error appears:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  No device code available for function: _Z10hip_normalv
Aborted
```
and I add a simple test program to show the error:
```c++
#include<stdio.h>
#include <hip/hip_runtime.h>
#define BLOCK_SIZE 64
__global__  void hip_normal()
{

}
int main(int argc, char *argv[])
{
    hipLaunchKernel(hip_normal,10,10,0,0);
    return 0;
}
```
I use hipcc, the running result is normal:
```
hipcc -c main.cpp -o main.o  [compile]
hipcc main.o -o Main [link]
./Main  [running]
```
But I use g++ to link: 
```
hipcc -c main.cpp -o main.o   [compile]
g++ -L/opt/rocm/lib  -lhip_hcc main.o -o Main [link]
./Main [running]
```
Running error appeared :
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  No device code available for function: _Z10hip_normalv
Aborted

```

So I want to ask the behavior using mpic++ or g++ to link is wrong or not even if I add the hip_hcc library? 
Thank you very much!

**Comment by louishp** [comment]
Add -fno-gpu-rdc to hipcc when you compile main.cpp and link with g++ o mpic++.

**Comment by holyprince** [comment]
@louishp , thank you for your reply, but when I add -fno-gpu-rdc to hipcc the error appears:

**clang-7: error: unknown argument: '-fno-gpu-rdc'**

and I use hipcc --help do not find the option in the list. The fllowing is my hipcc version info.
```
$ hipcc --version
HIP version: 1.5.18353
HCC clang version 7.0.0 (...) (...) (based on HCC 1.2.18354-ec91fed-e2b51bf-009cb63 )
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/hcc/bin
```

**Comment by whchung** [comment]
The feature is in ROCm 2.1+ if I understand correctly. You might want to upgrade your ROCm stack to have newer HCC with that flag.

**Comment by anilbommareddy** [comment]
I tested with  a sample code(example.cpp) with hipcc and mixed compile & link(Hipcc and g++)
Case1:
The sample code compile and link with hipcc and the time taken kernel call(add) is "18371NS"

Compile & Link:-hipcc

hipcc -c example.cpp.cpp -o main.o  [compile]
hipcc main.o -o Main [link]
./Main  [running]

rocprof :
Name						Calls	TotalDurationNs	AverageNs	Percentage
void add<int>(int*, int*)	1			18371		18371		100


Case2:

The sample code compile hipcc and link with g++ and the time taken  kernel call (add) is "18520Ns"

Compile(hipcc) & link(g++)
hipcc -c -fno-gpu-rdc example.cpp -o main.o   [compile]
g++ -L/opt/rocm/lib  -lhip_hcc main.o -o Main [link]
./Main [running]
rocprof :
Name	                  Calls	TotalDurationNs	AverageNs	Percentage
void add<int>(int*, int*)	1	18520	        18520	      100



Add -fno-gpu-rdc to hipcc is  support an early finalization of device code.
In both cases(case1 and case2) the time taken Kernel  call difference is 149Ns.

Is -fno-gpu-rdc  impact on performance ? If yes is any optimize solution available?

I would like to know  is any an alternate solution(on below issue) there compile example.cpp with hipcc(without Add -fno-gpu-rdc) and link with g++.
Is any proper document on cross compile and link.

Issue:

$ hipcc -c example.cpp -o main.o
$ g++ -L/opt/rocm/lib  -lhip_hcc main.o -o Main
$ ./Main
terminate called after throwing an instance of 'std::runtime_error'
  what():  Missing metadata for __global__ function: _Z3addIiEvPT_S1_
Aborted (core dumped)
[example.zip](https://github.com/ROCm-Developer-Tools/HIP/files/3914946/example.zip)

**Comment by dmcdougall** [comment]
Is the 149ns performance drop repeatable?  149ns difference out of 18371ns is 0.8%.  I would be surprised if this was a consistent repeatable measurement given how little work is being done on the device in your example code; scaling an array of length `1000` by `2.0`.

**Comment by anilbommareddy** [comment]
149ns performance drop not repeatable. 
I cross checked the behavior in the  same machine(AMD GPU -Vega10). 
In Case 2 the kernel call time taken less compare to Case 1.

void add<int>(int*, int*)	1	24890	"24890"	100 (Case 1)
void add<int>(int*, int*)	1	18816	"18816"	100 (Case 2)

void add<int>(int*, int*)	1	25186	"25186"	100 (Case 1)
void add<int>(int*, int*)	1	18075	"18075"	100 (Case 2)

void add<int>(int*, int*)	1	21038	"21038"	100 (Case1)
void add<int>(int*, int*)	1	18371	"18371"	100 (Case2)

finalize GPU kernels at compile-time with -fno-gpu-rdc.
I have question using "-fno-gpu-rdc " impact on performance in run time

Example:
if device code compile with "hipcc -fno-gpu-rdc" and host code compile g++.
Both device code(object files) and host code(Object files) linked to execute.
Is  any Impact on GPU performance(Kernel run time)?

**Comment by dmcdougall** [comment]
> I have question on using "-fno-gpu-rdc " impact on performance GPU?

All the `-fno-gpu-rdc` option does is instruct the compiler to generate device code at compile time rather than at link time.  To do that, any device code that calls other device code must be in the same translation unit (that's why it is called `no-rdc`).

Exactly the same ISA is executing on the device in both cases:

```
$ /opt/rocm/bin/hipcc -c example.cpp -o main.o

$ /opt/rocm/bin/hipcc main.o -o main

$ /opt/rocm/bin/extractkernel -i main

$ /opt/rocm/bin/hipcc -fno-gpu-rdc -c example.cpp -o main_no_rdc.o

$ g++ -L/opt/rocm/lib main_no_rdc.o -o main_no_rdc -lhip_hcc

$ /opt/rocm/bin/extractkernel -i main_no_rdc

$ diff main-000-gfx906.isa main_no_rdc-000-gfx906.isa 
2c2
< main-000-gfx906.hsaco:        file format ELF64-amdgpu
---
> main_no_rdc-000-gfx906.hsaco: file format ELF64-amdgpu
```

The `diff` between the two kernel ISA files shows no changes in the device code.  There is no difference at all what happens on the device between the two cases.

I guess I am confused about your question.  What problem are you trying to solve?  I am not convinced 149ns is worth worrying about in the example you gave because it is such a small example.  Of course, if you're just asking because you're curious about what the compiler option does then fair enough.

**Comment by ppanchad-amd** [comment]
@holyprince Do you still need assistance with this ticket? If not, please close ticket. Thanks!

**Comment by yiakwy-xpu-ml-framework-team** [comment]
@anilbommareddy  it is generally not recommended to compile hip program with g++ (link with g++), since HIP api changes quickly.

In the recent programs, if you want to compile with g++, you need to link object files agiant "-lhiprtc" instead of old "-lhip_hcc".

Here is an example:

```
# link with g++ or clang++; 
vcopy: vcopy.o
	$(CXX) $(LIBS) -lhiprtc vcopy-dir/vcopy.o -o vcopy
```

To generate asm or object files with clang++:

```
hipcc $(CXXFLAGS) $(HIPXXFLAGS) $(LIBS) -O2 -S --offload-arch=gfx942 ../vcopy.cpp -o vcopy.S
``` 

or 


```
clang++ --offload-arch=gfx942 --driver-mode=g++ --hip-link  -fPIC -std=c++17 $(LIBS) -Wall -O2 -S -x hip vcopy.cpp -o "vcopy.S"
```
